### ISSUE TITLE
nginx shutting down和FIN_WAIT2

### ISSUE THREAD

**Issue by Shliesce** [weibocom/nginx-upsync-module#100]
1、nginx shutting down
这个其他issues有提到，当我添加vhost或者upstreams时，必须reload nginx，而这时会产生worker数量的shutting down进程，时间要很久。当我把upsync_timeout设到很短，比如2s时，并不是2s就消失了，还是持续很久。这个时间的具体长短，我还没测试出来。这个问题能不能解决下？reload时不要等待timeout？

2、FIN_WAIT2
upsync_timeout后，nginx会产生FIN_WAIT2，而consul server会产生CLOSE_WIAT。upsync_timeout时间越短，则产生越多。请问这个是什么原因？nginx在读取consul超时后断开连接时，为何consul没有发送fin包，导致这个tcp连接处于FIN_WAIT2和CLOSE_WAIT状态？

**Comment by xiaokai-wang** [comment]
1. nginx 的定时器 是轮询做的，不是硬中断，所以不会严格按照设置的时间来进行关闭，存在出入；reload 延迟关闭就得work 进程问题，我会尝试解决；

2. 感谢你对问题的反馈，如此认真仔细；你那边网络如何？换一个环境呢？

**Comment by Shliesce** [comment]
1、感谢你能抽时间解决第一个shutting down的问题，希望能尽快修复~
2、FIN_WAIT2和CLOSE_WAIT的问题。我把upsync_timeout设置到2s后（测试目的，为了尽快结束shutting down），就发现每2s nginx跟consul断开连接就会出现FIN_WAIT2 socket，数量相当多，毕竟每2s断开一次。如果设置timeout为2m，就没有这个问题了。

**Comment by xiaokai-wang** [comment]
FIN_WAIT2 会出现，但是也会关闭，这个关闭的时间取决于RTT 时长，我认为是可以理解的；

多谢使用！

**Comment by Shliesce** [comment]
对，是会关闭的，跟RTT有关，最后也会消失。
但这不是一个正常关闭的socket连接。等于是nginx超时后发送FIN给consul，consul响应ACK，然后就结束了，两边的socket都在等待一定时间后消失。我想问下你们开发这个模块的时候是否遇到过这个现象？

**Comment by xiaokai-wang** [comment]
为什么不正常？谁主动关闭连接，谁就发fin，谁就进入fin_wait 的状态；nginx 发现consul 没有在设置的时间回复，就会主动关闭连接！

另，nginx 旧的work 进程延迟退出严格的说不是bug，在正常服务的nginx reload 时也会发生延迟关闭的现象，因为它需要等待它所建立的连接收发完毕.

**Comment by Shliesce** [comment]
nginx主动关闭连接了，发送FIN了，但consul只发送了ACK没发送FIN，导致这是一个半断开连接，不是一个完整的断开连接。想问下你们遇到过这个现象没？
恩，不是BUG。一般情况reload时，需要等待它所建立的连接收发完毕是很快的，一般1S都不到，瞬时的。但我们的nginx启动的时候由于特殊配置，启动会很耗内存，大概一个G。如果短时间reload3次，就会有4倍的进程和内存消耗，多次reload时真的会发生内存耗尽的情况。这个我们自己想办法避免，确实不是BUG。

**Comment by gfrankliu** [comment]
在正常服务的nginx reload 时发生延迟关闭是没有办法的，除非你不在乎正在进行中的收发。
但upsync 的reload 延迟就是没有必要的”牺牲”了。

**Comment by Shliesce** [comment]
恩  是这个道理。

**Comment by xiaokai-wang** [comment]
在任何一个upstream 发送之前（取 conf server 信息）都会检查nginx 进程是否退出，如果显示的退出状态，便会清除所有upstream（配置了upsync）的已建立连接，从而让nginx 进程退出；（当前的实现）

一旦所有的upstream 与conf server 在连接状态，这个时候便不再受模块控制，nginx 进程退出，也只能等待任何一个upstream 返回 或timeout 才能关闭其它连接，从而退出；

如果必须要实时（相对）的能够退出，现在能够想到的是添加一个定时器，实时的监测nginx 进程的状态，如果要退出了则清除所有连接upstream 的连接，从而保证nginx 进程的退出；这个定时器时长设置短一些，唯一做的事情就是监测ngx_exiting || ngx_quit || ngx_terminate 的值；
你们认为这是有必要的吗？

nginx 作为代理对内存的消耗是极少的，在reload 的阶段会增长一些，我认为是有限的……欢迎探讨

**Comment by gfrankliu** [comment]
nginx 作为代理对内存的消耗少是相对而言的。正因为内存消耗少，一个服务器上可能会设有几千个Virtual Host。这样一来，总内存消耗就大了。另外，使用shm也会花内存。真正优化状态下，服务器一半的内存都用掉了。再来几下reload，就不行了。

upstream连接是否退出，不是问题。主要是upsync的退出。reload时，nginx新进程以生成，有了新的upsync连接，旧的等timeout就没有意义了。

**Comment by xiaokai-wang** [comment]
quickly close the connection with conf-server when reloading or replacing the binary, please have a try.

**Comment by Shliesce** [comment]
新代码跟nginx-1.10.1编译 make 报错，之前的版本跟nginx-1.10.1编译无问题
/tmp/nginx-upsync-module-master/src/ngx_http_upsync_module.c: In function 'ngx_http_upsync_etcd_parse_json':
/tmp/nginx-upsync-module-master/src/ngx_http_upsync_module.c:1364:37: error: variable 'upsync_type_conf' set but not used [-Werror=unused-but-set-variable]
     ngx_upsync_conf_t              *upsync_type_conf;
                                     ^
cc1: all warnings being treated as errors
objs/Makefile:1352: recipe for target 'objs/addon/src/ngx_http_upsync_module.o' failed
make[1]: *** [objs/addon/src/ngx_http_upsync_module.o] Error 1
make[1]: Leaving directory '/tmp/nginx-1.10.1'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by xiaokai-wang** [comment]
yeah, truly warning error. Not report in my version, strange. :-) thanks.

**Comment by CallMeFoxie** [comment]
Happens when compiling on debian as it defaults to -Wunused-but-set-variable and other hardening options. The upsync_type_conf var can be just removed as it is not used.

**Comment by xiaokai-wang** [comment]
yes, just be moved. : -). 👍 , thanks.

**Comment by Shliesce** [comment]
thanks very much

**Comment by gfrankliu** [comment]
confirmed working, thanks!
