### ISSUE TITLE
安装upsync到tengine-2.1.2报错

### ISSUE THREAD

**Issue by onkevin** [weibocom/nginx-upsync-module#101]
*Tengine version: Tengine/2.1.2 (nginx/1.6.2)
*upsync-1.0.0
make -j4报错如下，是兼容问题吗？我需要做哪些改动，请指导下，感谢！
../nginx-upsync-module-1.0.0/src/ngx_http_upsync_module.c:11:0:
../nginx-upsync-module-1.0.0/src/ngx_http_upsync_module.h: In function ‘ngx_http_upsync_chash’:
../nginx-upsync-module-1.0.0/src/ngx_http_upsync_module.h:210:19: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘server’
     server = &peer->server;
                   ^
../nginx-upsync-module-1.0.0/src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_add_peers’:
../nginx-upsync-module-1.0.0/src/ngx_http_upsync_module.c:810:27: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘server’
             peers->peer[m].server.len = server->addrs->name.len;
                           ^
../nginx-upsync-module-1.0.0/src/ngx_http_upsync_module.c:811:27: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘server’
             peers->peer[m].server.data = server->addrs->name.data;
                           ^
../nginx-upsync-module-1.0.0/src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_del_peers’:
../nginx-upsync-module-1.0.0/src/ngx_http_upsync_module.c:991:31: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘server’
                 peers->peer[n].server.len = tmp_peers->peer[i].server.len;
                               ^
../nginx-upsync-module-1.0.0/src/ngx_http_upsync_module.c:991:63: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘server’
                 peers->peer[n].server.len = tmp_peers->peer[i].server.len;
                                                               ^
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions  -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -DNDK_SET_VAR  -I src/core -I src/event -I src/event/modules -I src/os/unix -I src/proc -I ../ngx_image_thumb-master/ -I ../ngx_devel_kit/objs -I objs/addon/ndk -I /usr/local/include/luajit-2.0/ -I modules/ngx_http_lua_module/src/api -I objs -I src/http -I src/http/modules -I ../ngx_devel_kit/src -I src/mail \
	-o objs/addon/src/ngx_http_parser.o \
	../nginx-upsync-module-1.0.0/src/ngx_http_parser.c
../nginx-upsync-module-1.0.0/src/ngx_http_upsync_module.c:992:31: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘server’
                 peers->peer[n].server.data = tmp_peers->peer[i].server.data;
                               ^
../nginx-upsync-module-1.0.0/src/ngx_http_upsync_module.c:992:64: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘server’
                 peers->peer[n].server.data = tmp_peers->peer[i].server.data;
                                                                ^
../nginx-upsync-module-1.0.0/src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_init_peers’:
../nginx-upsync-module-1.0.0/src/ngx_http_upsync_module.c:2195:27: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘server’
             peers->peer[i].server = peers->peer[i].name;
                           ^
make[1]: *** [objs/addon/src/ngx_http_upsync_module.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/usr/src/tengine-2.1.2'
make: *** [build] Error 2

**Comment by xiaokai-wang** [comment]
sorry, not support  nginx-1.8.0-.

暂不支持低于nginx-1.8.0 版本
