### ISSUE TITLE
NULL point panic

### ISSUE THREAD

**Issue by datastream** [weibocom/nginx-upsync-module#102]
I just find some Segmentation fault, when nginx reload.  It turns out `upsync_server->upscf` is null point, if nginx run without upsync config.

`    upsync_server = upsync_ctx->upsync_server;
     upsync_type_conf = upsync_server->upscf->upsync_type_conf;
`
https://github.com/weibocom/nginx-upsync-module/blob/a0b9f02895b3b1df373a121370249bbbcf9025bf/src/ngx_http_upsync_module.c#L3372

Reproduce step:
1. run nginx without any upsync config
2. run nginx -s reload

**Comment by xiaokai-wang** [comment]
Fixed, thanks for your report. Please have a try.
