### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by fastio** [weibocom/nginx-upsync-module#104]
错误信息：```nginx-upsync-module/src/ngx_http_upsync_module.c:829:17: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
             peer->next = peers->peer;```

查看代码，发现结构体```ngx_http_upstream_rr_peer_t``` 确实没有next 成员变量。

**Comment by xiaokai-wang** [comment]
你的nginx 是什么版本？master 分支支持nginx-1.9.0+；nginx-upsync-1.8.x 分支支持nginx-1.8.0+.

请注意.
