### ISSUE TITLE
make 报错

### ISSUE THREAD

**Issue by qwe109** [weibocom/nginx-upsync-module#106]
centos-6
nginx-1.8.0
upsync-1.8.x

	../../nginx-upsync-module-nginx-upsync-1.8.x/src/ngx_http_upsync_module.c
../../nginx-upsync-module-nginx-upsync-1.8.x/src/ngx_http_upsync_module.c: 在函数‘ngx_http_upsync_add_peers’中:
../../nginx-upsync-module-nginx-upsync-1.8.x/src/ngx_http_upsync_module.c:823: 错误：‘ngx_http_upstream_rr_peer_t’没有名为‘check_index’的成员
../../nginx-upsync-module-nginx-upsync-1.8.x/src/ngx_http_upsync_module.c: 在函数‘ngx_http_upsync_del_peers’中:
../../nginx-upsync-module-nginx-upsync-1.8.x/src/ngx_http_upsync_module.c:1001: 错误：‘ngx_http_upstream_rr_peer_t’没有名为‘check_index’的成员
../../nginx-upsync-module-nginx-upsync-1.8.x/src/ngx_http_upsync_module.c:1001: 错误：‘ngx_http_upstream_rr_peer_t’没有名为‘check_index’的成员
../../nginx-upsync-module-nginx-upsync-1.8.x/src/ngx_http_upsync_module.c: 在函数‘ngx_http_upsync_init_peers’中:
../../nginx-upsync-module-nginx-upsync-1.8.x/src/ngx_http_upsync_module.c:2198: 错误：‘ngx_http_upstream_rr_peer_t’没有名为‘check_index’的成员
../../nginx-upsync-module-nginx-upsync-1.8.x/src/ngx_http_upsync_module.c:2198: 错误：‘ngx_http_upstream_rr_peer_t’没有名为‘check_index’的成员
make[1]: *** [objs/addon/src/ngx_http_upsync_module.o] 错误 1
单独make&makeinstall upsync没有问题，但是加上nginx_upstream_check_module-master就报错

**Comment by xiaokai-wang** [comment]
没有打check.patch 的补丁

**Comment by qwe109** [comment]
非常感谢@xiaokai-wang

**Comment by bobo213** [comment]
centos7.2
tengine-2.2.0
编译时出现如下错误。

In file included from /home/appsvr/nginx-upsync-module-master/src/ngx_http_upsync_module.c:11:0:
/home/appsvr/nginx-upsync-module-master/src/ngx_http_upsync_module.h: 在函数‘ngx_http_upsync_chash_init’中:
/home/user/nginx-upsync-module-master/src/ngx_http_upsync_module.h:151:51: 错误：‘ngx_http_upstream_rr_peer_t’没有名为‘next’的成员
         for (peer = peers->peer; peer; peer = peer->next) {
                                                   ^
/home/user/nginx-upsync-module-master/src/ngx_http_upsync_module.h: 在函数‘ngx_http_upsync_del_chash_peer’中:
/home/appsvr/nginx-upsync-module-master/src/ngx_http_upsync_module.h:284:47: 错误：‘ngx_http_upstream_rr_peer_t’没有名为‘next’的成员
     for (peer = peers->peer; peer; peer = peer->next) {
                                               ^

**Comment by bobo213** [comment]
check.patch 的补丁怎么打？

**Comment by qwe109** [comment]
@bobo213 安装nginx_upstream_check_module-master下的 check.patch
