### ISSUE TITLE
如果旧server地址是新server地址的子串，则添加会失败

### ISSUE THREAD

**Issue by yangguilong** [weibocom/nginx-upsync-module#111]
如果原来已有 `210.32.142.88:80` 这样一个server，这时候consul上面新出现了 `210.32.142.8081` 和 `210.32.142.8088` 这样的新server （旧server地址是新server地址的子串），后面这些不能给正确加入。

问题在于 `ngx_http_upsync_add_filter` 这里面的如下代码:

```
            if (ngx_memcmp(peer->name.data, 
                           upstream_conf->sockaddr, peer->name.len) == 0) {
                break;
            }
```

这里只比较 `peer->name.len` 这么长是不够的，应该改为 `peer->name.len + 1`，或者改用 `ngx_memn2cmp`

**Comment by xiaokai-wang** [comment]
这个函数不只是比较长度的吧

**Comment by yangguilong** [comment]
改为 `peer->name.len + 1` 也不对，还是应该用 `ngx_memn2cmp`。

目前的用法会导致 `ngx_memcmp`认为 `210.32.142.88:80` 跟 `210.32.142.88:8080` 是一样的。

`ngx_http_upsync_remove_filter` 和`ngx_http_upsync_update_peers` 有同样的问题。

**Comment by xiaokai-wang** [comment]
嗯，这种情况是可能存在的，提一个pr？welcome.

**Comment by yangguilong** [comment]
PR:  #112
