### ISSUE TITLE
nginx-1.8.0 and nginx-1.10.2 compile error

### ISSUE THREAD

**Issue by jaylwlm** [weibocom/nginx-upsync-module#115]
when i compile this module with nginx1.8 or nginx 1.10 ，all errors。

--------------------------------------------------------
1.8
error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
             peer->next = peers->peer;

1.10
/root/nginx-upsync-module/src/ngx_http_upsync_module.c:945:49: error: variable ‘len’ set but not used [-Werror=unused-but-set-variable]
     ngx_uint_t                     i, n=0, w=0, len=0;
/root/nginx-upsync-module/src/ngx_http_upsync_module.c:1114:9: error: ‘return’ with no value, in function returning non-void [-Werror=return-type]
         return;

-----------------------------------------------------------------

# git clone https://github.com/weibocom/nginx-upsync-module
# ./configure \
--prefix=/usr/local/nginx \
--user=nginx \
--group=nginx \
--with-http_gzip_static_module \
--with-http_ssl_module \
--with-http_stub_status_module \
--with-zlib=/root/zlib-1.2.8 \
--with-pcre=/root/pcre-8.38 \
--add-module=/root/nginx-upsync-module

**Comment by Phipray** [comment]
me too !
when I compile this module with nginx1.8
`../nginx-upsync-module/src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_add_peers’:
../nginx-upsync-module/src/ngx_http_upsync_module.c:829:17: error: ‘ngx_http_upstream_rr_peer_t {aka struct <anonymous>}’ has no member named ‘next’
             peer->next = peers->peer;
                 ^
../nginx-upsync-module/src/ngx_http_upsync_module.c:830:25: error: assignment to expression with array type
             peers->peer = peer;
                         ^
../nginx-upsync-module/src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_add_filter’:
../nginx-upsync-module/src/ngx_http_upsync_module.c:922:58: error: ‘ngx_http_upstream_rr_peer_t {aka struct <anonymous>}’ has no member named ‘next’
         for (peer = peers->peer, j = 0; peer; peer = peer->next, j++) {
                                                          ^
../nginx-upsync-module/src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_del_peers’:
../nginx-upsync-module/src/ngx_http_upsync_module.c:982:47: error: ‘ngx_http_upstream_rr_peer_t {aka struct <anonymous>}’ has no member named ‘next’
     for (peer = peers->peer; peer; peer = peer->next) {
                                               ^
../nginx-upsync-module/src/ngx_http_upsync_module.c:1001:33: error: ‘ngx_http_upstream_rr_peer_t {aka struct <anonymous>}’ has no member named ‘next’
                     tmp_del_peer->next = peer;
                                 ^
../nginx-upsync-module/src/ngx_http_upsync_module.c:1007:39: error: ‘ngx_http_upstream_rr_peer_t {aka struct <anonymous>}’ has no member named ‘next’
                     peers->peer = peer->next;
                                       ^
../nginx-upsync-module/src/ngx_http_upsync_module.c:1008:36: error: ‘ngx_http_upstream_rr_peer_t {aka struct <anonymous>}’ has no member named ‘next’
                     pre_peer = peer->next;
                                    ^
../nginx-upsync-module/src/ngx_http_upsync_module.c:1011:29: error: ‘ngx_http_upstream_rr_peer_t {aka struct <anonymous>}’ has no member named ‘next’
                     pre_peer->next = peer->next;
                             ^
../nginx-upsync-module/src/ngx_http_upsync_module.c:1011:42: error: ‘ngx_http_upstream_rr_peer_t {aka struct <anonymous>}’ has no member named ‘next’
                     pre_peer->next = peer->next;
                                          ^
../nginx-upsync-module/src/ngx_http_upsync_module.c:1023:17: error: ‘ngx_http_upstream_rr_peer_t {aka struct <anonymous>}’ has no member named ‘next’
     tmp_del_peer->next = NULL;
                 ^
../nginx-upsync-module/src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_del_filter’:
../nginx-upsync-module/src/ngx_http_upsync_module.c:1073:47: error: ‘ngx_http_upstream_rr_peer_t {aka struct <anonymous>}’ has no member named ‘next’
     for (peer = peers->peer; peer; peer = peer->next) {
                                               ^
../nginx-upsync-module/src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_update_peers’:
../nginx-upsync-module/src/ngx_http_upsync_module.c:1124:47: error: ‘ngx_http_upstream_rr_peer_t {aka struct <anonymous>}’ has no member named ‘next’
     for (peer = peers->peer; peer; peer = peer->next) {
                                               ^
../nginx-upsync-module/src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_init_peers’:
../nginx-upsync-module/src/ngx_http_upsync_module.c:2163:17: error: ‘ngx_http_upstream_rr_peer_t {aka struct <anonymous>}’ has no member named ‘next’
             peer->next = peers->peer;
                 ^
../nginx-upsync-module/src/ngx_http_upsync_module.c:2164:25: error: assignment to expression with array type
             peers->peer = peer;
                         ^
../nginx-upsync-module/src/ngx_http_upsync_module.c:2167:21: error: ‘ngx_http_upstream_rr_peer_t {aka struct <anonymous>}’ has no member named ‘next’
                 peer->next = NULL;
                     ^
../nginx-upsync-module/src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_dump_server’:
../nginx-upsync-module/src/ngx_http_upsync_module.c:2852:47: error: ‘ngx_http_upstream_rr_peer_t {aka struct <anonymous>}’ has no member named ‘next’
     for (peer = peers->peer; peer; peer = peer->next) {
                                               ^
../nginx-upsync-module/src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_del_delay_delete’:
../nginx-upsync-module/src/ngx_http_upsync_module.c:3119:20: error: ‘ngx_http_upstream_rr_peer_t {aka struct <anonymous>}’ has no member named ‘next’
         peer = peer->next;
                    ^
../nginx-upsync-module/src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_show_upstream’:
../nginx-upsync-module/src/ngx_http_upsync_module.c:3656:47: error: ‘ngx_http_upstream_rr_peer_t {aka struct <anonymous>}’ has no member named ‘next’
     for (peer = peers->peer; peer; peer = peer->next) {
                                               ^
objs/Makefile:1145: recipe for target 'objs/addon/src/ngx_http_upsync_module.o' failed
make[1]: *** [objs/addon/src/ngx_http_upsync_module.o] Error 1
make[1]: Leaving directory '/opt/nginx/nginx-1.8.0'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2
`
./configure  
--add-module=../nginx-upsync-module 
--add-module=../nginx-stream-upsync-module 
--with-http_ssl_module  
--with-http_ssl_module   
--with-pcre=../pcre-8.36 
--with-zlib=../zlib-1.2.8 
--with-openssl=../openssl-1.0.2d

**Comment by Phipray** [comment]
I know how to fix, branch master is for nginx1.9+, We need to use nginx-upsync-1.8x

**Comment by xiaokai-wang** [comment]
Fixed up.

Thanks, try again.
