### ISSUE TITLE
nginx version: openresty/1.9.7.3   compile error

### ISSUE THREAD

**Issue by Phipray** [weibocom/nginx-upsync-module#116]
When I compiled this module ( Branch:master )  with openresty/1.9.7.3 (nginx 1.9.7.3) on ubuntu16.04 , I found some errors

> ./configure  --with-http_stub_status_module --add-module=../nginx-http-sysguard-master  --add-module=../nginx-upsync-module  --add-module=../nginx-stream-upsync-module  --with-http_ssl_module --with-zlib=../zlib-1.2.8 --with-openssl=../openssl-1.0.2d

> make
-----------------------------------------------------------------------------------------
`objs/addon/src/ngx_stream_json.o: In function `cJSON_GetErrorPtr':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:37: multiple definition of `cJSON_GetErrorPtr'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:37: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_InitHooks':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:62: multiple definition of `cJSON_InitHooks'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:62: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_Delete':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:84: multiple definition of `cJSON_Delete'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:84: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_ParseWithOpts':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:253: multiple definition of `cJSON_ParseWithOpts'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:253: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_Parse':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:268: multiple definition of `cJSON_Parse'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:268: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_Print':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:271: multiple definition of `cJSON_Print'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:271: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_PrintUnformatted':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:272: multiple definition of `cJSON_PrintUnformatted'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:272: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_GetArraySize':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:498: multiple definition of `cJSON_GetArraySize'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:498: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_GetArrayItem':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:499: multiple definition of `cJSON_GetArrayItem'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:499: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_GetObjectItem':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:500: multiple definition of `cJSON_GetObjectItem'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:500: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_AddItemToArray':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:508: multiple definition of `cJSON_AddItemToArray'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:508: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_AddItemToObject':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:509: multiple definition of `cJSON_AddItemToObject'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:509: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_AddItemReferenceToArray':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:510: multiple definition of `cJSON_AddItemReferenceToArray'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:510: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_AddItemReferenceToObject':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:511: multiple definition of `cJSON_AddItemReferenceToObject'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:511: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_DetachItemFromArray':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:513: multiple definition of `cJSON_DetachItemFromArray'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:513: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_DeleteItemFromArray':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:515: multiple definition of `cJSON_DeleteItemFromArray'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:515: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_DetachItemFromObject':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:516: multiple definition of `cJSON_DetachItemFromObject'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:516: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_DeleteItemFromObject':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:517: multiple definition of `cJSON_DeleteItemFromObject'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:517: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_ReplaceItemInArray':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:520: multiple definition of `cJSON_ReplaceItemInArray'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:520: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_ReplaceItemInObject':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:523: multiple definition of `cJSON_ReplaceItemInObject'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:523: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_CreateNull':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:526: multiple definition of `cJSON_CreateNull'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:526: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_CreateTrue':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:527: multiple definition of `cJSON_CreateTrue'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:527: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_CreateFalse':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:528: multiple definition of `cJSON_CreateFalse'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:528: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_CreateBool':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:529: multiple definition of `cJSON_CreateBool'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:529: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_CreateNumber':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:530: multiple definition of `cJSON_CreateNumber'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:530: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_CreateString':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:531: multiple definition of `cJSON_CreateString'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:531: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_CreateArray':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:532: multiple definition of `cJSON_CreateArray'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:532: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_CreateObject':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:533: multiple definition of `cJSON_CreateObject'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:533: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_CreateIntArray':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:536: multiple definition of `cJSON_CreateIntArray'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:536: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_CreateFloatArray':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:537: multiple definition of `cJSON_CreateFloatArray'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:537: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_CreateDoubleArray':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:538: multiple definition of `cJSON_CreateDoubleArray'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:538: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_CreateStringArray':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:539: multiple definition of `cJSON_CreateStringArray'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:539: first defined here
objs/addon/src/ngx_stream_json.o: In function `cJSON_Duplicate':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_json.c:546: multiple definition of `cJSON_Duplicate'
objs/addon/src/ngx_http_json.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_json.c:546: first defined here
objs/addon/src/ngx_stream_http_parser.o: In function `http_message_needs_eof':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_http_parser.c:2083: multiple definition of `http_message_needs_eof'
objs/addon/src/ngx_http_parser.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_parser.c:2083: first defined here
objs/addon/src/ngx_stream_http_parser.o: In function `http_should_keep_alive':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_http_parser.c:2108: multiple definition of `http_should_keep_alive'
objs/addon/src/ngx_http_parser.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_parser.c:2108: first defined here
objs/addon/src/ngx_stream_http_parser.o: In function `http_parser_execute':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_http_parser.c:630: multiple definition of `http_parser_execute'
objs/addon/src/ngx_http_parser.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_parser.c:630: first defined here
objs/addon/src/ngx_stream_http_parser.o: In function `http_method_str':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_http_parser.c:2124: multiple definition of `http_method_str'
objs/addon/src/ngx_http_parser.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_parser.c:2124: first defined here
objs/addon/src/ngx_stream_http_parser.o: In function `http_parser_init':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_http_parser.c:2134: multiple definition of `http_parser_init'
objs/addon/src/ngx_http_parser.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_parser.c:2134: first defined here
objs/addon/src/ngx_stream_http_parser.o: In function `memset':
/usr/include/x86_64-linux-gnu/bits/string3.h:90: multiple definition of `http_parser_settings_init'
objs/addon/src/ngx_http_parser.o:/usr/include/x86_64-linux-gnu/bits/string3.h:90: first defined here
objs/addon/src/ngx_stream_http_parser.o: In function `http_errno_name':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_http_parser.c:2147: multiple definition of `http_errno_name'
objs/addon/src/ngx_http_parser.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_parser.c:2147: first defined here
objs/addon/src/ngx_stream_http_parser.o: In function `http_errno_description':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_http_parser.c:2153: multiple definition of `http_errno_description'
objs/addon/src/ngx_http_parser.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_parser.c:2153: first defined here
objs/addon/src/ngx_stream_http_parser.o: In function `http_parser_parse_url':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_http_parser.c:2298: multiple definition of `http_parser_parse_url'
objs/addon/src/ngx_http_parser.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_parser.c:2298: first defined here
objs/addon/src/ngx_stream_http_parser.o: In function `http_parser_pause':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_http_parser.c:2400: multiple definition of `http_parser_pause'
objs/addon/src/ngx_http_parser.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_parser.c:2400: first defined here
objs/addon/src/ngx_stream_http_parser.o: In function `http_body_is_final':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_http_parser.c:2410: multiple definition of `http_body_is_final'
objs/addon/src/ngx_http_parser.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_parser.c:2410: first defined here
objs/addon/src/ngx_stream_http_parser.o: In function `http_parser_version':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_http_parser.c:2418: multiple definition of `http_parser_version'
objs/addon/src/ngx_http_parser.o:/opt/nginx-lua/openresty-1.9.7.3/../nginx-upsync-module/src/ngx_http_parser.c:2418: first defined here
objs/addon/src/ngx_stream_upsync_module.o: In function `ngx_stream_upsync_set':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_upsync_module.c:3582: undefined reference to `ngx_stream_core_module'
objs/addon/src/ngx_stream_upsync_module.o: In function `ngx_stream_upsync_chash_init':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_upsync_module.h:183: undefined reference to `ngx_stream_upstream_hash_module'
objs/addon/src/ngx_stream_upsync_module.o: In function `ngx_stream_upsync_init_main_conf':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_upsync_module.c:1743: undefined reference to `ngx_stream_upstream_module'
objs/addon/src/ngx_stream_upsync_module.o: In function `ngx_stream_upsync_show':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_upsync_module.c:3693: undefined reference to `ngx_stream_module'
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_upsync_module.c:3693: undefined reference to `ngx_stream_upstream_module'
objs/addon/src/ngx_stream_upsync_module.o: In function `ngx_stream_upsync_del_chash_peer':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_upsync_module.h:259: undefined reference to `ngx_stream_upstream_hash_module'
objs/addon/src/ngx_stream_upsync_module.o: In function `ngx_stream_upsync_show':
/opt/nginx-lua/openresty-1.9.7.3/../nginx-stream-upsync-module/src/ngx_stream_upsync_module.c:3704: undefined reference to `ngx_stream_close_connection'
collect2: error: ld returned 1 exit status
objs/Makefile:385: recipe for target 'objs/nginx' failed
make[2]: *** [objs/nginx] Error 1
make[2]: Leaving directory '/opt/nginx-lua/openresty-1.9.7.3/build/nginx-1.9.7'
Makefile:8: recipe for target 'build' failed
make[1]: *** [build] Error 2
make[1]: Leaving directory '/opt/nginx-lua/openresty-1.9.7.3/build/nginx-1.9.7'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2`

Is that what patch need me to patch before compile ?

**Comment by xiaokai-wang** [comment]
upsync-module and stream-upsync-module are compiled together, please refer to https://github.com/CallMeFoxie/nginx-upsync
