### ISSUE TITLE
sticky session with upsync module

### ISSUE THREAD

**Issue by gfrankliu** [weibocom/nginx-upsync-module#119]
Has anybody tried https://bitbucket.org/nginx-goodies/nginx-sticky-module-ng or other nginx upstream sticky module?

**Comment by freexp** [comment]
i have tried sticky and it not work.
then i tried --with-http_realip_module, but 
nginx: [emerg] "real_ip_header" directive is not allowed here in /usr/local/nginx/conf/nginx.conf:109

**Comment by gfrankliu** [comment]
I am not sure how realip module would help sticky. Are you talking something different?
BTW, I've used realip module without a problem with upsync module.

**Comment by freexp** [comment]
I was tried to use realip module to get the real ip behind F5 and ip_hash module to load balance.

**Comment by gfrankliu** [comment]
@freexp when you said "I have tried sticky and it not work", what problem did you see? 
Did you apply this patch https://github.com/yaoweibin/nginx_upstream_check_module/blob/master/nginx-sticky-module.patch ?

**Comment by xuhengpw** [comment]
@gfrankliu  补丁怎么打?

patch -p0 < /usr/local/src/nginx-sticky-module.patch 
patching file ngx_http_sticky_module.c
Hunk #1 succeeded at 15 with fuzz 2 (offset 5 lines).
Hunk #2 succeeded at 304 (offset 12 lines).
Hunk #3 succeeded at 330 (offset 12 lines).
Hunk #4 succeeded at 352 (offset 12 lines).

**Comment by gfrankliu** [comment]
@xuhengpw Your above shows patch has been applied successfully. Do you still have issues?
