### ISSUE TITLE
centos7   安装nginx-upsync-module报错，模块支持centos7吗？

### ISSUE THREAD

**Issue by 79658788** [weibocom/nginx-upsync-module#122]
nginx-upsync-module 模块支持centos7吗？

系统：centos7 minion
nginx版本：nginx-1.8.1
依赖包yum安装：yum install zlib pcre pcre-devel openssl openssl-devel   -y
编译参数：
./configure  --user=nginx --group=nginx --prefix=/usr/local/nginx  --with-pcre  --with-http_stub_status_module --with-http_ssl_module --with-http_gzip_static_module --with-http_realip_module --with-http_sub_module  --add-module=/root/nginx-upsync-module/

make出错信息如下：
/root/nginx-upsync-module//src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_add_peers’:
/root/nginx-upsync-module//src/ngx_http_upsync_module.c:830:17: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘conns’
             peer->conns = 0;
                 ^
/root/nginx-upsync-module//src/ngx_http_upsync_module.c:832:17: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
             peer->next = peers->peer;
                 ^
/root/nginx-upsync-module//src/ngx_http_upsync_module.c:833:25: error: incompatible types when assigning to type ‘struct ngx_http_upstream_rr_peer_t[1]’ from type ‘struct ngx_http_upstream_rr_peer_t *’
             peers->peer = peer;
                         ^
/root/nginx-upsync-module//src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_add_filter’:
/root/nginx-upsync-module//src/ngx_http_upsync_module.c:920:58: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
         for (peer = peers->peer, j = 0; peer; peer = peer->next, j++) {
                                                          ^
/root/nginx-upsync-module//src/ngx_http_upsync_module.c:920:64: error: left-hand operand of comma expression has no effect [-Werror=unused-value]
         for (peer = peers->peer, j = 0; peer; peer = peer->next, j++) {
                                                                ^
/root/nginx-upsync-module//src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_del_peers’:
/root/nginx-upsync-module//src/ngx_http_upsync_module.c:982:47: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
     for (peer = peers->peer; peer; peer = peer->next) {
                                               ^
/root/nginx-upsync-module//src/ngx_http_upsync_module.c:1000:33: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
                     tmp_del_peer->next = peer;
                                 ^
/root/nginx-upsync-module//src/ngx_http_upsync_module.c:1006:39: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
                     peers->peer = peer->next;
                                       ^
/root/nginx-upsync-module//src/ngx_http_upsync_module.c:1007:36: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
                     pre_peer = peer->next;
                                    ^
/root/nginx-upsync-module//src/ngx_http_upsync_module.c:1010:29: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
                     pre_peer->next = peer->next;
                             ^
/root/nginx-upsync-module//src/ngx_http_upsync_module.c:1010:42: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
                     pre_peer->next = peer->next;
                                          ^
/root/nginx-upsync-module//src/ngx_http_upsync_module.c:1022:17: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
     tmp_del_peer->next = NULL;
                 ^
/root/nginx-upsync-module//src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_del_filter’:
/root/nginx-upsync-module//src/ngx_http_upsync_module.c:1067:47: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
     for (peer = peers->peer; peer; peer = peer->next) {
                                               ^
/root/nginx-upsync-module//src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_update_peers’:
/root/nginx-upsync-module//src/ngx_http_upsync_module.c:1117:47: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
     for (peer = peers->peer; peer; peer = peer->next) {
                                               ^
/root/nginx-upsync-module//src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_init_peers’:
/root/nginx-upsync-module//src/ngx_http_upsync_module.c:2155:17: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘conns’
             peer->conns = 0;
                 ^
/root/nginx-upsync-module//src/ngx_http_upsync_module.c:2160:17: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
             peer->next = peers->peer;
                 ^
/root/nginx-upsync-module//src/ngx_http_upsync_module.c:2161:25: error: incompatible types when assigning to type ‘struct ngx_http_upstream_rr_peer_t[1]’ from type ‘struct ngx_http_upstream_rr_peer_t *’
             peers->peer = peer;
                         ^
/root/nginx-upsync-module//src/ngx_http_upsync_module.c:2164:21: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
                 peer->next = NULL;
                     ^
/root/nginx-upsync-module//src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_dump_server’:
/root/nginx-upsync-module//src/ngx_http_upsync_module.c:2845:47: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
     for (peer = peers->peer; peer; peer = peer->next) {
                                               ^
/root/nginx-upsync-module//src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_del_delay_delete’:
/root/nginx-upsync-module//src/ngx_http_upsync_module.c:3112:20: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
         peer = peer->next;
                    ^
/root/nginx-upsync-module//src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_show_upstream’:
/root/nginx-upsync-module//src/ngx_http_upsync_module.c:3654:47: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
     for (peer = peers->peer; peer; peer = peer->next) {
                                               ^
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/src/ngx_http_upsync_module.o] Error 1
make[1]: Leaving directory `/root/nginx-1.8.1'
make: *** [build] Error 2

**Comment by CallMeFoxie** [comment]
Please use branch nginx-upsync-1.8.x

**Comment by 79658788** [comment]
3Q
