### ISSUE TITLE
nginx-upsync-module安装正常，session会话保持有什么建议？

### ISSUE THREAD

**Issue by 79658788** [weibocom/nginx-upsync-module#123]
nginx-upsync-module安装正常，nginx-sticky-module-ng模块用来做session会话保持，测试发现有问题。不一定必须用nginx-sticky-module-ng模块来处理session会话问题，有没有其他方式来解决session会话的问题，有什么建议？

环境：nginx1.8   
模块：nginx-upsync-module-1.0.0 ， nginx_upstream_check_module-master ， nginx-sticky-module-ng

1：不用upsync模块功能，nginx-sticky-module-ng模块session会话保持功能正常，配置如下：
      upstream test{
      sticky;
      server 192.168.10.79:8080 fail_timeout=50 max_fails=2;
      server 192.168.10.79:8081 fail_timeout=50 max_fails=2;
}

2：使用upsync模块功能，nginx-sticky-module-ng模块session会话不能正常保持会话，访问会出现轮询的状态。  
upstream upsync{
        sticky;
        # fake server otherwise ngx_http_upstream will report error when startup
        server 127.0.0.1:11111;
        # all backend server will pull from consul when startup and will delete fake server
        upsync 192.168.10.78:8500/v1/kv/upstreams/upsync upsync_timeout=6m upsync_interval=500ms upsync_type=consul strong_dependency=off;
        upsync_dump_path /usr/local/nginx/conf/servers/servers_upsync.conf;
}

**Comment by xiaokai-wang** [comment]
这个模块没有研究过，理论上应该不影响，本模块只有在server 有变化的时候才做更新；

一起学习，欢迎pr.

**Comment by xuhengpw** [comment]
期待支持session_sticky的解决方案。我也遇到这种问题。

**Comment by gfrankliu** [comment]
我试过nginx-sticky-module-ng模块，如果你加了布丁：https://github.com/yaoweibin/nginx_upstream_check_module/blob/master/nginx-sticky-module.patch 应该没有问题。
The sticky is based on cookie, so your client has to support cookie. If you use curl to send multiple request, you will not see the stickiness, unless you manually inject the cookie header.
