### ISSUE TITLE
crash while reloading nginx if consistent hash is used

### ISSUE THREAD

**Issue by bluestn** [weibocom/nginx-upsync-module#124]
in function ngx_http_upsync_del_chash_peer

the follwing code has the bug:

    for (i = 0; i < peers->number; i++) {
        peer = &peers->peer[i];
        ngx_http_upsync_chash(peer, points);

    }

because peers is not a C array, but a link

can  modify the above codes as the following:

    for (peer = peers->peer; peer; peer = peer->next) {
           ngx_http_upsync_chash(peer, points);
     }

**Comment by xiaokai-wang** [comment]
What's the version of nginx? If it is, a pr is much welcome.

**Comment by bluestn** [comment]
version is nginx 10.0.1,
but this bug has no relationship with nginx version.

在 2016-11-25 19:14:18，xiaokai <notifications@github.com> 写道：


What's the version of nginx? If it is, a pr is much welcome.

**Comment by xiaokai-wang** [comment]
Thanks.

**Comment by xiaokai-wang** [comment]
I update consistent-hash of load balance and test it offline. 

Please have a try.

**Comment by bluestn** [comment]
thank u, test is ok now.
