### ISSUE TITLE
Round Robin doesn't work properly

### ISSUE THREAD

**Issue by gfrankliu** [weibocom/nginx-upsync-module#126]
upsync seems to have broken the round robin. 
e.g.: I can see there are two upstream servers in the dump file. If I send request to nginx every 5 second, I can see all the requests are going to the first upstream server as shown in the dump file. Round robin doesn't seem to work.

BTW, I see the dump file is being updated every few seconds, even though nothing is changing. I suspect every time when the dump file is updated, the upstream pool definition is reloaded, and the round robin count is reset. That's why nginx will send the next request to the first upstream server always, due to the round robin information got reset.

**Comment by CallMeFoxie** [comment]
Yes, whenever the upstream definition reloads it resets the round robin counter. It should not be updating all the time though. Is there something writing to etcd/consul to the upstream definition?

**Comment by gfrankliu** [comment]
We are using consul and there were no changes in consul kv tree during the few minutes when I was watching the dump file, but when I "stat" the dump file, I can see its modification time kept updating every couple of seconds.

**Comment by gfrankliu** [comment]
I take it back. I talked to our developer and it seems there is an app that writes the exact same data to the kv tree every few seconds.
