### ISSUE TITLE
nginx-upsync-module与nginx-module-vts共同使用的问题

### ISSUE THREAD

**Issue by saga1015** [weibocom/nginx-upsync-module#127]
大神，我这边测试upsync模块，现在全都测试通过，也工作正常，为了查看每一个upstream里server的状态，我增加了nginx-module-vts模块，动态载入后，发现除了在upstream中的fake server可以看到外，实际通过consul载入的server一个都看不到，请教大神如何来弄呢

**Comment by xiaokai-wang** [comment]
酷；

这个应该是需要对方支持一下.

**Comment by hadret** [comment]
Hi guys,

just wanted to let you know, that this bug can be actually closed as resolved. @xiaokai-wang with your recent changes to upsync (i.e. dumping of the upstream servers to a file and then including it back) are solving "fake server" issue vts was having.

Thanks a lot for your work!
