### ISSUE TITLE
ngx_http_upstream_rr_peer_t’ has no member named check_index

### ISSUE THREAD

**Issue by wsw79wsw** [weibocom/nginx-upsync-module#128]
In function ‘ngx_http_upsync_add_peers’:
error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘check_index’
In function ‘ngx_http_upsync_del_peers’:
error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘check_index’
In function ‘ngx_http_upsync_init_peers’:
error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘check_index’

**Comment by wsw79wsw** [comment]
--add-module=../nginx_upstream_check_module-master

**Comment by xiaokai-wang** [comment]
First: patch -p1 < check.patch;

Then: ./configure --add-module=../nginx_upstream_check_module-master --add-module=../nginx-upsync-module

Try.

**Comment by wsw79wsw** [comment]
The new error.
objs/addon/src/ngx_http_upsync_module.o: In function `ngx_http_upsync_add_peers':
/opt/nginx/openresty-1.9.7.5/../nginx-upsync-module-master/src/ngx_http_upsync_module.c:852: undefined reference to `ngx_http_upstream_check_add_dynamic_peer'
objs/addon/src/ngx_http_upsync_module.o: In function `ngx_http_upsync_del_peers':
/opt/nginx/openresty-1.9.7.5/../nginx-upsync-module-master/src/ngx_http_upsync_module.c:994: undefined reference to `ngx_http_upstream_check_delete_dynamic_peer'

**Comment by xiaokai-wang** [comment]
If using check module, please use the module: [nginx_upstream_check_module](https://github.com/xiaokai-wang/nginx_upstream_check_module)

**Comment by maomaoaichirou** [comment]
Nginx 1.12 The error
ne=generic -DNDK_SET_VAR  -I src/core -I src/event -I src/event/modules -I src/os/unix -I src/http/modules/perl -I /nginx/lua-nginx-module-0.10.7//src/api -I /nginx/ngx_devel_kit-0.3.0/objs -I objs/addon/ndk -I /usr/include/libxml2 -I objs -I src/http -I src/http/modules -I src/http/v2 -I ../nginx-upsync-module/src -I /nginx/ngx_devel_kit-0.3.0/src -I /nginx/ngx_devel_kit-0.3.0/src -I /nginx/ngx_devel_kit-0.3.0/objs -I objs/addon/ndk -I src/mail -I src/stream \
	-o objs/addon/src/ngx_http_lua_headers.o \
	/nginx/lua-nginx-module-0.10.7//src/ngx_http_lua_headers.c
/nginx/lua-nginx-module-0.10.7//src/ngx_http_lua_headers.c: In function ‘ngx_http_lua_ngx_req_raw_header’:
/nginx/lua-nginx-module-0.10.7//src/ngx_http_lua_headers.c:151:15: error: incompatible types when assigning to type ‘struct ngx_buf_t *’ from type ‘ngx_chain_t’
             b = hc->busy[i];
               ^
/nginx/lua-nginx-module-0.10.7//src/ngx_http_lua_headers.c:227:15: error: incompatible types when assigning to type ‘struct ngx_buf_t *’ from type ‘ngx_chain_t’
             b = hc->busy[i];
               ^
make[1]: *** [objs/addon/src/ngx_http_lua_headers.o] Error 1
make[1]: Leaving directory `/nginx/nginx-1.12.0'
make: *** [build] Error 2

**Comment by gfrankliu** [comment]
Your error is due to lua-nginx-module-0.10.7 module, not nginx-upsync-module
Please download the latest lua-nginx-module
