### ISSUE TITLE
用户链接问题

### ISSUE THREAD

**Issue by insoz** [weibocom/nginx-upsync-module#130]
您好, 有个疑问, 麻烦解答一下, 谢谢!
如果当前有一个用户建立了链接, 假如说他正在上传一个文件, 在这时候注册中心中变更了upstream的后端server ip, 那这时候upsync_module从注册中心拉取到server 后, 是会立即动态更新upstream 的server 呢还是会等待用户请求完成才会动态重载?

**Comment by xiaokai-wang** [comment]
会更新server，新的请求打到新的server 上，但是老的server 连接不会关掉，直到老的请求处理完了，才会关掉老的连接；
