### ISSUE TITLE
upsync_recv: recv error with upsync_server

### ISSUE THREAD

**Issue by YunaiV** [weibocom/nginx-upsync-module#133]
Nginx版本：tengine-2.2.0（基于nginx1.8.1+）
nginx-upsync-module：https://github.com/weibocom/nginx-upsync-module/releases/tag/v1.0.0
Etcd：3.0.15

查看nginx的error.log时，一直如下错误：
`
2017/01/07 11:13:35 [error] 24469#0: recv() failed (104: Connection reset by peer)
2017/01/07 11:13:35 [error] 24469#0: upsync_recv: recv error with upsync_server: 127.0.0.1:2379
`

搜索了issue，感觉应该和 https://github.com/weibocom/nginx-upsync-module/issues/91 是相同问题。
查看了commit记录，这个问题应该是在COMMIT#89bf40fb60268062aaeac3780ad8d56f0834c400修复了。

现在碰到一个问题：修复的代码是基于1.9+做的，在tegine-2.2.0上无法编译安装。请问有什么办法解决么？

感谢查看问题解答。
@xiaokai-wang

**Comment by xiaokai-wang** [comment]
抱歉回复迟了些；

tengine 的主版本跟进确实比较慢；本模块的主要更新都基于1.9+ master 分支，部分更新没有同步到1.8+ 分支，可以把相应的1.9+ bug修复跟新同步到1.8+ 分支，应该是可以解决问题的；@YunaiV 可以尝试一下，有问题再跟进.

tengine 需要用分支1.8+，有什么问题随时交流！

**Comment by YunaiV** [comment]
@xiaokai-wang 谢谢。辛苦啦。我尝试下。因为没写过c++，可能合并的修复代码不太对。恩，先试试。

**Comment by xiaokai-wang** [comment]
ok.

**Comment by liuyue2656** [comment]
@xiaokai-wang 你好，我现在也是在用tengine2.2.0，etcd用的3.2.0，upsync用的也是1.8.x的分支，这块的代码也都改了，但是还有一个问题就是现在nginx的upstream跟etcd的同步会不及时，如果一段时间不更新etcd之后，再去更新etcd的话nginx会报错

```
2017/04/20 18:34:44 [error] 16150#0: upsync_process: upstream change peer weight error
2017/04/20 18:35:13 [error] 16150#0: upsync_process: upstream change peer weight error
2017/04/20 18:35:45 [error] 16150#0: upsync_process: upstream change peer weight error
2017/04/20 18:35:52 [error] 16150#0: upsync_process: upstream change peer weight error
```

而且nginx跟etcd里的数据不同步

etcd里的数据：
```
{
key: "/upstreams/test/127.0.0.1:82",
value: "{"weight":1, "max_fails":2, "fail_timeout":100, "down": 1}",
modifiedIndex: 88,
createdIndex: 88
}
```

nginx里的数据：

`server 127.0.0.1:82 weight=1 max_fails=9 fail_timeout=10s;`

**Comment by xiaokai-wang** [comment]
大概多长时间？现在模块不支持增删server 和 更新属性同步进行；你用的etcd 的版本是3.2.0？etcd 的github release 版本最新的是3.1.6？@liuyue2656
