### ISSUE TITLE
想实现对zookeeper的支持，但有些问题不明白

### ISSUE THREAD

**Issue by hoker38** [weibocom/nginx-upsync-module#136]
你好，我最近开始接触nginx模块的开发，想实现nginx-upsync-module对zookeeper的支持，在看您的代码时发现模块和consul/etcd通信的函数ngx_http_upsync_get_upstream调用了系统接口send()/recv()，这两个调用应该会阻塞nginx的工作进程，虽然有超时，但感觉也会对并发性能有较大的影响，但根据你们的测试，似乎没有什么影响，也许是我知识面窄不能理解其中的原因，望不吝解惑

**Comment by hoker38** [comment]
哦，我似乎明白了，ngx_http_upsync_get_upstream只发生在初始化阶段，之后就靠事件驱动了

**Comment by xiaokai-wang** [comment]
欢迎提交对zookeeper 支持的patch，代码风格请参照readme 链接，感谢！
