### ISSUE TITLE
关于upsync中支持server的resolve指令

### ISSUE THREAD

**Issue by saga1015** [weibocom/nginx-upsync-module#137]
大神，默认的话，nginx是不支持在server中用resolve指令的，如果通过打补丁或者模块的方式支持了server中的resolve指令，在使用curl增加server的时候，是否支持添加resolve指令呢？

**Comment by xiaokai-wang** [comment]
你是指这个模块？还是你的新的模块？

**Comment by saga1015** [comment]
大神，比如我编译进https://github.com/GUI/nginx-upstream-dynamic-servers 这个模块，那我通过curl向consul增加server的时候，是否支持带上resolve指令

**Comment by xiaokai-wang** [comment]
本模块暂时不支持这个指令；

上述所提模块提供了动态解析域名的功能，最终的目的是相同的；
