### ISSUE TITLE
请问支持新服务注册么？

### ISSUE THREAD

**Issue by fankeke** [weibocom/nginx-upsync-module#138]
很高兴看到不依赖第三方的nginx动态扩容：）

简单实践了下，发现upsync是基于已有的upstream做的动态扩/缩容方式，即需要配置文件里面原来就要配置upstream块。

1，不知道先有的upsync是否支持新的upstream块创建？如果没有，是否有计划支持呢？难度大么？

2，目前有dyups模块[1]是支持通过push的方式来动态创建upstream（更新upstream的），请问下当初是基于怎样的考量没有采用呢？

[1] https://github.com/yzprofile/ngx_http_dyups_module
谢谢：）

**Comment by xiaokai-wang** [comment]
这个可以给dyups 提一个patch，做一个兼容性支持，以便动态的创建upstream && 动态的扩容/缩容.
