### ISSUE TITLE
这种直接改peers的方法对chash等等负载均衡算法是不是不兼容？

### ISSUE THREAD

**Issue by cfsego** [weibocom/nginx-upsync-module#14]
我的理解是太深入nginx的实现了，所以兼容性不佳。
原来还有一个ngx_fair，也是不兼容的。
也不支持keepalive

**Comment by xiaokai-wang** [comment]
感谢你的关注！really much.

我看了nginx-1.9.9 的源码，里面支持了hash, ip_hash, least_conn等, 但是这些实现跟peers 本身的加减貌似没有关系，对负载均衡算法应该没有影响；

对于keepalive，连接池的问题，之前也想过，但它是无状态的，如果考虑到长连接性能的影响，最简单的可以通过预设一个值来解决，多一点、少一点对系统的开销应该有限？你觉得呢？

貌似现在所有涉及对upstream 或对 peer的操作的模块，好像都没有考虑keepalive 这个特性，你觉的呢？

这些都是我的个人的一些还不成熟的看法，有任何不对、不严谨的还请见谅、指正，希望能够保持沟通……，再次感谢！

**Comment by xiaokai-wang** [comment]
@cfsego , 前段时间添加了对least_conn 和 chash 的支持，希望有时间帮忙review 一下，非常感谢！
