### ISSUE TITLE
upstream name下节点出错

### ISSUE THREAD

**Issue by wsw79wsw** [weibocom/nginx-upsync-module#142]
1. 建立一个upstream
   curl -X PUT   127.0.0.1:8500/v1/kv/upstreams/upstream_a/1.1.1.1:8080
2. 再建立一个
   curl -X PUT   127.0.0.1:8500/v1/kv/upstreams/upstream_a_1/2.2.2.2:8080
3. 查看    upstream_a
    curl 127.0.0.1:8089/upstream_show?upstream_a
  返回的结果中upstream_a_1下的节点也写了进来
   Upstream name: upstream_a; Backend server count: 2
        server 1.1.1.1:8080 weight=1 max_fails=2 fail_timeout=10s;
        server 1.1.1.1:8080 weight=1 max_fails=2 fail_timeout=10s;

**Comment by xiaokai-wang** [comment]
哪一个版本 or 分支？

**Comment by wsw79wsw** [comment]
default-branch : master

**Comment by xiaokai-wang** [comment]
Fixed.

**Comment by gfrankliu** [comment]
@xiaokai-wang The fix seems to be broken. I emailed you my setup, can you see if you can reproduce?

**Comment by gfrankliu** [comment]
Can we revert this fix? It is not really a problem. It is how you configure the upsync.
If you only want upstream_a but not upstream_a_1, you need to configure upsync to stop at upstream_a/
e.g.:
`upsync 127.0.0.1:8500/v1/kv/upstreams/upstream_a/ `  
Pay attention to the trailing /
If you want all upstream_a* like upstream_a_1, you don't need to include the trailing /
`upsync 127.0.0.1:8500/v1/kv/upstreams/upstream_a `

**Comment by xiaokai-wang** [comment]
Is it necessary？ If so, has badly influence?

**Comment by gfrankliu** [comment]
原作者 @wsw79wsw 指出的情况不是bug。
他没有发出具体设置，但我推测他忘记了加斜杠
错的设置：`upsync 127.0.0.1:8500/v1/kv/upstreams/upstream_a`
对的设置：`upsync 127.0.0.1:8500/v1/kv/upstreams/upstream_a/`

@wsw79wsw 你能把你的upsync configuration 发出来吗？

**Comment by xiaokai-wang** [comment]
@gfrankliu 感谢你的持续关注，你的意见是正确、无可否认的！
现在的使用习惯是，很多人配置时都会忽略去在后面加 '/'，可能是首页readme 的误导！

退一步，有没有必要加一个校验？如果没有，只要在upstream 配置块内配置上consul 的 url，就会获取servers（如果consul not null），然后直接work，这样有没有风险点？
另一点，如果保持upstream name 和 配置的url 的最后一个字段一致，这样有什么危害？会限制功能的扩展使用嘛？

**Comment by gfrankliu** [comment]
可以在readme里指出两种使用情况。
有人可能需要包括test, test_a, test_b。我们不能关闭这个选项 :)

**Comment by gfrankliu** [comment]
如果我们不想给用户这个选项，我们可以简单地在code里强行加上／（如果用户没有／结束的话）。

**Comment by xiaokai-wang** [comment]
不建议强行加哈

**Comment by gfrankliu** [comment]
这也是我为什么建议rollback the fix。因为那就相当于强行加上了／。upsync 127.0.0.1:8500/v1/kv/upstreams/test 被截段，只算test。有人可能需要包括test, test_a, test_b 也不行了。
