### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by yangzieric** [weibocom/nginx-upsync-module#144]
版本：  nginx -1.8.1
nginx-upsync-module-1.0.0
ginx_upstream_check_module-master

报错：
        objs/addon/src/ngx_http_upsync_module.o \
        objs/addon/src/ngx_http_json.o \
        objs/addon/src/ngx_http_parser.o \
        objs/addon/nginx_upstream_check_module-master/ngx_http_upstream_check_module.o \
        objs/ngx_modules.o \
        -lpthread -lcrypt -lm -lpcre -lcrypto -lcrypto -lz
objs/addon/src/ngx_http_upsync_module.o: In function `ngx_http_upsync_add_peers':
/home/yangzi/nginx-upsync-module-1.0.0/src/ngx_http_upsync_module.c:821: undefined reference to `ngx_http_upstream_check_add_dynamic_peer'
objs/addon/src/ngx_http_upsync_module.o: In function `ngx_http_upsync_del_peers':
/home/yangzi/nginx-upsync-module-1.0.0/src/ngx_http_upsync_module.c:975: undefined reference to `ngx_http_upstream_check_delete_dynamic_peer'
collect2: ld returned 1 exit status
make[1]: *** [objs/nginx] Error 1
make[1]: Leaving directory `/home/yangzi/nginx-1.8.0'
make: *** [build] Error 2

在代码里我没有找到 

ngx_http_upsync_add_peers  函数的实现 方法。

另外：
nginx-upsync-module    不能支持  tengine 编译！

不知作者 有 编译成功么？我看  案例 是 用的 NGINX 1.8.0  我试过了 报错一样的。

**Comment by xiaokai-wang** [comment]
nginx-1.8.1 + 1.8.X 分支 ＋ upstream_check_module, 需要把补丁先打上；

tengine2.2.0 ＋ 1.8.X 分支可以使用，需要把upsync.h 文件的两个函数声明：
‘’‘
ngx_http_upstream_check_add_dynamic_peer
ngx_http_upstream_check_delete_dynamic_peer
’‘’
去掉

**Comment by yangzieric** [comment]
环境：

nginx-upsync-module/src/ngx_http_upsync_module.h
tengine2.2.0 ＋ 1.8.X 分支

把 nginx-upsync-module/src/ngx_http_upsync_module.h
//#if (NGX_HTTP_UPSTREAM_CHECK)

//extern ngx_uint_t ngx_http_upstream_check_add_dynamic_peer(ngx_pool_t *pool,
//    ngx_http_upstream_srv_conf_t *uscf, ngx_addr_t *peer_addr);
//extern void ngx_http_upstream_check_delete_dynamic_peer(ngx_str_t *name,
//    ngx_addr_t *peer_addr);

//#endif

编译还是报错了：

make[1]: Entering directory `/home/yangzi/tengine-2.2.0'
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g   -I src/core -I src/event -I src/event/modules -I src/os/unix -I src/proc -I /home/yangzi/nginx-upsync-module/src -I objs -I src/http -I src/http/modules -I src/mail \
                -o objs/addon/src/ngx_http_upsync_module.o \
                /home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c
In file included from /home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c:11:
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.h: In function ‘ngx_http_upsync_chash_init’:
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.h:151: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.h: In function ‘ngx_http_upsync_del_chash_peer’:
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.h:284: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_add_peers’:
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c:833: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘conns’
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c:835: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c:836: error: incompatible types when assigning to type ‘struct ngx_http_upstream_rr_peer_t[1]’ from type ‘struct ngx_http_upstream_rr_peer_t *’
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_add_filter’:
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c:923: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
cc1: warnings being treated as errors
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c:923: error: left-hand operand of comma expression has no effect
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c:923: error: value computed is not used
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_del_peers’:
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c:985: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c:1003: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c:1009: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c:1010: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c:1013: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c:1013: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c:1025: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_del_filter’:
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c:1070: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_update_peers’:
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c:1120: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_init_peers’:
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c:2166: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘conns’
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c:2171: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c:2172: error: incompatible types when assigning to type ‘struct ngx_http_upstream_rr_peer_t[1]’ from type ‘struct ngx_http_upstream_rr_peer_t *’
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c:2175: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_dump_server’:
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c:2856: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_del_delay_delete’:
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c:3123: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_show_upstream’:
/home/yangzi/nginx-upsync-module/src/ngx_http_upsync_module.c:3665: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
make[1]: *** [objs/addon/src/ngx_http_upsync_module.o] Error 1
make[1]: Leaving directory `/home/yangzi/tengine-2.2.0'
make: *** [build] Error 2

**Comment by xiaokai-wang** [comment]
请确认用的是1.8.x 分支；从提示错误来看，貌似不是；

你的 ./configure 命令是？
