### ISSUE TITLE
cache manager process 29855 exited on signal 11 (core dumped)

### ISSUE THREAD

**Issue by xiaosazixian** [weibocom/nginx-upsync-module#147]
2017/03/23 14:28:17 [alert] 29781#0: cache manager process 29844 exited on signal 11 (core dumped)
2017/03/23 14:28:17 [alert] 29781#0: cache manager process 29847 exited on signal 11 (core dumped)
2017/03/23 14:28:17 [alert] 29781#0: cache manager process 29849 exited on signal 11 (core dumped)
2017/03/23 14:28:17 [alert] 29781#0: cache manager process 29851 exited on signal 11 (core dumped)
2017/03/23 14:28:17 [alert] 29781#0: cache manager process 29853 exited on signal 11 (core dumped)
2017/03/23 14:28:17 [alert] 29781#0: cache manager process 29855 exited on signal 11 (core dumped)
2017/03/23 14:28:17 [alert] 29781#0: worker process 29846 exited on signal 11 (core dumped)
一大推这种错误，不知道是真没情况额。

**Comment by xiaokai-wang** [comment]
用了这个模块之后产生的？还是什么？

**Comment by yuzunzhi** [comment]
我也遇到这个问题，nginx-1.10.3，upsync模块是1.0.0的，使用upsync模块后会有这个报错，系统日志内会有  kernel: nginx[101875]: segfault at 0 ip 0000000000488245 sp 00007ffd615bc500 error 6 in nginx[400000+b4000]   报错。注释掉upsync的相关配置后一切正常。
然后我使用tengine-2.2.0（nginx-1.8.1）编译加载upsync模块是正常的，就是backend-server的backup参数不生效，是现在还未支持吗？

**Comment by xiaokai-wang** [comment]
backup 参数暂不支持；
release 版本只兼容nginx-1.9.0 版本一下的

**Comment by xiaosazixian** [comment]
确实是版本问题
