### ISSUE TITLE
upsync不会删除已经在consul里删除的upstream键值对所生成的.conf

### ISSUE THREAD

**Issue by Colstuwjx** [weibocom/nginx-upsync-module#149]
RT，经过实验，当Consul里原本有的upstream目录被完全删掉，比如Marathon APP整个被suspend，就会出现nginx的upstreams目录下仍然保存之前版本的conf文件。

有什么好办法可以解决这个问题吗？upstreams整个目录应该是upsync所维护的，如果有冗余文件，upsync是否也应该删除？

**Comment by xiaokai-wang** [comment]
不支持删除upstream；

**Comment by Colstuwjx** [comment]
了解，跟团队同事沟通下来也是这样，应该是一个合理的设计，由于应用已经suspend了，自然也不会有上层流量路由到该Upstream。感谢回复。

**Comment by gfrankliu** [comment]
我们在讨论用fake server
https://github.com/weibocom/nginx-upsync-module/pull/148
这样虽然upstream没有删除，至少nginx会给客户端一个错误。
