### ISSUE TITLE
有没有qq群或者论坛

### ISSUE THREAD

**Issue by mysterytree** [weibocom/nginx-upsync-module#15]
加个讨论下

**Comment by xiaokai-wang** [comment]
讨论的主题？@mysterytree

**Comment by mysterytree** [comment]
@xiaokai-wang 就是nginx-upsync-module的发烧友qq群   这样大家遇到问题一起讨论下  
说不定还能提个pull request啥的哈哈

**Comment by mysterytree** [comment]
@xiaokai-wang  
插件好像是在轮询consul的kv   好像还是伪实时
现在容器rolling update的时候  非常希望做到每台容器的start／stop event 能够直接触发更新nginx的列表和reload    不知道能不能实现

**Comment by xiaokai-wang** [comment]
@mysterytree 欢迎提pr 哈，现在还暂不支持etcd，架子已搭好，欢迎大家补充；

实时是相对的，consul 有一个timewait 机制，模块每次去拉取upstream 列表时，都会携带一个版本号，consul 发现这个版本号与自己的版本号一致，便会hang 住这个连接，不变的情况下会持续五分钟，这五分钟内任何的加减、修改操作，都会触发这个连接马上把更新后的内容返回给模块，模块再更新列表；另一个是每次返回后，何时再去拉，这个取决于你的配置 upsync_interval，我们这里的线上配置环境是500ms，若要实时性更好，可以配置的更短一点，比如 50ms；

基于上面两点，基本可以做到实时，实时的最大延迟取决于你配置的 upsync_interval，多谢.

**Comment by xiaokai-wang** [comment]
任何的都是有折中的，这个方案是我已知的实时性最优的，暂时

consul-template 它也是有一定的延时性的，而且reload 还会对nginx 造成比较大的影响；

欢迎补充！

**Comment by mysterytree** [comment]
容器做update的时候两个步骤：
一个是kill旧的容器
一个是new新的容器

因为业务需求，

需要保证旧容器在kill之前就从upstream中去掉
新容器在create之后在upstream中添加

看你们的分享
http://mp.weixin.qq.com/s?__biz=MzAwMDU1MTE1OQ==&mid=403475196&idx=1&sn=bf98b356a50226f26d9d5791ecb03af8&scene=0#wechat_redirect

不知道你们是否有业务场景和相关经验

**Comment by mysterytree** [comment]
@xiaokai-wang 
其实我有一大堆话想说但是不造如何描述
看你们swarm＋register＋nginx－upsync真的是绝配
但是无奈 swarm＋register没有一个比较成熟的rolling－update方案
开发成本对我们还是略高
我们采用marathon 但是又碰到loadbalance的坑坑过不去
遥望45度 脸上有热翔划过

**Comment by xiaokai-wang** [comment]
具体的业务应用与模块本身无关，取决于你的使用策略；

据我所知，除了上述组件，公司内还自己开发了组件；

欢迎多多讨论模块相关的问题.

**Comment by mysterytree** [comment]
@xiaokai-wang 好的感谢分享

**Comment by luxuan** [comment]
@mysterytree 
1. 根据容器启停状态将其IP实时注册到consul中，是否尝试过https://github.com/gliderlabs/registrator？
2. 你们面临的问题是不是“docker化场景下如何优雅的解决服务发现问题”，个人理解swarm、marathon是做集群化管理的，即使它有好的loadbalance方案也不至于需要用的负载均衡策略而引入它的复杂度，除非有集群需求。
3. 关于公司内部的使用方式，@xiaokai-wang 在上面有提到，由于公司原来就有一整套的上线系统，Nginx路由变更只是它的一个子模块，改用nginx-upsync-module后，实际上只需要向consul发一个http请求即可完成变更。
