### ISSUE TITLE
nginx-1.11.12编译不过

### ISSUE THREAD

**Issue by shenzhixun** [weibocom/nginx-upsync-module#152]
objs/addon/src/ngx_http_upsync_module.o：在函数‘ngx_http_upsync_add_peers’中：
/software/nginx-upsync-module/src/ngx_http_upsync_module.c:866：对‘ngx_http_upstream_check_add_dynamic_peer’未定义的引用
objs/addon/src/ngx_http_upsync_module.o：在函数‘ngx_http_upsync_del_peers’中：
/software/nginx-upsync-module/src/ngx_http_upsync_module.c:1008：对‘ngx_http_upstream_check_delete_dynamic_peer’未定义的引用
collect2: 错误：ld 返回 1
make[1]: *** [objs/nginx] 错误 1
make[1]: 离开目录“/software/nginx-1.11.12”

**Comment by shenzhixun** [comment]
./configure --add-module=/software/nginx_upstream_check_module --add-module=/software/nginx-upsync-module --user=webwd --group=weidong --prefix=/XXX/nginx --with-http_stub_status_module --with-http_ssl_module --with-http_gzip_static_module --with-pcre --with-http_realip_module --with-http_sub_module --without-select_module --with-http_gzip_static_module --with-http_degradation_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module

编译命令如上：并且已经打了patch -p0 < /opt/software/nginx_upstream_check_module-master/check_1.11.5+.patch

**Comment by xiaokai-wang** [comment]
使用的是此分支 [upstream_check_module](https://github.com/xiaokai-wang/nginx_upstream_check_module) 代码吗？

**Comment by shenzhixun** [comment]
是的。

**Comment by xiaokai-wang** [comment]
电脑版本里木有nginx-1.11.12，用的是nginx-1.11.13，打上补丁之后，没有报任何错误；

从你的错误提示里，应该是没有定义词函数，upstream_check 原git 下是没有定义此函数的，所以我怀疑你并没有引用我分支的健康监测模块 @shenzhixun

**Comment by shenzhixun** [comment]
我改个nginx-1.11.13试试。补丁肯定是执行了的。patch -p0 < /opt/software/nginx_upstream_check_module-master/check_1.11.5+.patch这行的是这个补丁版本。

**Comment by coco535** [comment]
-L/root/mysoft/openresty-1.11.2.4/build/luajit-root/usr/local/openresty/luajit/lib -Wl,-rpath,/usr/local/openresty/luajit/lib -Wl,-E -ldl -lpthread -lpthread -lcrypt -L/root/mysoft/openresty-1.11.2.4/build/luajit-root/usr/local/openresty/luajit/lib -lluajit-5.1 -lm -ldl -lm /root/mysoft/openresty-1.11.2.4/../pcre-8.41/.libs/libpcre.a /root/mysoft/openresty-1.11.2.4/../openssl-1.0.2l/.openssl/lib/libssl.a /root/mysoft/openresty-1.11.2.4/../openssl-1.0.2l/.openssl/lib/libcrypto.a -ldl -lz -lGeoIP \
	-Wl,-E
objs/addon/src/ngx_http_upsync_module.o: In function `ngx_http_upsync_add_peers':
/root/mysoft/openresty-1.11.2.4/../nginx-upsync-module-2.0.0/src/ngx_http_upsync_module.c:866: undefined reference to `ngx_http_upstream_check_add_dynamic_peer'
objs/addon/src/ngx_http_upsync_module.o: In function `ngx_http_upsync_del_peers':
/root/mysoft/openresty-1.11.2.4/../nginx-upsync-module-2.0.0/src/ngx_http_upsync_module.c:1008: undefined reference to `ngx_http_upstream_check_delete_dynamic_peer'
collect2: ld 返回 1
gmake[2]: *** [objs/nginx] 错误 1
gmake[2]: Leaving directory `/root/mysoft/openresty-1.11.2.4/build/nginx-1.11.2'
gmake[1]: *** [build] 错误 2
gmake[1]: Leaving directory `/root/mysoft/openresty-1.11.2.4/build/nginx-1.11.2'
gmake: *** [all] 错误 2

**Comment by xiaokai-wang** [comment]
@coco535 使用健康监测模块 [nginx_upstream_check_module](https://github.com/xiaokai-wang/nginx_upstream_check_module)
