### ISSUE TITLE
如何配置upstream的keepalive

### ISSUE THREAD

**Issue by yfgu** [weibocom/nginx-upsync-module#154]
原先的upstream配置如下：
upstream  test   {
    server    10.20.22.85:8021    weight=10 fail_timeout=10 max_fails=3;
    keepalive    256;
}

上面server的配置知道了，怎么配置下面一行“keepalive    256;”？

**Comment by xiaokai-wang** [comment]
nginx 原生配置保持不变

**Comment by yfgu** [comment]
谢谢，不是很明白upsync_dump_path的配置，我先跑着看一下
