### ISSUE TITLE
生成upsync_dump_path配置的文件以后，重启nginx报错

### ISSUE THREAD

**Issue by yfgu** [weibocom/nginx-upsync-module#155]
生成upsync_dump_path配置的文件以后，重启nginx报错，具体步骤如下，请问这个是怎么回事？谢谢！

1. 在nginx.conf里面include upstream.conf,在upstream.conf里面配置：
upstream  stg-1 {
    server 127.0.0.1:11112;
    upsync 10.20.22.86:2379/v2/keys/upstreams/stg-1 upsync_timeout=6m upsync_interval=500ms upsync_type=etcd strong_dependency=off;
    upsync_dump_path /wls/apache/appsystems/ng_test/conf/abconf/servers_stg-1.conf;
}
upstream stable {
    server 127.0.0.1:11111;
    upsync 10.20.22.86:2379/v2/keys/upstreams/stable upsync_timeout=6m upsync_interval=500ms upsync_type=etcd strong_dependency=off;
    upsync_dump_path /wls/apache/appsystems/ng_test/conf/abconf/servers_stable.conf;
}

2. 在etcd里面添加upstream的server信息
curl -X PUT -d value="{\"weight\":10, \"fail_timeout\":10, \"max_fails\":3}" http://10.20.22.86:2379/v2/keys/upstreams/stable/10.20.22.85:8010

curl -X PUT -d value="{\"weight\":10, \"fail_timeout\":10, \"max_fails\":3}" http://10.20.22.86:2379/v2/keys/upstreams/stg-1/10.20.22.85:8020

3. 在/wls/apache/appsystems/ng_test/abconf/下的servers_stg-1.conf和servers_stable.conf的内容分别如下：
server 10.20.22.85:8020 weight=10 max_fails=3 fail_timeout=10s;
server 10.20.22.85:8010 weight=10 max_fails=3 fail_timeout=10s;

4. 重启nginx,报错
nginx: [emerg] directive "server" has no opening "{" in /wls/apache/appsystems/ng_test/conf/abconf/servers_stable.conf:1

**Comment by xiaokai-wang** [comment]
从来没遇到过这个问题，可有解决？可否把整个dump 独立完整的贴出来

**Comment by yfgu** [comment]
1. servers_stg-1.conf 的内容如下:
server 10.20.22.85:8020 weight=10 max_fails=3 fail_timeout=10s;
2.  servers_stable.conf 的内容如下：
server 10.20.22.85:8010 weight=10 max_fails=3 fail_timeout=10s;

就这么多了

**Comment by yfgu** [comment]
而且只有在etcd下添加server才会在dump文件里面增加行数，修改etcd的server参数，dump文件没有变化，这个正常么？有了dump文件还是启动不起来。

**Comment by xiaokai-wang** [comment]
不正常

**Comment by yfgu** [comment]
应该是怎样的？能够给个已经生成的文件看看么？
