### ISSUE TITLE
读取nginx的upstream和server时,server还是初始配置

### ISSUE THREAD

**Issue by yfgu** [weibocom/nginx-upsync-module#156]
1. upstream是以下配置
upstream stg-1 {
    server 127.0.0.1:11112;
    upsync 10.20.22.86:2379/v2/keys/upstreams/stg-1 upsync_timeout=6m upsync_interval=500ms upsync_type=etcd strong_dependency=off;
    upsync_dump_path /wls/apache/appsystems/ng_testconf/abconf/servers_stg-1.conf;
}
upstream stable {
    server 127.0.0.1:11111;
    upsync 10.20.22.86:2379/v2/keys/upstreams/stable upsync_timeout=6m upsync_interval=500ms upsync_type=etcd strong_dependency=off;
    upsync_dump_path /wls/apache/appsystems/ng_test/conf/abconf/servers_stable.conf;
}

2. 使用“lua-upstream-nginx-module-0.06”模块读取nginx的upstream和server信息，结果如下
{
    "desc": "success ",
    "code": 200,
    "data": [
        {
            "servers": [
                {
                    "addr": "127.0.0.1:11112",
                    "weight": 1,
                    "fail_timeout": 10,
                    "name": "127.0.0.1:11112",
                    "max_fails": 1
                }
            ],
            "upstream": "stg-1"
        },
        {
            "servers": [
                {
                    "addr": "127.0.0.1:11111",
                    "weight": 1,
                    "fail_timeout": 10,
                    "name": "127.0.0.1:11111",
                    "max_fails": 1
                }
            ],
            "upstream": "stable"
        }
    ]
}

3. 在etcd中增加upstream的server信息
curl -X PUT -d value="{\"weight\":10, \"fail_timeout\":10, \"max_fails\":3}" http://10.20.22.86:2379/v2/keys/upstreams/stable/10.20.22.85:8010

curl -X PUT -d value="{\"weight\":10, \"fail_timeout\":10, \"max_fails\":3}" http://10.20.22.86:2379/v2/keys/upstreams/stg-1/10.20.22.85:8020

4. 使用“lua-upstream-nginx-module-0.06”模块读取nginx的upstream和server信息，结果如下,和2一样
{
    "desc": "success ",
    "code": 200,
    "data": [
        {
            "servers": [
                {
                    "addr": "127.0.0.1:11112",
                    "weight": 1,
                    "fail_timeout": 10,
                    "name": "127.0.0.1:11112",
                    "max_fails": 1
                }
            ],
            "upstream": "stg-1"
        },
        {
            "servers": [
                {
                    "addr": "127.0.0.1:11111",
                    "weight": 1,
                    "fail_timeout": 10,
                    "name": "127.0.0.1:11111",
                    "max_fails": 1
                }
            ],
            "upstream": "stable"
        }
    ]
}

**Comment by xiaokai-wang** [comment]
nginx 后端sever 大致可以分为三层：upstream, servers, server-list; 此模块只会替换server-list, 并不会更新中间层servers( server 配置项 支持域名）；所以你用此模块读取的是servers 层，并不会变；
可以参考readme 的upstream_show 配置项，读取每个upstream 下的server 列表；

**Comment by yfgu** [comment]
看了lua-upstream-nginx-module-0.06的ngx_http_lua_upstream_module.c， get_servers取的是upstream的servers(server = us->servers->elts;)
项目中的配置：http里面配置server/upstream，在upstream里面配置server list，因此认为该模块读的是upstream里面的server list。
但是etcd变化了以后，没有看到get_servers的返回发生变化是为什么呢？
