### ISSUE TITLE
check module failing at high cpu

### ISSUE THREAD

**Issue by gfrankliu** [weibocom/nginx-upsync-module#157]
When nginx server is busy and nginx workers run 100% cpu, it seems the "nginx_upstream_check_module" will mark all upstream servers as "down". "check_status" takes a bit longer to respond and all the upstream servers are showing down. Is this because the "check" thread didn't get a chance to run, or take a long time to run? How to make sure check thread get a higher priority?

**Comment by xiaokai-wang** [comment]
The question is about upstream_check_module, not upsync_module. 

Ok, when cpu is high to 100%, other requests can work normally? No independently thread or progress do check things, all checks is used timer, not attached to the fixed progress.

**Comment by gfrankliu** [comment]
I didn't see an "issues" section in "nginx_upstream_check_module" repo so I created here.
Looks like now you enabled "issues" there so I am moving this ticket to https://github.com/xiaokai-wang/nginx_upstream_check_module/issues/1
