### ISSUE TITLE
upstream_show有没有lua的接口

### ISSUE THREAD

**Issue by yfgu** [weibocom/nginx-upsync-module#158]
项目中的管理接口的统一入口是location /admin{....}。在admin中用的lua文件最前面做了权限控制，然后再根据url做不同的操作。 
请问upstream_show有没有lua的接口，有没有例子，这里需要把所有的upstream返回给前端。
谢谢！

**Comment by xiaokai-wang** [comment]
目前木有lua 接口

**Comment by milesdong** [comment]
@xiaokai-wang seems this module is not compatiable with lua-upstream-nginx-module for those reasons:
1. umcf->servers not modified, this lead ngx.upsteam.get_servers gets the static config
2. ngx_http_upstream_rr_peer_t.peers are organized as a linked list, but it also should be array
