### ISSUE TITLE
能动态修改server_name吗

### ISSUE THREAD

**Issue by lmdkfs** [weibocom/nginx-upsync-module#159]
我看nginx-upsync-module 这个模块只能动态修改upstream, 这样话, 我们的docker集群就是基于location 区分应用, 那么能否同时支持基于域名区分应用, 动态添加server_name

**Comment by xiaokai-wang** [comment]
基于location 就可以了吧，为什么要基于upstream 块内的 server 呢？

**Comment by lmdkfs** [comment]
非常感谢您回答我的问题, 是我描述问题没描述清楚, 我说的不是upstream下的server, 是基于server 块 , 基于location可以, 但是这样只能基于location区分应用, 我们想基于server块下的server_name 域名区分应用, 我们用的是marathon + mesos  做的docker集群, 我们想基于域名区分应用, 目前的方式是动态生成nginx配置文件, 但是每次都需要reload 影响性能, 所以我们想动态生成server块,不需要reload,  不知道怎么实现, 咱们的这个模块能支持最好了.

**Comment by xiaokai-wang** [comment]
server 块下的可配置项太多，情况好复杂，难以支持啊

**Comment by lmdkfs** [comment]
你们是server块的域名都是手动添加的吗, 还有通过脚本 生成配置文件然后再reload, upstream 下面的主机是通过你写的这个模块实现的动态变更. 你们是这部分你们是怎么做的呢,有没有什么好的解决方案, 谢谢大神

**Comment by xiaokai-wang** [comment]
server 块的域名会频繁变更吗？这个模块是基于location 的弹性扩容所容，或者location 下的server 频繁变更，这种情况下比较适用。

**Comment by lmdkfs** [comment]
域名一般不会变更但是会增加, 功能类似于k8s的ingress, 但是ingress 实现的方式就是 模版生成配置文件然后reload

**Comment by NsLib** [comment]
server的生成，一般可以用模板+agent自动生成/删除，修改操作配合一个web管理的页面去做；
因为server块中很多配置是不能运行中动态修改的，需要reload才行。

**Comment by wangsp102** [comment]
> 域名一般不会变更但是会增加, 功能类似于k8s的ingress, 但是ingress 实现的方式就是 模版生成配置文件然后reload

您好  我们现在也用到nginx动态增加server_name的情景，想请教下你们的这个问题最终是怎么解决的？谢谢！
