### ISSUE TITLE
能支持consul的service吗

### ISSUE THREAD

**Issue by mysterytree** [weibocom/nginx-upsync-module#16]
看了下 好像是轮询consul的kv  
docker registrator 默认是注册到consul的service里边

**Comment by mysterytree** [comment]
手动转化很麻烦

**Comment by mysterytree** [comment]
@xiaokai-wang

**Comment by xiaokai-wang** [comment]
抱歉，暂不支持

**Comment by luxuan** [comment]
关于对service的支持，我们在最开始设计时也是有过评估的，最后采用kv的原因有两个：
1. consul service机制相对复杂，担心过于复杂会有什么坑在里头；
2. 当时在选择协调服务时，也考虑过对ectd的支持，但由于公司内部已经有现成的consul服务，所有优先选择consul，但如果要支持etcd的话（支持kv），那么采用kv存储后续扩容更好；
3. 与此同时，我们也去扫了下swarm的源码，发现它用consul、etcd存储容器IP也统一使用kv结构，而并非因为consul已经有service的支持而对它单独实现（理由估计与第2点相似），有了现有系统的实践证明kv是可行的、相对来说也是更可靠的，我们没有理由再选择service结构去实现，这也是后来我们采用kv存储的决定因素。

**Comment by mysterytree** [comment]
@xiaokai-wang  忘了关 不好意思～
