### ISSUE TITLE
ngx_http_upstream_round_robin.c 编译不过

### ISSUE THREAD

**Issue by lihuibo128** [weibocom/nginx-upsync-module#160]
使用 Tengine/2.2.0 (nginx/1.8.1) 版本
cd /data/tengine-2.2.0 
patch -p1 < /data/nginx_upstream_check_module/check_1.7.5+.patch
将补丁patch打上，替换了相应的文件
./configure --with-http_upstream_check_module  --add-module=/data/code/nginx-upsync-module
make 
出错：
src/http/ngx_http_upstream_round_robin.c: 在函数‘ngx_http_upstream_init_round_robin’中:
src/http/ngx_http_upstream_round_robin.c:100: 错误：‘ngx_http_upstream_rr_peer_t’没有名为‘check_index’的成员
src/http/ngx_http_upstream_round_robin.c:104: 错误：‘ngx_http_upstream_rr_peer_t’没有名为‘check_index’的成员
src/http/ngx_http_upstream_round_robin.c:169: 错误：‘ngx_http_upstream_rr_peer_t’没有名为‘check_index’的成员
src/http/ngx_http_upstream_round_robin.c:173: 错误：‘ngx_http_upstream_rr_peer_t’没有名为‘check_index’的成员
src/http/ngx_http_upstream_round_robin.c:240: 错误：‘ngx_http_upstream_rr_peer_t’没有名为‘check_index’的成员
src/http/ngx_http_upstream_round_robin.c: 在函数‘ngx_http_upstream_create_round_robin_peer’中:
src/http/ngx_http_upstream_round_robin.c:355: 错误：‘ngx_http_upstream_rr_peer_t’没有名为‘check_index’的成员
src/http/ngx_http_upstream_round_robin.c:400: 错误：‘ngx_http_upstream_rr_peer_t’没有名为‘check_index’的成员
make[1]: *** [objs/src/http/ngx_http_upstream_round_robin.o] 错误 1
make[1]: Leaving directory `/data/tengine-2.2.0'
make: *** [build] 错误 2
-------------------------------------------------------
因为nginx的版本或者patch版本问题？

**Comment by xiaokai-wang** [comment]
看着像是patch 打得有问题，用的是nginx-upsync-1.8.x 分支，对吧？

**Comment by lihuibo128** [comment]
patch 打的没问题，后来从#133 看到应该是nginx-upsync-xx版本对应不上，因为tengine-2.2.0使用的是nginx-1.8.1，所以需要nginx-upsync-1.8.x 这个版本

**Comment by xiaokai-wang** [comment]
OK

**Comment by lihuibo128** [comment]
使用：
Tengine/2.2.0 (nginx/1.8.1)  
nginx-upsync-1.8.x （通过git clone拉取并切换到1.8.x分支编译有问题，但通过直接下载xx-1.8.x.zip确可以）
consul_0.8.4_linux_amd64.zip
./configure --with-http_upstream_check_module --add-module=/data/code/nginx-upsync-module （注意，本身tengine集成了upstream_check_module，因此不需要--add-module=upstream_check_module，以及也不需要打patch包，打patch包后会报错）
成功搭建并运行了demo，目前demo运行没有错误

但根据#133使用tengine-2.2.0中碰到的问题，而我在demo中并没有碰到：
查看nginx的error.log时，一直如下错误：
2017/01/07 11:13:35 [error] 24469#0: recv() failed (104: Connection reset by peer) 2017/01/07 11:13:35 [error] 24469#0: upsync_recv: recv error with upsync_server: 127.0.0.1:2379
根据提问者的说明：
    修复的代码是基于1.9+做的，在tegine-2.2.0上无法编译安装
根据你的回答：
    本模块的主要更新都基于1.9+ master 分支，部分更新没有同步到1.8+ 分支，可以把相应的1.9+ bug修复跟新同步到1.8+ 分支，应该是可以解决问题的
我的问题是：
    1、目前基于1.8+分支对于运行时出现的问题是否有在分支上合并修复？ 还是需要自己再手动合并1.9+中修复的代码？
    2、是不是推荐使用1.9+版本的nginx，因为修复的代码是基于1.9+做的(因为公司一直使用的是tengine)？

**Comment by xiaokai-wang** [comment]
1. 并不是会把模块1.9+ 分支的patch 都merge 到 1.8+ 分支上，因为1.9+ 分支遇到的问题 1.8+ 分支并不一定会有，如果有需要会merge 进1.9+分支；
2. 嗯，有一些公司使用的是tengine ，但是为什么要使用tengine？现在官方更新迭代的很快，大部分tengine 有的feature 官方也有，所以还是建议使用官方的nginx，relase版本越高一般越稳定；另 tengine 由于历史原因吧，现在更新好慢，主分支稳定版还是基于nginx-1.8.1, 很陈旧的版本了。
