### ISSUE TITLE
consul 无法获取到设置的weight等参数？

### ISSUE THREAD

**Issue by lihuibo128** [weibocom/nginx-upsync-module#161]
curl http://10.1.48.196:8500/v1/kv/upstreams/test?recurse -d '{"weight":1, "max_fails":2, "fail_timeout":10}'
可以获取到test下的设置的server列表，
[{
        "LockIndex": 0,
        "Key": "upstreams/test/10.1.48.195:7777",
        "Flags": 0,
        "Value": "eyJmYWlsX3RpbWVvdXQiOiAxMCwgIm1heF9mYWlscyI6IDIsICJ3ZWlnaHQiOiAxfQ==",
        "CreateIndex": 16752,
        "ModifyIndex": 22590
 }]
但通过这个方法执行，无法获取到weight、max_fails等参数，是否有方法获取到对应的值？
当然在安装upsync机器上 upsync_dump_path /tmp/servers_test.conf; 中有这个配置，这样相对麻烦，而且也不一定准确，因为有可能没有同步过去，并且upstream配置的server会改变。

还是希望能够在consul中获取到，不知道有没有方法？

**Comment by xiaokai-wang** [comment]
consul 官方有个界面展示，但是应该不是你所需要的；

value 对应的字段是加密后的属性，不清楚有没有这样的工具；

**Comment by lihuibo128** [comment]
多谢指导，就是value这个字段，通过base64编码的（使用base64编码是为了允许非UTF-8的字符）
