### ISSUE TITLE
consistent_hash $cookie_session 不支持

### ISSUE THREAD

**Issue by lihuibo128** [weibocom/nginx-upsync-module#163]
使用最新版本的tengine(Nginx 1.8.x) 
当在upstream中加上 consistent_hash $cookie_session; 是则不能够使用，配置如下：
upstream huidu_juzilicaiServer {
    consistent_hash $cookie_session;
    server 127.0.0.1:11111;
    upsync 10.1.48.196:8500/v1/kv/upstreams/server upsync_timeout=6m upsync_interval=1000ms   upsync_type=consul strong_dependency=off;
    upsync_dump_path /data/upstream_huidu_servers.conf;
}
请求日志中，upstream分发到了 127.0.0.1:11111，去掉则可以按设置规则分发
是否nginx-upsync-module 不支持 cookie_session ？？

**Comment by xiaokai-wang** [comment]
Refer : https://github.com/weibocom/nginx-upsync-module#upsync_lb

**Comment by lihuibo128** [comment]
ok，多谢

**Comment by sunsky-cn** [comment]
具体怎么用能给个例子吗？谢谢

**Comment by sunsky-cn** [comment]
consistent_hash $cookie_session;
upsync_lb hash_ketama；
这样？？完全没用啊会502
