### ISSUE TITLE
tengine + upsync的场景,nginx reload后大概75秒会出现cpu耗尽的情况

### ISSUE THREAD

**Issue by snake1361222** [weibocom/nginx-upsync-module#164]
环境:
tengine版本:  Tengine/2.2.0 (nginx/1.8.1)
upsync版本:   branch是 nginx-upsync-1.8.x

当时用perf top发现是这两个函数的占用比较高[ngx_http_upsync_add_delay_delete](https://github.com/weibocom/nginx-upsync-module/blob/nginx-upsync-1.8.x/src/ngx_http_upsync_module.c#L3150)

![perf_top](https://user-images.githubusercontent.com/4124307/28423565-f0677cdc-6d9d-11e7-9e9c-707dff21d28d.png)

**Comment by xiaokai-wang** [comment]
赞！reload 时会获取upstream 并进行替换 ，某一个时刻此操作比较集中；你的upstream 列表很多？但也不足以把cpu 占满；当时处于请求量很大？

这部分之后可以考虑优化一下，谢谢！

**Comment by Shliesce** [comment]
PS：跟snake1361222是同事。
1、我们测试过，把这台nginx的流程全部下掉后reload，75s后nginx cpu还会100%（没有任何HTTP请求的情况下）；upstream数量 在200左右。
2、75S的时间是固定的么？
3、如果在75S时进行替换，那reload时只是从consul获取upstream server列表，nginx用的还是老的配置？
4、如果在75S内upstream server发生了变更会如何？一起在75S时更新？
5、目前这个问题对我们线上服务影响很大，每次reload必影响服务，大佬能否给个联系方式，我们和snake1361222一起私聊下？

**Comment by xiaokai-wang** [comment]
@Shliesce , xiaokai.wang@live.com 把你微信发我邮箱，加一下微信

**Comment by xiaokai-wang** [comment]
@snake1361222 @Shliesce 发一下微信，加一下

**Comment by Shliesce** [comment]
当天就发到你邮箱了。难道被扔垃圾箱了？我微信Shliesce，大佬你加下
