### ISSUE TITLE
怎么支持etcd集群？

### ISSUE THREAD

**Issue by mlkt** [weibocom/nginx-upsync-module#166]
配置中把集群中每台机器的IP都写进去就可以了吗？
还是说只能写一个地址，只能通过域名解析出的IP来随机选择？
假如解析出来的某台机子有问题一直不能重启，那不是一直会有一定的请求会失败吗？

有没有像zookeeper客户端那样自动跳过有问题的机子的功能？

**Comment by xiaokai-wang** [comment]
支持ip 和 域名，集群的话通过域名解析IP 来随机选择；有问题的机器会重试跳过.

**Comment by minminmsn** [comment]
能不能加个tcp负载，提交一个VIP，轮询到后端的IP，这样行吗？

**Comment by xiaokai-wang** [comment]
理论上是可以的哈

**Comment by wanzr** [comment]
我用的 lvs VIP代理是可以的
