### ISSUE TITLE
配置项中的weight不生效

### ISSUE THREAD

**Issue by liuyue2656** [weibocom/nginx-upsync-module#168]
经测试，发现backup模式不生效，打算把weight调成0实现backup的方式，但是发现weight调成0，另外一台调成1之后并不生效。nginx日志记录，还会有访问分发到weigth=0的那台real server上。

**Comment by xiaokai-wang** [comment]
weight＝0 就会变为backup吗，不是吧.

支持设置为down，暂不支持backup 属性;

**Comment by liuyue2656** [comment]
@xiaokai-wang thx，用lua实现了backup了=。=

**Comment by CaoYusong** [comment]
@xiaokai-wang liuyue2656  weight动态可以生效吗，在一致性hash的情况下
