### ISSUE TITLE
upsync_check_key: has no port in /

### ISSUE THREAD

**Issue by niyunjiu** [weibocom/nginx-upsync-module#169]
curl http://192.168.1.208:8500/v1/kv/upstreams/book/?recurse
[{"LockIndex":0,"Key":"upstreams/book/","Flags":0,"Value":null,"CreateIndex":7168,"ModifyIndex":7168},{"LockIndex":0,"Key":"upstreams/book/127.0.0.1:9000","Flags":0,"Value":null,"CreateIndex":7578,"ModifyIndex":7578},{"LockIndex":0,"Key":"upstreams/book/192.168.2.195:9000","Flags":0,"Value":null,"CreateIndex":7575,"ModifyIndex":7575}][niyunjiu@neibu-02-vm servers]
两个后端服务器，但是结果确有3个item，第一个是upstreams/book/，这个显然无法解析出port的。
我用的consul kv模式，consul 0.9.0

**Comment by xiaokai-wang** [comment]
嗯. 既然有两个后端服务器应该有两个item，怎么会有三个呢？这是consul 的问题？

**Comment by niyunjiu** [comment]
consul的设计确实有些不合理。
我的意思是，你们能不能判断一下，过滤一下。

**Comment by xiaokai-wang** [comment]
我有点困惑了：模块里进行了判断，所以会打印no port 的error 日志，并过滤掉了有问题的key 啊

**Comment by niyunjiu** [comment]
明白了，谢谢答复！！
