### ISSUE TITLE
同步consul服务器列表的时候用的是key

### ISSUE THREAD

**Issue by mysterytree** [weibocom/nginx-upsync-module#17]
刚才测试了下
用docker regsitrator直接注册数据到consulkv  大概这个样子
![image](https://cloud.githubusercontent.com/assets/6166794/12441872/61fd6a4a-bf86-11e5-82f1-d3b4a59bdff7.png)
报错了  
![image](https://cloud.githubusercontent.com/assets/6166794/12441874/68f2679c-bf86-11e5-9291-c9c723e8c599.png)
找了半天bug
发现module做同步的时候是抓取的 key 的值  

![image](https://cloud.githubusercontent.com/assets/6166794/12441805/dadeed90-bf85-11e5-8afd-c37a70506903.png)

value哭晕在厕所

很想知道你们为什么用key而不是value？这样用起来方便吗

**Comment by mysterytree** [comment]
@xiaokai-wang

**Comment by xiaokai-wang** [comment]
不好意思，可能文档里没有写明白

value 这个值用来储存server 的一些属性，比如 weight、max_fails...等，现在支持json 格式；

用key 来存储ip 和 port 是结合consul 的key/value 结构综合考虑的

**Comment by mysterytree** [comment]
现在的nginx-upsync 会调用value中的其他数据吗？
还是说value只是其他的应用来调用
@xiaokai-wang

**Comment by xiaokai-wang** [comment]
你注册server 的时候，可能需要调整它的属性，比如：
```
curl -X PUT -d '{"weight":1, "max_fails":2, "fail_timeout":10}' http://$consul_ip:$port/v1/kv/$dir1/$upstream_name/$backend_ip:$backend_port
```

如果你的value 非空，并且合法，模块会解析，并设置server 的属性；value 只是模块用

**Comment by mysterytree** [comment]
好的 感谢

**Comment by luxuan** [comment]
@mysterytree 
看你的截图，regsitrator注册的是容器名称，因为对regsitrator暂不了解，不确定这是regsitrator的实现机制？如果是它的实现，这种设计的合理性是存在怀疑的。
首先，对于容器集群，怎么保证同一业务不同机器上起的容器名是不同的？
再者，即使能容器名的不同，由于对于Nginx无法根据容器名做路由转发，最终还是要去valve中读取IP信息，也就说IP是必不可少的，而且IP+Port本身就能决定key的唯一性，那把它当做key就顺理成章了

感谢

**Comment by mysterytree** [comment]
@luxuan  registrator官方推荐时注册到service里边   
这里的kv其实是service的一个拷贝   也就是service＋id
细节暂时不用考虑 我调整了regsitrator的源码 现在已经与咱的module兼容
感谢！

**Comment by leeeboo** [comment]
@mysterytree 我们最近也在开始配合registrator使用，不知是否可以分享修改的经验？谢

**Comment by mysterytree** [comment]
@leeeboo 改天我写个博

**Comment by mysterytree** [comment]
@leeeboo 不过我们最近转了k8s  你可以试下 不错

**Comment by leeeboo** [comment]
@mysterytree 谢谢。

**Comment by imiskolee** [comment]
我们也在使用 gliderlabs/registrator ，遇到了同样的问题。
为了解决这个问题，我们Fork了一个版本：[nginx-upsync-module](https://github.com/weixinhost/nginx-upsync-module)，以使得nginx-upsync-module支持gliderlabs/registrator 。

**Comment by xiaokai-wang** [comment]
hi @imiskolee ,

建议一起把模块完善，便于以后维护，nginx 后续版本可能会变动；

模块还在持续添加一些新的feature，欢迎提交pr，感谢！

**Comment by mysterytree** [comment]
@imiskolee  直接修改upsync确实比修改registrator更加好一些  感谢分享

**Comment by mysterytree** [comment]
@xiaokai-wang  听说你们今晚在微信群分享这个模块？

**Comment by xiaokai-wang** [comment]
是啊，会介绍一下

**Comment by xiaokai-wang** [comment]
这个是支持挂载不同的解析方法的，可参考upsync_type字段，当前暂时实现了consul，对etcd、zk可以弹性扩展

欢迎多交流

**Comment by mysterytree** [comment]
@xiaokai-wang  感觉支持etcd的话 可以弥补k8s上kube－proxy＋iptables的性能短板   看好此module前景

**Comment by xiaokai-wang** [comment]
@mysterytree 想要实现etcd 的话，实际上只要实现一个解析函数就可以了（解析json 格式），欢迎pr

**Comment by xiaokai-wang** [comment]
already supported etcd, 欢迎试用

**Comment by mysterytree** [comment]
开心
