### ISSUE TITLE
openresty-1.11.2.4 + nginx-upsync-module + nginx_upstream_check_module make异常

### ISSUE THREAD

**Issue by coco535** [weibocom/nginx-upsync-module#171]
没有打补丁的时候的异常：
cc -c -I/root/mysoft/openresty-1.11.2.4/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1  -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -g -O2 -DNDK_SET_VAR -DNDK_UPSTREAM_LIST -DNDK_SET_VAR -DNDK_SET_VAR -DNDK_SET_VAR -DLUA_DEFAULT_PATH='"/usr/local/openresty/site/lualib/?.lua;/usr/local/openresty/site/lualib/?/init.lua;/usr/local/openresty/lualib/?.lua;/usr/local/openresty/lualib/?/init.lua"' -DLUA_DEFAULT_CPATH='"/usr/local/openresty/site/lualib/?.so;/usr/local/openresty/lualib/?.so"' -DNDK_SET_VAR  -I src/core -I src/event -I src/event/modules -I src/os/unix -I ../ngx_devel_kit-0.3.0/objs -I objs/addon/ndk -I ../ngx_lua-0.10.8/src/api -I /root/mysoft/openresty-1.11.2.4/../nginx_upstream_check_module-0.3.0 -I /root/mysoft/openresty-1.11.2.4/../pcre-8.41 -I /root/mysoft/openresty-1.11.2.4/../openssl-1.0.2l/.openssl/include -I objs -I src/http -I src/http/modules -I src/http/v2 -I ../ngx_devel_kit-0.3.0/src -I ../ngx_devel_kit-0.3.0/src -I ../ngx_devel_kit-0.3.0/objs -I objs/addon/ndk -I /root/mysoft/openresty-1.11.2.4/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1 -I /root/mysoft/openresty-1.11.2.4/../nginx-upsync-module-2.0.0/src -I src/stream \
		-o objs/addon/src/ngx_http_upsync_module.o \
		/root/mysoft/openresty-1.11.2.4/../nginx-upsync-module-2.0.0/src/ngx_http_upsync_module.c
/root/mysoft/openresty-1.11.2.4/../nginx-upsync-module-2.0.0/src/ngx_http_upsync_module.c: 在函数‘ngx_http_upsync_add_peers’中:
/root/mysoft/openresty-1.11.2.4/../nginx-upsync-module-2.0.0/src/ngx_http_upsync_module.c:868: 错误：‘ngx_http_upstream_rr_peer_t’没有名为‘check_index’的成员
/root/mysoft/openresty-1.11.2.4/../nginx-upsync-module-2.0.0/src/ngx_http_upsync_module.c: 在函数‘ngx_http_upsync_init_peers’中:
/root/mysoft/openresty-1.11.2.4/../nginx-upsync-module-2.0.0/src/ngx_http_upsync_module.c:2336: 错误：‘ngx_http_upstream_rr_peer_t’没有名为‘check_index’的成员
/root/mysoft/openresty-1.11.2.4/../nginx-upsync-module-2.0.0/src/ngx_http_upsync_module.c:2336: 错误：‘ngx_http_upstream_rr_peer_t’没有名为‘check_index’的成员
gmake[2]: *** [objs/addon/src/ngx_http_upsync_module.o] 错误 1
打完补丁后的异常：
-L/root/mysoft/openresty-1.11.2.4/build/luajit-root/usr/local/openresty/luajit/lib -Wl,-rpath,/usr/local/openresty/luajit/lib -Wl,-E -ldl -lpthread -lpthread -lcrypt -L/root/mysoft/openresty-1.11.2.4/build/luajit-root/usr/local/openresty/luajit/lib -lluajit-5.1 -lm -ldl -lm /root/mysoft/openresty-1.11.2.4/../pcre-8.41/.libs/libpcre.a /root/mysoft/openresty-1.11.2.4/../openssl-1.0.2l/.openssl/lib/libssl.a /root/mysoft/openresty-1.11.2.4/../openssl-1.0.2l/.openssl/lib/libcrypto.a -ldl -lz -lGeoIP \
	-Wl,-E
objs/addon/src/ngx_http_upsync_module.o: In function `ngx_http_upsync_add_peers':
/root/mysoft/openresty-1.11.2.4/../nginx-upsync-module-2.0.0/src/ngx_http_upsync_module.c:866: undefined reference to `ngx_http_upstream_check_add_dynamic_peer'
objs/addon/src/ngx_http_upsync_module.o: In function `ngx_http_upsync_del_peers':
/root/mysoft/openresty-1.11.2.4/../nginx-upsync-module-2.0.0/src/ngx_http_upsync_module.c:1008: undefined reference to `ngx_http_upstream_check_delete_dynamic_peer'
collect2: ld 返回 1
gmake[2]: *** [objs/nginx] 错误 1
gmake[2]: Leaving directory `/root/mysoft/openresty-1.11.2.4/build/nginx-1.11.2'
gmake[1]: *** [build] 错误 2
gmake[1]: Leaving directory `/root/mysoft/openresty-1.11.2.4/build/nginx-1.11.2'
gmake: *** [all] 错误 2

补丁check_1.11.1+.patch 和 check_1.11.5+.patch 都尝试过了依然编译报上面的错误ngx_http_upstream_check_delete_dynamic_peer

**Comment by xiaokai-wang** [comment]
使用健康监测模块[nginx_upstream_check_module](https://github.com/xiaokai-wang/nginx_upstream_check_module)
