### ISSUE TITLE
使用upsync TCP链接增多

### ISSUE THREAD

**Issue by sxauyhz** [weibocom/nginx-upsync-module#175]
每个(work,upstream_backend)一个纬度会和consul建立一个TCP链接；即如果是32个worker，每个nginx上有10个backend，会增加320个TCP长链接。如果有多台nginx，consul的连接数会成倍增加。要是worker可以共享配置就好了？

**Comment by xiaokai-wang** [comment]
是的，当前会占用consul 蛮多fd 资源，只是大部分都处于休眠状态（无更新）；改为共享的也是可以的，类似于健康监测模块的状态共享，只是看到反馈健康监测的状态更新有时会不稳定，这个对于弹性扩缩容可能比较麻烦，所以也并未实行；

**Comment by sxauyhz** [comment]
感谢🙏
