### ISSUE TITLE
nginx-1.13.4 最新nginx-upsync-module

### ISSUE THREAD

**Issue by qist** [weibocom/nginx-upsync-module#178]
../nginx-upsync-module/src/ngx_http_upsync_module.c: 在函数‘ngx_http_upsync_del_delay_delete’中:
../nginx-upsync-module/src/ngx_http_upsync_module.c:3110:41: 错误：变量‘conn_interval’被设定但未被使用 [-Werror=unused-but-set-variable]
     ngx_uint_t                       i, conn_interval;
                                         ^
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/src/ngx_http_upsync_module.o] 错误 1

**Comment by xiaokai-wang** [comment]
fixed, thanks.
