### ISSUE TITLE
nginx-upsync-module+nginx_upstream_check_module cannot be compiled successfully in openresty

### ISSUE THREAD

**Issue by DanielWangSPE** [weibocom/nginx-upsync-module#179]
These two modules can compile successfully in nginx ,but not in openresty(Here i say are compiling  together. If compiling separately, it will be always sucessful in nginx and openresty).
The compiling directive is "./configure --add-module=../nginx_upstream_check_module --add-module=../nginx-upsync-module".
The openresty versions are from 1.9.15.1 to 1.11.2.4(covers the lastest 5 versions).
Below is the compiling error information:
objs/addon/src/ngx_http_upsync_module.o: In function `ngx_http_upsync_add_peers':
/usr/local/openresty-1.11.2.2/../nginx-upsync-module/src/ngx_http_upsync_module.c:874: undefined reference to `ngx_http_upstream_check_add_dynamic_peer'
objs/addon/src/ngx_http_upsync_module.o: In function `ngx_http_upsync_del_peers':
/usr/local/openresty-1.11.2.2/../nginx-upsync-module/src/ngx_http_upsync_module.c:1024: undefined reference to `ngx_http_upstream_check_delete_dynamic_peer'
collect2: ld returned 1 exit status
gmake[2]: *** [objs/nginx] Error 1
gmake[2]: Leaving directory `/usr/local/openresty-1.11.2.2/build/nginx-1.11.2'
gmake[1]: *** [build] Error 2
gmake[1]: Leaving directory `/usr/local/openresty-1.11.2.2/build/nginx-1.11.2'
gmake: *** [all] Error 2.

**Comment by xiaokai-wang** [comment]
nginx_upstream_check_module, please use https://github.com/xiaokai-wang/nginx_upstream_check_module.

**Comment by DanielWangSPE** [comment]
The nginx_upstream_check_module i use is from https://github.com/xiaokai-wang/nginx_upstream_check_module.If convenient,we can talk by qq(362412593) or emails(wangzhisdu@163.com).Tks
