### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by mysterytree** [weibocom/nginx-upsync-module#18]
@xiaokai-wang 
我用marathon 动态更新容器 容器端口随机
然后通过docker registrator注册到consul里边
nginx配置文件里边写的是：
1.upsync 127.0.0.1:8500/v1/kv/haserver/haserver
![image](https://cloud.githubusercontent.com/assets/6166794/12473686/525df022-c04f-11e5-8a00-f96b1f3d377c.png)
我在添加和删除consul里边的ip的时候 
/usr/local/nginx/conf/servers/servers_test.conf
里的列表确实能够正常动态更新
但我一旦将/kv/haserver/haserver整个删除
servers_test.conf并不会更新（变成空）
2. 我将轮询间隔设置了50ms 
然后用benchmark去测试nginx
刚开始测试挺正常的
但随着我更新consul
发现经常有upstream失败的情况
ab -n 10 -c 10 http://192.168.1.55/
![image](https://cloud.githubusercontent.com/assets/6166794/12473836/cdefcade-c050-11e5-9d0d-747be5b27f09.png)

![image](https://cloud.githubusercontent.com/assets/6166794/12473821/a50013ea-c050-11e5-8e05-72ab6e493a00.png)

这种情况经常出现  而且都是整数型的失败
![image](https://cloud.githubusercontent.com/assets/6166794/12473865/090ea946-c051-11e5-909d-6e8a0122eed0.png)
![image](https://cloud.githubusercontent.com/assets/6166794/12473872/1c2eadd2-c051-11e5-8901-b00d2b639c09.png)

![image](https://cloud.githubusercontent.com/assets/6166794/12473861/0036d2a8-c051-11e5-9b40-de24f7937fe2.png)

**Comment by mysterytree** [comment]
难道是我打开方式不对

**Comment by xiaokai-wang** [comment]
hi,
1. 模块的功能是扩容、缩容，并不支持整个upstream的删除；传统意义上整个upstream的删除意味着相应的location(即对应的业务下线) 删除，这个需要修改nginx的主配置文件，需要nginx reload 来生效；

2. 用ab 压测没有问题，失败的类型是后端返回的body 长度不一致，你频繁的添加、删除后端节点，后端节点返回的信息都是怎样的？相同么？可以用 wrk 压测试一下.

有什么问题欢迎及时交流

**Comment by mysterytree** [comment]
@xiaokai-wang 
body长度不一致？什么原因造成的。。
ab
![image](https://cloud.githubusercontent.com/assets/6166794/12475732/df6be2c0-c05f-11e5-8c75-b3ccc99a7d0e.png)
wrk
![image](https://cloud.githubusercontent.com/assets/6166794/12475753/fb72cae2-c05f-11e5-8ef3-1a2961eb67f5.png)

**Comment by mysterytree** [comment]
我用ab挨着压测单个节点   没有failed
只有upstream的时候有问题

**Comment by mysterytree** [comment]
应用是个golang写的简单server
```
package main

import (
	"flag"
	"fmt"
	"net/http"
	"os"
	"time"

	"github.com/facebookgo/grace/gracehttp"
)

var (
	address0 = flag.String("a0", ":9099", "Zero address to bind to.")
	now      = time.Now()
)

func main() {
	flag.Parse()
	gracehttp.Serve(
		&http.Server{Addr: *address0, Handler: newHandler()},
	)
}

func newHandler() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(
			w,
			"%s started at %s slept for %d nanoseconds from pid %d.\n",
			"s",
			now,
			os.Getpid(),
		)
	})
	return mux
}

```
跑在容器里的

**Comment by xiaokai-wang** [comment]
用ab 压测单个节点没有问题，压测所有的节点，并且频繁的扩容、缩容会出现这个问题；

对比access 日志，里面返回的长度应该都是一致的；这个我认为是工具本身造成的，没有过多的深入研究ab 这个工具，抱歉，另参数里可以设置忽略返回的长度；

**Comment by mysterytree** [comment]
有附带wrk的测试结果 在楼上  没明确标示出来

**Comment by xiaokai-wang** [comment]
```
./wrk -t8 -c100 -d5m --timeout 3s "http://10.75.16.37:8888/proxy_test"
Running 5m test @ http://10.75.16.37:8888/proxy_test
  8 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.94ms  573.56us  20.39ms   62.78%
    Req/Sec     6.20k   294.75     7.07k    61.63%
  14799843 requests in 5.00m, 2.29GB read
Requests/sec:  49316.38
Transfer/sec:      7.83MB
```

这是我的压测数据，后端挂的也是nginx，频繁的向consul 加减一个节点；有时候出错，跟你后端的承载力是有关系的

**Comment by xiaokai-wang** [comment]
```
./wrk -t8 -c100 -d5m --timeout 3s "http://$ip:8888/proxy_test"
Running 5m test @ http://10.75.16.37:8888/proxy_test
  8 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.94ms  573.56us  20.39ms   62.78%
    Req/Sec     6.20k   294.75     7.07k    61.63%
  14799843 requests in 5.00m, 2.29GB read
Requests/sec:  49316.38
Transfer/sec:      7.83MB
```

这是我的压测数据，后端挂的是3个nginx，频繁的向consul 注册/注销 某一个节点，所得数据；
有时出错，跟你后端的承载力也是有关系的，具体的可以查看日志，可以把日志贴出来；
