### ISSUE TITLE
当从consul读取不到的情况下，reload了nginx后，不会使用之前的dump文件中的server

### ISSUE THREAD

**Issue by xukunfeng** [weibocom/nginx-upsync-module#180]
nginx version: nginx/1.10.1
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC)
built with OpenSSL 1.0.1g 7 Apr 2014
TLS SNI support enabled
configure arguments: --prefix=/usr/local/nginx --sbin-path=/usr/sbin/nginx --conf-path=/usr/local/nginx/nginx.conf --error-log-path=/usr/local/nginx/log/error.log --http-log-path=/usr/local/nginx/log/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-http_auth_request_module --with-mail --with-stream --with-stream_ssl_module --with-mail_ssl_module --with-file-aio --with-ipv6 --with-cc-opt='-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic' --with-pcre=/usr/local/src/pcre-8.34 --with-zlib=/usr/local/src/zlib-1.2.8 --with-openssl=/usr/local/src/openssl-1.0.1g --add-module=/usr/local/src/nginx-upsync-module-master --add-module=/usr/local/src/ngx_cache_purge-2.3 --add-module=/usr/local/src/nginx-goodies-nginx-sticky-module-ng-08a395c66e42

当upsync调用consul的接口，读取到的健康实例为空的时候：
未reload前： 会使用上一次可用健康的server
reload后： 使用fake server

期望： reload后也是使用上次可用的server或者dump文件中的server

**Comment by xiaokai-wang** [comment]
麻烦贴出配置的指令

**Comment by xukunfeng** [comment]
upstream myou-webpub{
        server 10.25.69.158:8085;
        upsync myou-consul.service.consul:14001/v1/upstream/myou_webpub/health/query upsync_timeout=6m upsync_interval=500ms upsync_type=consul strong_dependency=off;
        upsync_dump_path /usr/local/nginx/conf/servers/myou_webpub.conf;
        keepalive 16;
}
myou-consul 是一个中间服务，会访问consul，并取到健康的server列表，例如：
[
  {
    "Key": "upstreams/myou_webpub/10.7.9.51:8080",
    "Value": "eyJ3ZWlnaHQiOjEsIm1heF9mYWlscyI6MiwiZmFpbF90aW1lb3V0IjoxMH0="
  },
  {
    "Key": "upstreams/myou_webpub/10.7.0.23:8080",
    "Value": "eyJ3ZWlnaHQiOjEsIm1heF9mYWlscyI6MiwiZmFpbF90aW1lb3V0IjoxMH0="
  }
]
当没有任何可用的server的时候，返回是
[]

实验发现strong_dependency 设置成on和off 结果一样

**Comment by xiaokai-wang** [comment]
模块代码请使用master分支最新代码，配置更新为如下方式，麻烦再试一下：
```
upstream myou-webpub{
        upsync myou-consul.service.consul:14001/v1/upstream/myou_webpub/health/query 
        upsync_timeout=6m upsync_interval=500ms upsync_type=consul strong_dependency=off;
        upsync_dump_path /usr/local/nginx/conf/servers/myou_webpub.conf;

        include /usr/local/nginx/conf/servers/myou_webpub.conf;

        keepalive 16;
}
```
