### ISSUE TITLE
nginx-upsync-module与nginx_upstream_check_module同时编译报错

### ISSUE THREAD

**Issue by hanzixiaoshu** [weibocom/nginx-upsync-module#182]
您好，我使用的是nginx1.13.3版本，同时编译这两个模块时报以下错误，但是单编译这两个模块没有错误，请问是什么问题？
objs/addon/src/ngx_http_upsync_module.o: In function `ngx_http_upsync_add_peers':
/usr/src/nginx-upsync-module-master/src/ngx_http_upsync_module.c:893: undefined reference to `ngx_http_upstream_check_add_dynamic_peer'
objs/addon/src/ngx_http_upsync_module.o: In function `ngx_http_upsync_del_peers':
/usr/src/nginx-upsync-module-master/src/ngx_http_upsync_module.c:1043: undefined reference to `ngx_http_upstream_check_delete_dynamic_peer'
collect2: ld 返回 1
make[1]: *** [objs/nginx] 错误 1
make[1]: Leaving directory `/usr/src/nginx-1.13.3'
make: *** [build] 错误 2

**Comment by xiaokai-wang** [comment]
健康检测模块请用：https://github.com/xiaokai-wang/nginx_upstream_check_module
