### ISSUE TITLE
nginx reload 会导致请求转发到默认upstream

### ISSUE THREAD

**Issue by wanzr** [weibocom/nginx-upsync-module#186]
nginx version: nginx/1.12.1
编译参数 --add-module=../nginx-upsync
目前已用于生产环境，最近发现nginx reload会有部分请求返回502，查看日志发现有部分请求被转发到 http://127.0.0.1:11111/ 也就是upstream的默认配置，我理解nginx启动应该先加载upsync_dump_path所指定的配置, 但是upsync_dump_path的文件中是存在host的。 upstream共有450个，是upstream数量过多导致加载慢造成的么，还是可能有其他原因？麻烦帮看下 非常感谢~

附件是截取部分nginx reload的 error.log 和upstream 配置
etcd-lvs.abc.org 为LVS的地址，代理后端etcd集群。 'upsync_parse_json: nodes is null, no servers'是因为etcd中存在存在个别upstream为空。
[error.log](https://github.com/weibocom/nginx-upsync-module/files/1470818/error.log)

**Comment by xiaokai-wang** [comment]
你好，最新版本去掉了fake server，增加include；麻烦更新一下

reload 过程中，在之前版本，在work 进程工作之前会拉取server，拉取失败（尝试三次，默认）的话，有可能会把请求打到fake server 上；

**Comment by wanzr** [comment]
@xiaokai-wang  升级后问题解决了，非常感谢。
