### ISSUE TITLE
worker process exited on signal 11 

### ISSUE THREAD

**Issue by xukunfeng** [weibocom/nginx-upsync-module#188]
使用upsync最新的master代码编译，在nginx运行过程中概率出现：
2017/11/20 11:24:05 [alert] 5413#5413: worker process 20299 exited on signal 11 (core dumped)
有大量的错误出现，且最终只能重启恢复。

nginx version: nginx/1.12.2
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC)
built with OpenSSL 1.0.1g 7 Apr 2014
TLS SNI support enabled
configure arguments: --prefix=/usr/local/nginx --sbin-path=/usr/sbin/nginx --conf-path=/usr/local/nginx/nginx.conf --error-log-path=/usr/local/nginx/log/error.log --http-log-path=/usr/local/nginx/log/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-http_v2_module --with-threads --with-http_auth_request_module --with-mail --with-stream --with-stream_ssl_module --with-mail_ssl_module --with-file-aio --with-ipv6 --with-cc-opt='-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic' --with-pcre=/usr/local/src/pcre-8.34 --with-zlib=/usr/local/src/zlib-1.2.8 --with-openssl=/usr/local/src/openssl-1.0.1g --add-module=/usr/local/src/nginx-upsync --add-module=/usr/local/src/ngx_cache_purge-2.3 --add-module=/usr/local/src/nginx-goodies-nginx-sticky-module-ng-08a395c66e42

coredump:https://drive.cvte.com/p/DbuarQsQ4AIY5n0
nginx: https://drive.cvte.com/p/DTP9qWgQ4AIY5X0

**Comment by xukunfeng** [comment]
(gdb) bt
#0  0x000000000044c896 in ngx_memn2cmp (s1=0x5016ad4 "\002", s2=0x0, n1=16, n2=85636752) at src/core/ngx_string.c:836
#1  0x00000000004d99c8 in ngx_http_upstream_get_keepalive_peer (pc=0x433f110, data=0x433f768) at src/http/modules/ngx_http_upstream_keepalive_module.c:239
#2  0x00000000004660ac in ngx_event_connect_peer (pc=0x433f110) at src/event/ngx_event_connect.c:34
#3  0x00000000004964f0 in ngx_http_upstream_connect (r=0x2f527d0, u=0x433f100) at src/http/ngx_http_upstream.c:1485
#4  0x0000000000496e2c in ngx_http_upstream_init_request (r=0x2f527d0) at src/http/ngx_http_upstream.c:790
#5  0x000000000048c16f in ngx_http_read_client_request_body (r=0x2f527d0, post_handler=0x497670 <ngx_http_upstream_init>) at src/http/ngx_http_request_body.c:147
#6  0x00000000004c5bad in ngx_http_proxy_handler (r=0x2f527d0) at src/http/modules/ngx_http_proxy_module.c:929
#7  0x000000000047d5f0 in ngx_http_core_content_phase (r=0x2f527d0, ph=<optimized out>) at src/http/ngx_http_core_module.c:1386

**Comment by xiaokai-wang** [comment]
从堆栈看是拿到了非法的server，server 的ip 是空的；很奇怪；

加一下联系方式？没看到你的邮箱，方便把你的联系方式发到我的邮箱吗？@xukunfeng

**Comment by xukunfeng** [comment]
xukunfeng@cvte.com

**Comment by xiaokai-wang** [comment]
第一次碰到这种情况，想了解下你的场景

**Comment by xiaokai-wang** [comment]
问题同 #192 ，感谢你的反馈与协助，谢谢.
