### ISSUE TITLE
keepalive的值会自动变化

### ISSUE THREAD

**Issue by adaiguoguo** [weibocom/nginx-upsync-module#19]
模板文件设置如下
upstream test {
	server 127.0.0.1:11111;

	upsync 192.168.80.142:8500/v1/kv/bnspear/upstream/test/vitality  upsync_timeout=6m upsync_interval=500ms upsync_type=consul strong_dependency=off;
	upsync_conf_path /tmp/test.conf;

	keepalive 512;
	check interval=3000 rise=2 fall=3 timeout=2000 type=tcp;
}

同步后/tmp/test.conf中keepalive的数值会自动改变，并且这个数值会随着反向代理的node数量相等
upstream test {
	keepalive 4;

	upsync 192.168.80.142:8500/v1/kv/bnspear/upstream/zeus.eus/vitality upsync_interval=500ms upsync_timeout=360000ms upsync_type=consul;
	upsync_conf_path /tmp/test.conf;

	server 192.168.11.2:15200 weight=1 max_fails=3 fail_timeout=30s;
	server 192.168.11.3:15200 weight=1 max_fails=3 fail_timeout=30s;
	server 192.168.11.4:15200 weight=1 max_fails=3 fail_timeout=30s;
	server 192.168.11.5:15200 weight=1 max_fails=3 fail_timeout=30s;

	check interval=3000 rise=2 fall=3 timeout=2000 type=tcp default_down=true;
	check_keepalive_requests 1;
	check_http_send "";
	check_http_expect_alive http_2xx http_3xx;
}

**Comment by xiaokai-wang** [comment]
你用的是分支：weibo_version?

**Comment by adaiguoguo** [comment]
是的

**Comment by adaiguoguo** [comment]
是的

**Comment by adaiguoguo** [comment]
和tengine2.1.2

**Comment by xiaokai-wang** [comment]
这个分支是这样子的，不具有通用性；

主分支修改了dump 策略，为了保持通用性，只dump upstream 的 server；

可以用主分支，upstream 里配置的其它参数就不会受影响

**Comment by adaiguoguo** [comment]
主分支和tengine2.1.2配合是否有啥特别问题？

**Comment by xiaokai-wang** [comment]
我测试过的版本是 tengine-2.2.0, 没有，或者说暂时没有发现

**Comment by xiaokai-wang** [comment]
tengine 只要是基于官方nginx-1.8.0 应该都适用
