### ISSUE TITLE
nginx_status 计数异常

### ISSUE THREAD

**Issue by wanzr** [weibocom/nginx-upsync-module#192]
nginx version: nginx/1.12.2
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) 
built with OpenSSL 1.0.2j  26 Sep 2016
TLS SNI support enabled
configure arguments: --prefix=/opt/tuniu/nginx --user=www --group=www --with-ld-opt=-Wl,-rpath,/usr/local/luajit/lib --with-openssl=../openssl-1.0.2j --with-pcre=../pcre-8.39/ --with-zlib=../zlib-1.2.8/ --with-http_realip_module --with-http_ssl_module --with-http_stub_status_module --add-module=../ngx_devel_kit-0.3.0 --add-module=../ngx_cache_purge-2.3 --add-module=../nginx-http-concat --with-stream --add-module=../nginx-upsync --add-module=../lua-nginx-module --add-module=../nginx-sticky-module-ng
为了修复nginx reload 导致请求转发到 fake server，同时升级了nginx版本和最新的upsync模块，运行一段时间后出现了nginx status计数器会出现异常飙升，但实际的nginx链接数是正常的，nginx 重启后恢复正常，过一段时间后又出现异常。 有遇到过类似的问题么？
还有nginx作为docker网关，docker使用动态ip，变更很频繁，error log 经常有‘upsync_timeout: timed out reading upsync_server: 10.40.11.102:2333’ ，upstream 参数‘upsync_timeout=6m upsync_interval=5000ms upsync_type=etcd strong_dependency=off’ 是否合理？
方便加一下你的联系方式嘛? 我的邮箱 wanzhirui1990@126.com

**Comment by xiaokai-wang** [comment]
因为最新的优化升级，去掉了fake server，所以用新的代码而还用fake server 时便有可能打到fake server 上；
升级前用fake server 则不会出现打到fake server 的问题；

nginx status 异常跟模块有关系吗？我把联系方式发你邮箱了

**Comment by xiaokai-wang** [comment]
@wanzr 感谢你的协助排查，谢谢；

问题是由于上次优化时引入的，已修复.
