### ISSUE TITLE
支持stream的upstream sync

### ISSUE THREAD

**Issue by collinmsn** [weibocom/nginx-upsync-module#20]
用了一下，目前不支持stream的ups sync，能否增加一下

**Comment by xiaokai-wang** [comment]
是的，暂不支持stream 的 ups sync, 后续会考虑支持

**Comment by gembin** [comment]
+1,  需要stream

**Comment by xiaokai-wang** [comment]
用nginx 做四层的多么？

**Comment by gembin** [comment]
Nginx 1.9 开始支持stream,  用做tcp proxy代替HAProxy了， 这样就不用多去维护一个HAProxy.   估计应该有不少人在用nginx做tcp proxy.

**Comment by xiaokai-wang** [comment]
[nginx-stream-upsync-module](https://github.com/xiaokai-wang/nginx-stream-upsync-module) support stream(tcp protocol) module, please have a look and a try. 

thanks.
