### ISSUE TITLE
reload nginx 报错 nginx: [emerg] directive "server" has no opening

### ISSUE THREAD

**Issue by mulihong** [weibocom/nginx-upsync-module#201]
[root@test1vl:/app/nginx/sbin]#./nginx -s reload
nginx: [emerg] directive "server" has no opening "{" in /app/nginx/conf/servers/consul-account.conf:1

consul-account.conf文件内容
server 10.201.68.61:8080 weight=1 max_fails=2 fail_timeout=10s;
server 10.201.68.60:8080 weight=1 max_fails=2 fail_timeout=10s;

consul.conf
upstream Consul_Server {
 
           upsync 10.201.68.152:8500/v1/kv/upstreams/Consul_Server/ upsync_timeout=6m upsync_interval=500ms upsync_type=consul strong_dependency=off;
           upsync_dump_path /app/nginx/conf/servers/consul-account.conf;
           include  /app/nginx/conf/servers/consul-account.conf;
}

nginx version: nginx/1.10.3
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC) 
built with OpenSSL 1.0.1e-fips 11 Feb 2013
TLS SNI support enabled
configure arguments: --prefix=/app/nginx --user=mwopr --group=mwopr --with-http_stub_status_module --with-http_ssl_module --add-module=/app/nginx-upsync-module-master/

测试出现两个问题
1. 每次reload时都是报错,只能把从consul拉取的文件内容全部清空,或者删除,才能reload成功.
2. 转发到后台两个应用, 请求都只能落到其中一个节点,round_robin,least_conn 算法都试过.
   如果修改consul中节点的权重值之后,请求才能到另外一个节点。
   curl -X PUT -d "{\"- weight\":5, \"max_fails\":2, \"fail_timeout\":10, \"down\":0}"    http://10.201.68.152:8500/v1/kv/upstreams/Consul_Server/10.201.68.61:8080

3. 使用include包含fake server时,reload nginx报错。
include  /app/nginx/conf/servers/consul-account.conf; 
文件内容
server  127.0.0.1:8080;
启动报错:
nginx: [emerg] directive "server" has no opening "{" in /app/nginx/conf/servers/consul-account.conf:1

**Comment by xiaokai-wang** [comment]
@mulihong 你好，include 里面都是true server（consul 里有的），不能使用fake server；
最新版本的模块这边已经做了更新，你用true server 试试；

**Comment by mulihong** [comment]
好的, 我再测试下。 关于第一、第二个问题, 有什么建议吗？ 谢谢。

**Comment by xiaokai-wang** [comment]
@mulihong 你再试一下先，第一、二个问题暂时没碰到过.

**Comment by mulihong** [comment]
[root@testlv:/app/nginx/sbin]#./nginx -s reload                              
nginx: [emerg] directive "server" has no opening "{" in /app/nginx/conf/servers/consul-account.conf:1

重启还是报错
[root@testlv:/app/nginx/conf/servers]#cat consul-account.conf 
server 10.204.58.60:8080 weight=1 max_fails=2 fail_timeout=10s;
server 10.204.58.61:8080 weight=1 max_fails=2 fail_timeout=10s;

**Comment by xiaokai-wang** [comment]
重启之后功能上有影响吗？

**Comment by xiaokai-wang** [comment]
@mulihong 你好，问题解决了吗？

**Comment by scottzzq** [comment]
@xiaokai-wang  我今天也遇到这个问题，原因基本上可以定位是在include的时候写了通配符路径，把dump出来的那个文件直接include到nginx.conf中了

**Comment by xiaokai-wang** [comment]
噢？ @scottzzq 用了什么通配符呢？能贴出来吗

**Comment by gfrankliu** [comment]
dump出来的那个文件必须include在upstream里面。
例如：

```
...
    upstream test {
        upsync 127.0.0.1:8500/v1/kv/upstreams/test/ upsync_timeout=6m upsync_interval=500ms upsync_type=consul strong_dependency=off;
        upsync_dump_path /usr/local/nginx/conf/servers/servers_test.conf;

        include /usr/local/nginx/conf/servers/servers_test.conf;
    }
...
```

**Comment by W-BC0001** [comment]
# `nginx: [emerg] directive "server" has no opening "{" in`问题分析及解决办法

## 问题分析:

upstream 配置

```shell
upstream test {
        upsync 127.0.0.1:8500/v1/kv/upstreams/test/ upsync_timeout=6m upsync_interval=500ms upsync_type=consul strong_dependency=off;
        upsync_dump_path /data/etc/nginx/test/server.conf;

        include /data/etc/nginx/test/server.conf; 

        keepalive 100;
}
```

nginx.conf

```shell
...
        include /data/etc/nginx/test/*.conf; # 这里的通配符路径也包括了 upsync_dump_path, 导致报错
...
```

## 解决办法

upsync_dump_path 不要在 nginx.conf 中直接引用

例如:

```shell
upstream test {
        upsync 127.0.0.1:8500/v1/kv/upstreams/test/ upsync_timeout=6m upsync_interval=500ms upsync_type=consul strong_dependency=off;
        upsync_dump_path /tmp/servers/server.conf; # 注意  upsync_dump_path 修改了

        include /tmp/servers/server.conf;

        keepalive 100;
}
```

nginx.conf 保持不变

```shell
...
        include /data/etc/nginx/test/*.conf;
...
```
