### ISSUE TITLE
nginx-1.13.10 centos7 compile error.

### ISSUE THREAD

**Issue by qzj** [weibocom/nginx-upsync-module#204]
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -DNDK_SET_VAR -DNDK_SET_VAR -DNDK_SET_VAR -DNDK_SET_VAR -DNDK_SET_VAR -DNDK_SET_VAR -DNDK_SET_VAR -DNDK_UPSTREAM_LIST  -I src/core -I src/event -I src/event/modules -I src/os/unix -I ../ngx_devel_kit-master/objs -I objs/addon/ndk -I ../lua-nginx-module-master/src/api -I ../nginx_upstream_check_module-master -I ../nginx-push-stream-module-master/src -I ../nginx-push-stream-module-master/include -I ../nginx_upstream_check_module-master -I /usr/include/libxml2 -I objs -I src/http -I src/http/modules -I src/http/v2 -I ../ngx_devel_kit-master/src -I ../ngx_devel_kit-master/src -I ../ngx_devel_kit-master/objs -I objs/addon/ndk -I /usr/include/luajit-2.0 -I ../nginx-upsync-module-master/src -I src/mail -I src/stream \
        -o objs/addon/src/ngx_http_upsync_module.o \
        ../nginx-upsync-module-master/src/ngx_http_upsync_module.c
../nginx-upsync-module-master/src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_add_peers’:
../nginx-upsync-module-master/src/ngx_http_upsync_module.c:891:17: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘check_index’
             peer->check_index = index;
                 ^
../nginx-upsync-module-master/src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_replace_peers’:
../nginx-upsync-module-master/src/ngx_http_upsync_module.c:1226:17: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘check_index’
             peer->check_index = tmp_peer[i].check_index;
                 ^
../nginx-upsync-module-master/src/ngx_http_upsync_module.c:1226:44: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘check_index’
             peer->check_index = tmp_peer[i].check_index;
                                            ^
make[1]: *** [objs/addon/src/ngx_http_upsync_module.o] Error 1
make[1]: Leaving directory `/home/root1/3/nginx-1.13.10'
make: *** [build] Error 2

**Comment by gfrankliu** [comment]
It seems you have lots of third party modules. To start, can you just use nginx and this module only? Let's see if you can reproduce the issue.

**Comment by qzj** [comment]
git clone https://github.com/weibocom/nginx-upsync-module.git
git clone https://github.com/xiaokai-wang/nginx-stream-upsync-module.git
wget http://nginx.org/download/nginx-1.13.10.tar.gz
tar -zxf nginx-1.13.10.tar.gz
cd nginx-1.13.10
./configure \
    --prefix=/usr/local/nginx \
    --user=nobody \
    --group=nobody \
    --with-poll_module \
    --with-file-aio \
    --with-http_ssl_module \
    --with-http_v2_module \
    --with-http_realip_module \
    --with-pcre \
    --with-pcre-jit \
    --with-stream \
    --with-stream_ssl_module \
    --with-stream_realip_module \
    --with-stream_ssl_preread_module \
    --with-http_gunzip_module \
    --with-http_secure_link_module \
    --with-http_stub_status_module \
    --with-http_xslt_module \
    --add-module=../nginx-stream-upsync-module \
    --add-module=../nginx-upsync-module \


make -j4

the result still have somethins wrong.

-ldl -lpthread -lcrypt -lm -lm -lpcre -lssl -lcrypto -ldl -lz -lxml2 -lxslt -lexslt \
-Wl,-E
objs/addon/src/ngx_http_json.o: In function `cJSON_GetErrorPtr':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:37: multiple definition of `cJSON_GetErrorPtr'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:37: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_InitHooks':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:63: multiple definition of `cJSON_InitHooks'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:63: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_Delete':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:83: multiple definition of `cJSON_Delete'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:83: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_ParseWithOpts':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:254: multiple definition of `cJSON_ParseWithOpts'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:254: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_Parse':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:269: multiple definition of `cJSON_Parse'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:269: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_Print':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:272: multiple definition of `cJSON_Print'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:272: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_PrintUnformatted':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:273: multiple definition of `cJSON_PrintUnformatted'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:273: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_GetArraySize':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:500: multiple definition of `cJSON_GetArraySize'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:500: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_GetArrayItem':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:501: multiple definition of `cJSON_GetArrayItem'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:501: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_GetObjectItem':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:502: multiple definition of `cJSON_GetObjectItem'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:502: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_AddItemToArray':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:510: multiple definition of `cJSON_AddItemToArray'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:510: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_AddItemToObject':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:511: multiple definition of `cJSON_AddItemToObject'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:511: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_AddItemReferenceToArray':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:512: multiple definition of `cJSON_AddItemReferenceToArray'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:512: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_AddItemReferenceToObject':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:513: multiple definition of `cJSON_AddItemReferenceToObject'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:513: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_DetachItemFromArray':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:515: multiple definition of `cJSON_DetachItemFromArray'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:515: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_DeleteItemFromArray':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:520: multiple definition of `cJSON_DeleteItemFromArray'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:520: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_DetachItemFromObject':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:521: multiple definition of `cJSON_DetachItemFromObject'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:521: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_DeleteItemFromObject':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:522: multiple definition of `cJSON_DeleteItemFromObject'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:522: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_ReplaceItemInArray':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:525: multiple definition of `cJSON_ReplaceItemInArray'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:525: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_ReplaceItemInObject':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:528: multiple definition of `cJSON_ReplaceItemInObject'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:528: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_CreateNull':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:531: multiple definition of `cJSON_CreateNull'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:531: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_CreateTrue':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:532: multiple definition of `cJSON_CreateTrue'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:532: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_CreateFalse':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:533: multiple definition of `cJSON_CreateFalse'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:533: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_CreateBool':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:534: multiple definition of `cJSON_CreateBool'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:534: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_CreateNumber':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:535: multiple definition of `cJSON_CreateNumber'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:535: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_CreateString':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:536: multiple definition of `cJSON_CreateString'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:536: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_CreateArray':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:537: multiple definition of `cJSON_CreateArray'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:537: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_CreateObject':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:538: multiple definition of `cJSON_CreateObject'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:538: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_CreateIntArray':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:541: multiple definition of `cJSON_CreateIntArray'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:541: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_CreateFloatArray':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:542: multiple definition of `cJSON_CreateFloatArray'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:542: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_CreateDoubleArray':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:543: multiple definition of `cJSON_CreateDoubleArray'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:543: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_CreateStringArray':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:544: multiple definition of `cJSON_CreateStringArray'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:544: first defined here
objs/addon/src/ngx_http_json.o: In function `cJSON_Duplicate':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_json.c:548: multiple definition of `cJSON_Duplicate'
objs/addon/src/ngx_stream_json.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_json.c:548: first defined here
objs/addon/src/ngx_http_parser.o: In function `http_message_needs_eof':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_parser.c:2083: multiple definition of `http_message_needs_eof'
objs/addon/src/ngx_stream_http_parser.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_http_parser.c:2083: first defined here
objs/addon/src/ngx_http_parser.o: In function `http_should_keep_alive':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_parser.c:2105: multiple definition of `http_should_keep_alive'
objs/addon/src/ngx_stream_http_parser.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_http_parser.c:2105: first defined here
objs/addon/src/ngx_http_parser.o: In function `http_parser_execute':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_parser.c:630: multiple definition of `http_parser_execute'
objs/addon/src/ngx_stream_http_parser.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_http_parser.c:630: first defined here
objs/addon/src/ngx_http_parser.o: In function `http_method_str':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_parser.c:2124: multiple definition of `http_method_str'
objs/addon/src/ngx_stream_http_parser.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_http_parser.c:2124: first defined here
objs/addon/src/ngx_http_parser.o: In function `http_parser_init':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_parser.c:2132: multiple definition of `http_parser_init'
objs/addon/src/ngx_stream_http_parser.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_http_parser.c:2132: first defined here
objs/addon/src/ngx_http_parser.o: In function `http_parser_settings_init':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_parser.c:2142: multiple definition of `http_parser_settings_init'
objs/addon/src/ngx_stream_http_parser.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_http_parser.c:2142: first defined here
objs/addon/src/ngx_http_parser.o: In function `http_errno_name':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_parser.c:2147: multiple definition of `http_errno_name'
objs/addon/src/ngx_stream_http_parser.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_http_parser.c:2147: first defined here
objs/addon/src/ngx_http_parser.o: In function `http_errno_description':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_parser.c:2153: multiple definition of `http_errno_description'
objs/addon/src/ngx_stream_http_parser.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_http_parser.c:2153: first defined here
objs/addon/src/ngx_http_parser.o: In function `http_parser_parse_url':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_parser.c:2298: multiple definition of `http_parser_parse_url'
objs/addon/src/ngx_stream_http_parser.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_http_parser.c:2298: first defined here
objs/addon/src/ngx_http_parser.o: In function `http_parser_pause':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_parser.c:2400: multiple definition of `http_parser_pause'
objs/addon/src/ngx_stream_http_parser.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_http_parser.c:2400: first defined here
objs/addon/src/ngx_http_parser.o: In function `http_body_is_final':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_parser.c:2410: multiple definition of `http_body_is_final'
objs/addon/src/ngx_stream_http_parser.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_http_parser.c:2410: first defined here
objs/addon/src/ngx_http_parser.o: In function `http_parser_version':
/data/1/nginx-1.13.10/../nginx-upsync-module/src/ngx_http_parser.c:2418: multiple definition of `http_parser_version'
objs/addon/src/ngx_stream_http_parser.o:/data/1/nginx-1.13.10/../nginx-stream-upsync-module/src/ngx_stream_http_parser.c:2418: first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [objs/nginx] Error 1
make[1]: Leaving directory `/data/1/nginx-1.13.10'
make: *** [build] Error 2

**Comment by gfrankliu** [comment]
Don't use nginx-stream-upsync-module and nginx-upsync-module together. Both of them bundles the same cjson code, that's why you see "multiple definition" errors.
If you really want to use both, you will need to json parser from "config" of one of the modules, eg: in nginx-stream-upsync-module/config, remove
  $ngx_addon_dir/src/ngx_stream_json.c \
  $ngx_addon_dir/src/ngx_stream_http_parser.c \

@xiaokai-wang , any ifdef tricks we can do, so people can use both modules?

**Comment by qzj** [comment]
Thanks,  it looks conflicted both of this 2 modules ,  and it's passed after remove 1.    We are looking forward to see the new functions that can use both modules.

**Comment by gfrankliu** [comment]
https://github.com/xiaokai-wang/nginx-stream-upsync-module/pull/30

**Comment by xiaokai-wang** [comment]
@gfrankliu Great. Thanks.

**Comment by gfrankliu** [comment]
@qzj 
I just merged the fix in nginx-stream-upsync-module. Can you check out and try again?
You should now be able to use both nginx-upsync-module and nginx-stream-upsync-module.
