### ISSUE TITLE
consul关闭的状态下重启nginx，没有读取dump下来的server列表

### ISSUE THREAD

**Issue by devin1982** [weibocom/nginx-upsync-module#206]
<img width="554" alt="default" src="https://user-images.githubusercontent.com/10161364/38019817-38ddd3d0-32ab-11e8-97cc-f3b6e4452e9c.png">

<img width="512" alt="default" src="https://user-images.githubusercontent.com/10161364/38019770-14fc0ed2-32ab-11e8-8226-bbf5c0b81cd1.png">

<img width="989" alt="default" src="https://user-images.githubusercontent.com/10161364/38019708-e72c9936-32aa-11e8-99ee-2d1af0ab84a7.png">

![default](https://user-images.githubusercontent.com/10161364/38019746-07076628-32ab-11e8-9680-13da388715e3.png)

**Comment by xiaokai-wang** [comment]
参考 #193

**Comment by devin1982** [comment]
就是用的master分支最新的代码，upstream里写include提示配置文件语法错误，我nginx1.9.7，是不是nginx版本太低？

**Comment by xiaokai-wang** [comment]
意思是把server 配置项都放到include 文件里；看你的upstream test 里有server 配置项；

**Comment by devin1982** [comment]
<img width="972" alt="default" src="https://user-images.githubusercontent.com/10161364/38066875-8c36b5ba-333c-11e8-8614-d548a5c1d62c.png">
<img width="596" alt="default" src="https://user-images.githubusercontent.com/10161364/38066889-96dc428c-333c-11e8-8f22-d0a9d62b50d4.png">
<img width="603" alt="default" src="https://user-images.githubusercontent.com/10161364/38066912-a948c878-333c-11e8-978e-179df940418a.png">
upsteam里没有server 加上include无法启动，是不是我的版本的nginx不支持upsteam里有include指令

**Comment by devin1982** [comment]
问题解决了，是nginx1.9.x版本不支持upstream中使用include指令的原因，解决方案是给nginx打补丁.

**Comment by gfrankliu** [comment]
nginx版本太低。更新到至少1.9.8

根据 http://nginx.org/en/CHANGES

```
Changes with nginx 1.9.8                                         08 Dec 2015

    *) Feature: pwritev() support.

    *) Feature: the "include" directive inside the "upstream" block.
```

**Comment by xiaokai-wang** [comment]
@devin1982 请更新到nginx-1.9.8+ ，谢谢.
