### ISSUE TITLE
consul_health 的功能什么时候能发RELEASE?

### ISSUE THREAD

**Issue by darren-fu** [weibocom/nginx-upsync-module#208]
@gfrankliu @xiaokai-wang 
consul_health 的功能什么时候能发RELEASE?
目前最新的2.0里没有包含CONSUL健康检查这一功能
期待很久了啊，MASTER可以直接用吗？

**Comment by gfrankliu** [comment]
建议使用MASTER，没有问题。

**Comment by darren-fu** [comment]
ヽ(￣▽￣) 好的，谢谢回复
