### ISSUE TITLE
使用health检测功能，upstream_show 出来的Backend servers 是consul ip + 服务端口

### ISSUE THREAD

**Issue by HaoHappen** [weibocom/nginx-upsync-module#209]
```
upsync consul_ip:8500/v1/health/service/test upsync_timeout=6m upsync_interval=2000ms upsync_type=consul_health strong_dependency=off;
```
upstream_show
```
Upstream name: test; Backend server count: 3
        server consul_ip:1234 weight=1 max_fails=2 fail_timeout=10s;
        server consul_ip:1232 weight=1 max_fails=2 fail_timeout=10s;
        server consul_ip:1231 weight=1 max_fails=2 fail_timeout=10s;
```

**Comment by gfrankliu** [comment]
Maybe @knorby  didn't update "upstream_show" to use the backend server address in display? 
Do you see the actually traffic goes to the correct backend servers?

**Comment by HaoHappen** [comment]
also the wrong  backend servers

**Comment by darren-fu** [comment]
@xiaokai-wang 项目使用SpringCloud完成服务注册，具体调用的Consul API: 
/agent/service/register
``` json
# payload示例
{
  "ID": "redis1",
  "Name": "redis",
  "Tags": [
    "primary",
    "v1"
  ],
  "Address": "127.0.0.1",
  "Port": 8000,
  "EnableTagOverride": false,
  "Check": {
    "DeregisterCriticalServiceAfter": "90m",
    "Args": ["/usr/local/bin/check_redis.py"],
    "HTTP": "http://localhost:5000/health",
    "Interval": "10s",
    "TTL": "15s"
  }
}
```
Consul 注册结果 http://Consul_ip:8500/v1/health/service/service_name

``` json
{
    "Node": {
      "ID": "7ba9c421-9a6e-c3eb-f7a7-2f5a07d50755",
      "Node": "center-test02.com",
      "Address": "consul_ip",
      "Datacenter": "test_env",
      "TaggedAddresses": {
        "lan": "10.168.59.174",
        "wan": "10.168.59.174"
      },
      "Meta": {
      
      },
      "CreateIndex": 2384440,
      "ModifyIndex": 2384446
    },
    "Service": {
      "ID": "service_name-test-10-168-59-157-8074",
      "Service": "service_name",
      "Tags": [
        "group=biz_admin",
        "primary",
        "versions=v1.0.7-RELEASE"
      ],
      "Address": "service_ip",
      "Port": 8074,
      "EnableTagOverride": false,
      "CreateIndex": 2404578,
      "ModifyIndex": 2404578
    },
    "Checks": [  ... ]
}

```

nginx-upsync-module   upstream_show 显示的是 Consul_ip+service的端口，而不是使用service_ip

**Comment by HaoHappen** [comment]
注册consul用的是Java spring cloud，nginx 版本1.11.2。使用的主分支代码
```
    upstream inventory_consul {
        server 127.0.0.1:11111;
        upsync 192.168.1.248:8500/v1/health/service/InventoryCenterServiceTest upsync_timeout=6m upsync_interval=2000ms upsync_type=consul_health strong_dependency=off;
        upsync_dump_path /usr/local/openresty/nginx/conf/servers_test.conf;

        # hash_ketama;
        upsync_lb least_conn;
    }
```

**Comment by gfrankliu** [comment]
Your consul registration seems wrong to me. nginx-upsync-module will only read from consul.

```
{
    "Node": {
      "ID": "7ba9c421-9a6e-c3eb-f7a7-2f5a07d50755",
      "Node": "center-test02.com",
      "Address": "consul_ip",
```

That "Address" should be your Backend service Node address, not consul_ip. You need to fix that first. Otherwise, nginx-upsync-module will only read and use that.

**Comment by darren-fu** [comment]
@gfrankliu  Thanks for your reply!
According to the  consul official document, [consul agent](https://www.consul.io/api/agent.html), it's the Recommended  way to register a service  with agent api.
FYI. [Consul ›Design question: when to register service local vs catalog](https://groups.google.com/forum/#!topic/consul-tool/4EaQofKm_Bc)
I'm pretty sure that `Node` is the meaning of Consul Node, not the service node, so the address of node is the address of consul, not service.
```
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Consul agent running!
           Version: 'v0.7.3'
           Node ID: 'a5c18b55-7adb-09fc-0020-c701eb862513'
         Node name: 'WQ-20161205QDPB'
        Datacenter: 'dc1'
            Server: true (bootstrap: false)
       Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600, RPC: 8400)
      Cluster Addr: 127.0.0.1 (LAN: 8301, WAN: 8302)
    Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false
             Atlas: <disabled>
```
when consul is starting, the consul node has bean created.,you can also see the node with consul ui
http://consul_ip：8500/ui 
---
Am i right? or I misread the consul api document?  Waiting for your answer~

**Comment by gfrankliu** [comment]
In my setup, we run consul agent on every service node, so two IPs are the same.
I guess your consul agent node is somewhere different from the service node. I don't know if that is a recommended way for running consul agent.

I just checked the PR from @knorby https://github.com/weibocom/nginx-upsync-module/pull/183/commits/ca4397b0aef15bc4cc2ae1a4e1815f11961bf1cb . That explicitly says "Pulling the address from the node instead". @knorby is there a reason why you changed from [pulling the Address from the Service](https://github.com/weibocom/nginx-upsync-module/pull/183/commits/26b136aa7223a36d8e0eafc284d90eae23f4b581) to [pulling from Node](https://github.com/weibocom/nginx-upsync-module/pull/183/commits/ca4397b0aef15bc4cc2ae1a4e1815f11961bf1cb)?

**Comment by darren-fu** [comment]
Addditional info [difference-between-consul-service-definition-address-and-service-address](https://stackoverflow.com/questions/40756293/difference-between-consul-service-definition-address-and-service-address)  

> that Address is the address of consul agent and ServiceAddress is the address which is used to access this service. This can be the same addresses, but they can also differ.

**Comment by darren-fu** [comment]
Thanks for the patch, I think it's useful.
I've already used `check_module` in my project, but I really hope `nginx-upsync-module` can deal with this situation in Master code, so we can use this `consul_health` feature in future.

**Comment by gfrankliu** [comment]
I will commit this change to master in a few days if there is no objections.
@knorby @xiaokai-wang , please take a look.

**Comment by xiaokai-wang** [comment]
@gfrankliu OK, please update the readme meanwhile, clarifying how to register consul. make a pr?

**Comment by gfrankliu** [comment]
I don't think there is a need to update readme. This is just a bug fix. 

Based on https://www.consul.io/api/agent/service.html , when a service is registered
```
Address (string: "") - Specifies the address of the service. If not provided, the agent's address is used
```
[This stackoverflow post](https://stackoverflow.com/questions/40756293/difference-between-consul-service-definition-address-and-service-address) also says:
`ServiceAddress: IP address of the service host — if empty, node address should be used`

Before my patch, we always use the agent Node address. After my change, we will use the Service address, and fallback to Node address if Service address is not provided. This is more inline with consul spec.

BTW, in upsync_type=consul_services , we are already doing this. I am just fixing upsync_type=consul_health to behave the same.
