### ISSUE TITLE
什么时候可以支持etcd

### ISSUE THREAD

**Issue by seven-wjx** [weibocom/nginx-upsync-module#21]

**Comment by xiaokai-wang** [comment]
这个要根据后续的计划而定；欢迎提交pr…

**Comment by rrfeng** [comment]
同求，因为已经使用 etcd 了，而且 key 形式这个一样。
本来打算在 openresty 里用 lua 实现一下，看到了 C 的版本很激动。

希望能快点看到。

**Comment by xiaokai-wang** [comment]
感谢各位的关注，我们会在近期支持，请各位继续关注！

**Comment by rrfeng** [comment]
加油！

**Comment by xiaokai-wang** [comment]
already supported etcd, 欢迎试用.

**Comment by rrfeng** [comment]
没有更新到 1.9 branch 吗，我们用的是 openresty

**Comment by xiaokai-wang** [comment]
暂时还没有，你们用的版本很新啊！

**Comment by rrfeng** [comment]
求加油！

**Comment by xiaokai-wang** [comment]
It's a little late, 现在已merge 进nginx-upsync-1.9.x 分支，欢迎试用

Thanks.
