### ISSUE TITLE
摘掉机器长连接还在，会有影响吗？

### ISSUE THREAD

**Issue by scottzzq** [weibocom/nginx-upsync-module#210]
使用upsync动态管理ip之后，摘掉一台机器之后，dump文件中的ip列表已经更新完成，也不会转发流量到这台机器上，但是用netstat命令看连接还在，这个有什么影响吗？ @xiaokai-wang

**Comment by xiaokai-wang** [comment]
@scottzzq 连接还在可能还有未处理完的请求，这个存在连接的时间很长吗？

摘掉之后新的请求不会打到服务器上（摘掉的）.

**Comment by scottzzq** [comment]
@xiaokai-wang  请求肯定是处理完成了，我用client发送请求，1秒发一个，所以不存在请求积压这种情况，我这边观察到的结果是，摘掉之后起码20分钟吧，长连接还是存在的。
