### ISSUE TITLE
upstream被清空

### ISSUE THREAD

**Issue by timopek** [weibocom/nginx-upsync-module#211]
当我有个服务是绑定机器和端口的时候，我把服务从consul里deregister以后，发现upstream里的东西都丢失了，我把服务就算重启了也不行，唯一就是重启nginx一下。

没有deregister之前的upstream如下
server 172.16.4.83:8181 weight=1 max_fails=2 fail_timeout=10s down;
server 172.16.4.83:8181 weight=1 max_fails=2 fail_timeout=10s;
server 172.16.4.82:8181 weight=1 max_fails=2 fail_timeout=10s down;
server 172.16.4.82:8181 weight=1 max_fails=2 fail_timeout=10s;

配置如下：
  upsync 127.0.0.1:8500/v1/health/service/WebappReadwrite  upsync_timeout=6m upsync_interval=500ms upsync_type=consul_health strong_dependency=off;
  upsync_dump_path /home/apps/config/nginx/conf.d/servers/WebappReadwrite.conf;

**Comment by xiaokai-wang** [comment]
只是对consul 做了一个注销server 的操作，相对应的upstream 下的server 列表都没了？怎么判断都没的？

**Comment by timopek** [comment]
现象是/home/apps/config/nginx/conf.d/servers/WebappReadwrite.conf;  这个文件变成空的了。
我们比较特殊的是 server是绑定机器和端口的
