### ISSUE TITLE
使用/v1/catalog/service/XXX接口获取数据，无法正确加载到upstream文件中

### ISSUE THREAD

**Issue by yinyalan** [weibocom/nginx-upsync-module#212]
配置文件里使用如下配置时/data/apps/config/nginx/conf.d/upstreams/demoA.conf中无数据更新：
upsync 127.0.0.1:8500/v1/catalog/service/demoA upsync_timeout=6m upsync_interval=500ms upsync_type=consul_services strong_dependency=off;
upsync_dump_path /data/apps/config/nginx/conf.d/upstreams/demoA.conf;
include  /data/apps/config/nginx/conf.d/upstreams/demoA.conf;

而使用直接curl 127.0.0.1:8500/v1/catalog/service/demoA 是能够从consul获取数据的，配置成如下配置也能正确获取数据：
upsync 127.0.0.1:8500/v1/health/service/demoA upsync_timeout=6m upsync_interval=500ms upsync_type=consul_health strong_dependency=off;
upsync_dump_path /data/apps/config/nginx/conf.d/upstreams/demoA.conf;
include  /data/apps/config/nginx/conf.d/upstreams/demoA.conf;

**Comment by xiaokai-wang** [comment]
upsync_type 更改后就可以了的话；那就是注册server 时与获取时，提取key 不同导致；
