### ISSUE TITLE
某个后端服务无响应时，似乎会导致整个nginx不可用

### ISSUE THREAD

**Issue by wangxr1985** [weibocom/nginx-upsync-module#213]
我们最近安装了upsync模块的nginx遇到好几次相同情况的问题，现象如下：

1.请求的路径为: 用户->公网nginx->内网upsync nginx->后端应用。
2.某个后端应用的所有服务器因访问量突增，负载过高长时间不响应。
3.此时两个nginx accesslog中有大量502错误，而不是504。errorlog中有大量的“no live upstreams while connecting to upstream”错误。
4.公网nginx中的502错误明显多于内网upsync nginx的502，且包括很多其他正常域名。upsync nginx只有异常应用对应域名的502错误。由此推测当时装upsync模块的nginx已经卡住，对所有域名请求都存在长时间不响应的情况，导致公网nginx认为该nginx已经死掉。
5.尝试修改为：用户->公网nginx->其他未安装upsync的nginx->异常的后端应用。该应用仍然因为负载过高一直不响应，但未安装upsync的nginx并没有卡住，其他域名也都正常访问。

这几次遇到问题时，出现问题的域名/应用各不相同，但现象相同。
公网nginx上配置的，未指向到upsync nginx的域名都正常。upsync nginx上配置的域名都受影响，将异常应用改配置到其他未安装upsync模块的nginx后，其他域名均恢复正常，包括切换过去的新nginx上其他域名也都正常，只有那个异常的应用无法访问。
因此我们怀疑只有安装了upsync模块的nginx，在某个后端应用长时间不响应时，会导致整个nginx受到影响。但也不排除是这台安装了upsync模块的nginx负载过高，操作系统原因导致nginx不正常。但出现异常时，我们未在操作系统中发现有其他错误日志。
想咨询下是否有其他人在使用中也遇到类似的问题。

**Comment by xiaokai-wang** [comment]
感谢反馈；麻烦贴一下upstream conf 配置，及使用的模块commit 版本.

**Comment by wangxr1985** [comment]
配置如下

upstream backend_aaa_bbb {
            upsync etcd.xxx.org:2333/v2/keys/operation/ngconf/config/prd/upstream/backend_aaa_bbb upsync_timeout=6m upsync_interval=5000ms upsync_type=etcd strong_dependency=off;
            upsync_dump_path /opt/nginx/conf/upsync-upstream/backend_aaa_bbb.conf;
            include /opt/nginx/conf/upsync-upstream/backend_aaa_bbb.conf;
} 

/opt/nginx/conf/upsync-upstream/backend_aaa_bbb.conf 内容
server 1.1.1.1:9080 weight=1 max_fails=2 fail_timeout=10s;
server 2.2.2.2:9080 weight=1 max_fails=2 fail_timeout=10s;

版本信息如下

commit 586f878b8b9102d19502e1bc5ddd4e5d8c998200

**Comment by xiaokai-wang** [comment]
问题发生时，后端的server 状态都是正常的吗？

**Comment by wangxr1985** [comment]
只有我问题描述里的那个应用，相关的所有server都响应时间长。其他应用状态都正常。问题出现时，所有应用访问都不正常，时好时坏。
