### ISSUE TITLE
编译nginx-upsync-module模块报错

### ISSUE THREAD

**Issue by zhouzhenhua** [weibocom/nginx-upsync-module#217]
**gmake编译遇到的错误**  nginx_upstream_check_module ，nginx-upsync-module一块编译失败，去掉nginx_upstream_check_module正常。
	
objs/addon/src/ngx_http_upsync_module.o: In function `ngx_http_upsync_del_peers':
/data/packages/openresty/openresty-1.13.6.1/../nginx-upsync-module/src/ngx_http_upsync_module.c:1120: undefined reference to `ngx_http_upstream_check_delete_dynamic_peer'
objs/addon/src/ngx_http_upsync_module.o: In function `ngx_http_upsync_add_peers':
/data/packages/openresty/openresty-1.13.6.1/../nginx-upsync-module/src/ngx_http_upsync_module.c:889: undefined reference to `ngx_http_upstream_check_add_dynamic_peer'
collect2: error: ld returned 1 exit status
gmake[2]: *** [objs/nginx] Error 1
gmake[2]: Leaving directory `/data/packages/openresty/openresty-1.13.6.1/build/nginx-1.13.6'
gmake[1]: *** [build] Error 2
gmake[1]: Leaving directory `/data/packages/openresty/openresty-1.13.6.1/build/nginx-1.13.6'
gmake: *** [all] Error 2

**Comment by xiaokai-wang** [comment]
健康检测模块请使用 [nginx_upstream_check_module](https://github.com/xiaokai-wang/nginx_upstream_check_module)
