### ISSUE TITLE
upsync支持slow_start参数吗

### ISSUE THREAD

**Issue by seven-wjx** [weibocom/nginx-upsync-module#219]
server appserv2.example.com:8080 fail_timeout=5s slow_start=30s
slow_start=time
sets the time during which the server will recover its weight from zero to a nominal value, when unhealthy server becomes healthy, or when the server becomes available after a period of time it was considered unavailable. Default value is zero, i.e. slow start is disabled.

作为后端应用预热机制

**Comment by gfrankliu** [comment]
slow_start is only for paid version of nginx.
