### ISSUE TITLE
如何监听Docker容器的启停自动更新Consul KV？

### ISSUE THREAD

**Issue by coverxiaoeye** [weibocom/nginx-upsync-module#22]
nginx-upsync模块会查询Consul KV中的列表，Consul KV中的列表如何根据Docker启停自动更新的呢？weibocom单独开发了模块还是使用第三方工具(比如registrator)？
另外有没有监控Docker的资源状况自动调整server的权重呢？

**Comment by xiaokai-wang** [comment]
1. 这个平台内是通过自己独立的组件把启动的docker注册到consul的；

2. 这个平台正在做相关组件的开发；

**Comment by coverxiaoeye** [comment]
这个独立的组件有没有相关的介绍？有没有开源呢？多谢啦

**Comment by xiaokai-wang** [comment]
这个组件没有开源，暂时没有对外的相关资料，抱歉

**Comment by coverxiaoeye** [comment]
了解了，多谢
