### ISSUE TITLE
建议直接生成upsync_dump_path文件，让初始化更加自动化

### ISSUE THREAD

**Issue by axeon** [weibocom/nginx-upsync-module#223]
在试用nginx-upsync-module，整体感觉不错，有几个建议，请考虑下：
1.如果按照官方readme.MD操作，可能是无法成功的，特别是需要手工创建upsync_dump_path，当微服务数量比较多的时候，这个步骤需要较多时间做调整，为何不用程序直接生成呢？
2.按照官方readme.MD操作，会一直卡在"no servers are inside upstream" 这个错误上，必须手工强行指定一个类似“server 127.0.0.1:8080 weight=1 fail_timeout=8 max_fails=3;”才能启动成功。
3.upsync_dump_path生成的文件中“ weight=1 max_fails=2 fail_timeout=10s;”检测参数，如何配置？

我使用的nginx版本为1.15.2，nginx-upsync-module版本2.1.0。

非常感谢！

**Comment by xiaokai-wang** [comment]
第一个需要确认；第二个需要把真实的server 放到dump 文件里（第一次启动时），这个readme 里应该有介绍；参数的配置与你注册到consul or etcd 时的数据保持一致（如果配置的话）

**Comment by axeon** [comment]
第一个是确定的，需要touch文件，否则报错，这一块完全可以自动创建。
第二个问题，没注意到readme中的介绍，我现在加了一个127.0.0.1:80 down的dummy数据，如果不加更完美。
第三个问题，consul service的health中并没有weight和max_fail的数据啊，可以在upsync指令中指定么？

**Comment by xiaokai-wang** [comment]
貌似是 nginx-1.9.8 之后，nginx upstream配置块下开始支持 include 指令，所以模块针对这个做了一个优化，启动或reload 时不会从 conf-server 拉取最新的server 节点信息（这个会加速启动或者重启），因此第一次用模块的话需要把upstream servers 列表放入dump-file 中，理论上servers 列表只是换了一种包含的方式。

nginx upstream 块下如果没有server，在nginx 启动时会报错，这是nginx 自己的检测机制；个人觉得还是配置上比较好

@gfrankliu 能帮忙回答一下第三个问题吗

**Comment by gfrankliu** [comment]
You can use "tags" when you register the service.
Check examples here: https://github.com/weibocom/nginx-upsync-module/pull/148
