### ISSUE TITLE
求救 。。nginx: [emerg] unknown directive "upsync"     nginx 1.9.2运行不了。。模块安装了

### ISSUE THREAD

**Issue by fulndon** [weibocom/nginx-upsync-module#224]
[root@rabbit conf.d]# /usr/local/nginx/sbin/nginx -V
nginx version: nginx/1.9.2
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC) 
configure arguments: --add-module=/home/fulndon/soft/nginx/nginx_upstream_check_module --add-module=/home/fulndon/soft/nginx/nginx-upsync-module
[root@rabbit conf.d]# 

conf
upstream zuul_server {
        server 127.0.0.1:11111;
        upsync 192.168.56.128:8500/v1/kv/upstreams/zuul?keys=true upsync_timeout=6m upsync_interval=500ms upsync_type=consul strong_dependency=off;
        upsync_dump_path /usr/local/nginx/conf/server/zuul_servers.conf;
        check interval=1000 rise=2 fall=2 timeout=3000 type=http default_down=false;
        check_http_send "HEAD / HTTP/1.0\r\n\r\n";
        check_http_expect_alive http_2xx http_3xx;
}
server{
       listen 18050;
       proxy_pass zuul_server;
       location /nstatus {
        check_status;
        access_log off;
        }
}
~

**Comment by gfrankliu** [comment]
至少要1.9.8以后吧。
能不能试试最新版的nginx?

**Comment by fulndon** [comment]
我试试，，还有一个问题。。就是加上module后执行config命人令时报下面这个错
./configure --add-module=/home/fulndon/soft/nginx/nginx_upstream_check_module --add-module=/home/fulndon/soft/nginx/nginx-upsync-module 

adding module in /home/fulndon/soft/nginx/nginx_upstream_check_module
/home/fulndon/soft/nginx/nginx_upstream_check_module
/home/fulndon/soft/nginx/nginx_upstream_check_module/config: line 10: auto/featu: No such file or directory

**Comment by fulndon** [comment]
我这个module就没有安装成功。。。

**Comment by gfrankliu** [comment]
你下载的源程序有问题。比如你上面说的错：
`No such file or directoryinx_upstream_check_module/config: line 10: auto/featurey`
正确源码第10行应该是 auto/feature

**Comment by fulndon** [comment]
试了最新版的也不行，不知道是不是我环境的问题，，，那个是我复制的有问题，确认了源码没有问题，真心晕。。

**Comment by gfrankliu** [comment]
应该是你的环境问题。

**Comment by crasybest** [comment]
应该是你的环境问题。
