### ISSUE TITLE
 最近在使用upsync模块时，nginx日志中$upstream_addr打印出来是upstream name，而不是upstream的IP地址，出现502错误

### ISSUE THREAD

**Issue by 527593036** [weibocom/nginx-upsync-module#225]
最近在使用upsync模块时，nginx日志中$upstream_addr打印出来是upstream name，而不是upstream的IP地址，因此出现大量的502错误，求解

![image](https://user-images.githubusercontent.com/10548716/44952718-fb695580-aeb8-11e8-80dd-b5985066c21f.png)

nginx版本信息如下：
sbin]# ./nginx -V
nginx version: nginx/1.12.2
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) 
built with OpenSSL 1.0.2k-fips  26 Jan 2017
TLS SNI support enabled
configure arguments: --user=www --group=www --prefix=/usr/local/nginx --with-http_stub_status_module --with-http_ssl_module --with-http_v2_module --with-http_gzip_static_module --with-ipv6 --with-http_sub_module --add-module=/root/src/nginx-upsync/ --add-module=/root/src/nginx-module-vts/ --with-stream

**Comment by xiaokai-wang** [comment]
是dns 解析失败？能贴一下配置信息吗？

**Comment by 527593036** [comment]
日志配置如下
![image](https://user-images.githubusercontent.com/10548716/44957760-45c5f300-af08-11e8-854d-12937e71698b.png)

配置文件如下
upstream vnstory {
        #server 127.0.0.1:11111;
        upsync 10.10.0.124:2379/v2/keys/upstreams/vnstory upsync_timeout=60m upsync_interval=500ms upsync_type=etcd strong_dependency=off;
        upsync_dump_path /usr/local/nginx/conf/server/vnstory.etcd.conf;
        include /usr/local/nginx/conf/server/vnstory.etcd.conf;
        keepalive 10;
}

**Comment by gfrankliu** [comment]
When there is no healthy servers in the upstream, you will get 502 error, and $upstream_addr will show upstream name because nginx has no upstream server IP addresses to send to.

**Comment by 527593036** [comment]
从/usr/local/nginx/conf/server/vnstory.etcd.conf配置文件更新时间看，要早于日志错误产生时间，配置文件没有问题。

**Comment by gfrankliu** [comment]
The timestamp doesn’t matter. Can you cat the file and paste the output
here?

**Comment by jackyliusohu** [comment]
刚测试了一下果然是这样，以下配置
upstream test {
server 127.0.0.1:11111;
upsync 127.0.0.1:8500/v1/kv/upstreams/test upsync_timeout=6m upsync_interval=500ms upsync_type=consul strong_dependency=off;
upsync_dump_path /usr/local/nginx/conf/servers/servers_test.conf;
}

server {
listen 8080;
access_log logs/test.access.log main;
location = / {
proxy_pass http://test;
}
location = /upstream_show {
upstream_show;
}
}

**Comment by jackyliusohu** [comment]
@527593036  我测试consul 版本是没出现这种问题的，你现在问题找到了吗？

**Comment by 527593036** [comment]
@jackyliusohu 没有找到

**Comment by gfrankliu** [comment]
nginx日志中$upstream_addr打印出来是upstream name，而不是upstream的IP地址，原因在于所有IP都无法连接。你应该可以从/usr/local/nginx/conf/server/vnstory.etcd.conf里看到IP和端口。确认一下。

**Comment by zhaowencheng1991** [comment]
此问题解决了吗？我们线上也出现类似的情况。
