### ISSUE TITLE
不支持一致性hash吗(upsync_lb)？ 

### ISSUE THREAD

**Issue by xiaoxiangs** [weibocom/nginx-upsync-module#228]
您好：
     目前upsync支持一致性hash吗？比如基于uri，或者第三方的consistent_hash？
     看见有upsync_lb功能，发现配置不生效(不确定是不是方式不对)，或者提供下upsync_lb的使用方式？ 

nginx 版本: 1.12.2

配置：

    upsync_lb hash;
    hash $arg_userid consistent;

多谢！

**Comment by xiaokai-wang** [comment]
```
upsync_lb hash_ketama;
```

指明hash 的类型，是取模还是一致性哈希

**Comment by xiaoxiangs** [comment]
非常感谢！
