### ISSUE TITLE
不支持nginx -s reload ? 

### ISSUE THREAD

**Issue by imiskolee** [weibocom/nginx-upsync-module#23]
当执行 nginx -s reload 之后.
会发现 旧的nginx worker process 进程已经标记为 shutting down。
新的worker process 也已经成功启动。但是旧的shutting down进行一直存在，没有退出。

>   14 root       0:00 nginx: master process /usr/local/nginx/sbin/nginx
   15 root       0:00 nginx: worker process is shutting down
   16 root       0:00 nginx: worker process is shutting down
   17 root       0:00 nginx: worker process is shutting down
   18 root       0:00 nginx: worker process is shutting down
   32 root       0:00 nginx: worker process is shutting down
   33 root       0:00 nginx: worker process is shutting down
   34 root       0:00 nginx: worker process is shutting down
   35 root       0:00 nginx: worker process is shutting down
   57 root       0:00 nginx: worker process is shutting down
   58 root       0:00 nginx: worker process is shutting down
   59 root       0:00 nginx: worker process is shutting down
   60 root       0:00 nginx: worker process is shutting down
  114 root       0:00 nginx: worker process is shutting down
  115 root       0:00 nginx: worker process is shutting down
  116 root       0:00 nginx: worker process is shutting down
  117 root       0:00 nginx: worker process is shutting down
  123 root       0:00 nginx: worker process is shutting down
  124 root       0:00 nginx: worker process is shutting down
  125 root       0:00 nginx: worker process is shutting down
  126 root       0:00 nginx: worker process is shutting down
  190 root       0:00 nginx: worker process is shutting down
  191 root       0:00 nginx: worker process is shutting down
  192 root       0:00 nginx: worker process is shutting down
  193 root       0:00 nginx: worker process is shutting down
  197 root       0:00 nginx: worker process
  198 root       0:00 nginx: worker process
  199 root       0:00 nginx: worker process
  200 root       0:00 nginx: worker process

**Comment by imiskolee** [comment]
延迟有点长，但还是会自己退出。

**Comment by xiaokai-wang** [comment]
支持reload， 是的；在有请求的情况下，任何时候reload，旧的work 进程都会运行一段时间；

而这个模块耗时长一点是由于与consul 的连接，会保持一段时间；不影响正常处理请求
