### ISSUE TITLE
支持两个upstream同时使用nginx-upsync-module吗

### ISSUE THREAD

**Issue by CaoYusong** [weibocom/nginx-upsync-module#234]
请问支持两个upstream同时使用nginx-upsync-module吗？

第二个upstream一直在报错：：
upstream del peers failed

**Comment by CaoYusong** [comment]
when I use two upstream which all use nginx-upsync-module, an error occur.
and the error is :
 upstream del peers failed
please

**Comment by xiaokai-wang** [comment]
可以的，能把你的配置贴出来吗
