### ISSUE TITLE
nginx-upsync-module-2.1.0 include 语法检测报错

### ISSUE THREAD

**Issue by sxauyhz** [weibocom/nginx-upsync-module#237]
版本：openresty/1.11.2.5，nginx-upsync-module-2.1.0
配置如下：  
  upstream test {
        upsync 127.0.0.1:8500/v1/kv/upstreams/test/ upsync_timeout=6m upsync_interval=500ms upsync_type=consul strong_dependency=off;
        upsync_dump_path /usr/local/nginx/conf/servers/servers_test.conf;
        include /usr/local/nginx/conf/servers/servers_test.conf;
    }
语法检测报错：
nginx: [emerg] open() "/usr/local/nginx/conf/servers/servers_test.conf" failed (2: No such file or directory) in /etc/openresty/nginx/conf/upstream.conf:23
nginx: configuration file/etc/openresty/nginx/conf/nginx.conf test failed

原因未知？是该文件需要手动创建？官方这句提示：（NOTE: recomending strong_dependency is configed off and the first time included file include all the servers.）

**Comment by gfrankliu** [comment]
需要手动创建。空文件应该也行。
要确保nginx用户可以写/更新此文件。

**Comment by sxauyhz** [comment]
@gfrankliu 手动创建就比较悲催了，就非常不方便了。

**Comment by gfrankliu** [comment]
还有个办法就是在include行最后加个星号，

include /usr/local/nginx/conf/servers/servers_test.conf*;

**Comment by gfrankliu** [comment]
```
upstream test {
upsync 127.0.0.1:8500/v1/kv/upstreams/test/ upsync_timeout=6m upsync_interval=500ms upsync_type=consul strong_dependency=off;
upsync_dump_path /usr/local/nginx/conf/servers/servers_test.conf;
#add * at the end to make nginx "include" happy when file doesn't exist.
include /usr/local/nginx/conf/servers/servers_test.conf*;
#dummy server entry to make nginx config check happy
server 127.0.0.1:11111 down;
}
```

**Comment by sxauyhz** [comment]
@gfrankliu 
#add * at the end to make nginx "include" happy when file doesn't exist.
include /usr/local/nginx/conf/servers/servers_test.conf*;
语法检测还是会报错：
sbin/nginx -t
nginx: [emerg] no servers are inside upstream in /etc/nginx/conf/upstream.conf:37

**Comment by gfrankliu** [comment]
Did you add the two lines in my example above for the "dummy server"?
You need to add the dummy server, otherwise you will get error:
`[emerg] no servers are inside upstream`

**Comment by W-BC0001** [comment]
经过测试:

1.**upsync_dump_path 需要提前创建**
2.**upsync_dump_path 如果是空的启动也会报错**, 需要将服务器ip提前写入到 upsync_dump_path 中

例如:

upstream.conf

```shell
upstream test {
        upsync 127.0.0.1:8500/v1/kv/upstreams/test/ upsync_timeout=6m upsync_interval=500ms upsync_type=consul strong_dependency=off;
        upsync_dump_path /tmp/servers/server.conf;

        include /tmp/servers/server.conf;

        keepalive 100;
}
```

还需要以下操作才能正常启动

```shell
# 创建空文件
$ touch /tmp/servers/server.conf

# 空文件nginx语法检测不通过
$ nginx -t
nginx: [emerg] no servers are inside upstream in /usr/local/openresty/nginx/conf/test/127.0.0.1.conf:8
nginx: configuration file /usr/local/openresty/nginx/conf/nginx.conf test failed

# 添加服务器ip(生产环境建议添加真实服务器ip用于备份)
$ echo 'server 127.0.0.1:82 weight=1 max_fails=2 fail_timeout=10s;' > /tmp/servers/server.conf

# nginx语法检测通过
$ nginx -t
nginx: the configuration file /usr/local/openresty/nginx/conf/nginx.conf syntax is ok
nginx: configuration file /usr/local/openresty/nginx/conf/nginx.conf test is successful
```
