### ISSUE TITLE
openresty1.9.7.3 下运行不起来

### ISSUE THREAD

**Issue by krainz** [weibocom/nginx-upsync-module#24]
consul 是可以正常访问的

![qq 20160304212157](https://cloud.githubusercontent.com/assets/2731312/13528140/207167e8-e24f-11e5-8734-091a78e73703.jpg)

在openresty下配置完upsync后，nginx process一直无法启动起来，是什么原因？
![qq 20160304211812](https://cloud.githubusercontent.com/assets/2731312/13528057/c152944e-e24e-11e5-9eba-87f5b0bba61f.jpg)

![qq 20160304212358](https://cloud.githubusercontent.com/assets/2731312/13528191/68e0e968-e24f-11e5-9097-a40d7b2cfe6d.jpg)

**Comment by xiaokai-wang** [comment]
yes，openresty1.9.7.3 基于官方 nginx-1.9.7 版本，nginx-1.8.x 到 nginx-1.9.x 后端的路由节点数据结构发生了变化，而本模块基于nginx-1.8.0 版本开发，所以不兼容；

可以使用分支：https://github.com/weibocom/nginx-upsync-module/tree/nginx-1.9.x-branch ；
此分支兼容 nginx-1.9.x；

nginx-1.9.x 暂时还没有发本稳定版本，请知晓；

**Comment by krainz** [comment]
thx

**Comment by nienie** [comment]
![image](https://cloud.githubusercontent.com/assets/5088904/13624526/fdb241ca-e5e9-11e5-897f-4ca67d8e26f6.png)
用openresy-1.9.7.3 + nginx-upsync-module/nginx-1.9.x-branch编译通不过。

**Comment by xiaokai-wang** [comment]
yes，thanks.

please try again.
