### ISSUE TITLE
nginx: [emerg] upsync_server: conf server port is invalid in  */sdk.conf

### ISSUE THREAD

**Issue by tk1990** [weibocom/nginx-upsync-module#244]
你好，我这里遇到一个问题，咨询下
nginx 配置

upstream sdk {
    server 127.0.0.1:9089;

    upsync 127.0.0.1:8500/v1/catalog/service/yzb-sdk-gateway  upsync_timeout=6m upsync_interval=500ms upsync_type=consul strong_dependency=off;
#    upsync_dump_path /usr/local/etc/nginx/vhost/servers_test.conf;
}
server {
        listen       81;
        server_name  127.0.0.1;
        #charset koi8-r;
        access_log  /usr/local/etc/nginx/logs/host.access.log  ;
        error_log  /usr/local/etc/nginx/logs/error.access.log  ;

        location / {
           proxy_pass http://sdk;
        }
         location = /upstream_show {
            upstream_show;
        }

        location = /upstream_status {
            check_status;
            access_log off;
        }
    }

通过http://127.0.0.1:8500/v1/catalog/service/yzb-sdk-gateway 获取的负载信息为：
[{"ID":"ec58e429-bea5-c6b5-28bc-a54088253a40","Node":"consul-server01","Address":"127.0.0.1","Datacenter":"dc1","TaggedAddresses":{"lan":"127.0.0.1","wan":"127.0.0.1"},"NodeMeta":{"consul-network-segment":""},"ServiceKind":"","ServiceID":"sdk-gateway-10.222.96.10:9088","ServiceName":"yzb-sdk-gateway","ServiceTags":["test"],"ServiceAddress":"10.222.96.10","ServiceWeights":{"Passing":1,"Warning":1},"ServiceMeta":{"version":"1.0"},"ServicePort":9088,"ServiceEnableTagOverride":false,"ServiceProxyDestination":"","ServiceProxy":{},"ServiceConnect":{},"CreateIndex":29602,"ModifyIndex":29653}]

现在启动nginx 报错为：
nginx: [emerg] upsync_server: conf server port is invalid in /usr/local/etc/nginx/vhost/sdk.conf:5 
也就是upsync这行，辛苦帮分析下什么问题，谢谢

**Comment by gfrankliu** [comment]
upsync_type is wrong in your case. it should be
upsync_type=consul_services

**Comment by tk1990** [comment]
> upsync_type is wrong in your case. it should be
> upsync_type=consul_services

Thank you, but if i set upsync_type=consul_services ， another error showed like below : 
nginx: [emerg] upsync_server: upsync_type invalid para in /usr/local/etc/nginx/vhost/sdk.conf:4

**Comment by gfrankliu** [comment]
Double check your config file, make sure you didn't make a typo:
upsync_type=consul_services
Please post your full configuration.

**Comment by tk1990** [comment]
> Double check your config file, make sure you didn't make a typo:
> upsync_type=consul_services
> Please post your full configuration.

upstream sdk {
    server 127.0.0.1:9089;
#    upsync 127.0.0.1:8500/v1/agent/service/SDK_GATEWAY-10.222.96.10  upsync_timeout=6m upsync_interval=500ms upsync_type=consul strong_dependency=off;
    upsync 127.0.0.1:8500/v1/catalog/service/yzb-sdk-gateway  upsync_timeout=6m upsync_interval=500ms upsync_type=consul_services  strong_dependency=off;
#    upsync  http://127.0.0.1:8500/v1/agent/service/SDK_GATEWAY-10.222.96.10  upsync_timeout=6m upsync_interval=500ms upsync_type=consul strong_dependency=off;
#    upsync_dump_path /usr/local/etc/nginx/vhost/servers_test.conf;
}
server {
        listen       81;
        server_name  127.0.0.1;
        #charset koi8-r;
        access_log  /usr/local/etc/nginx/logs/host.access.log  ;
        error_log  /usr/local/etc/nginx/logs/error.access.log  ;

        location / {
           proxy_pass http://sdk;
        }
         location = /upstream_show {
            upstream_show;
        }

        location = /upstream_status {
            check_status;
            access_log off;
        }
    }

thank you !

**Comment by tk1990** [comment]
> Double check your config file, make sure you didn't make a typo:
> upsync_type=consul_services
> Please post your full configuration.

upstream sdk {
    server 127.0.0.1:9089;
    upsync 127.0.0.1:8500/v1/catalog/service/yzb-sdk-gateway  upsync_timeout=6m upsync_interval=500ms upsync_type=consul_services  strong_dependency=off;
}
server {
        listen       81;
        server_name  127.0.0.1;
        #charset koi8-r;
        access_log  /usr/local/etc/nginx/logs/host.access.log  ;
        error_log  /usr/local/etc/nginx/logs/error.access.log  ;

        location / {
           proxy_pass http://sdk;
        }
         location = /upstream_show {
            upstream_show;
        }

        location = /upstream_status {
            check_status;
            access_log off;
        }
    }

thanks!

**Comment by gfrankliu** [comment]
I put your config in my nginx and the "configtest" shows fine without errors.
I can only get your error if I change the upsync_type to a typo, eg:
upsync_type=consul_service (without s at the end)
now the error:
upsync_server: upsync_type invalid para in ...
