### ISSUE TITLE
upsync重复向consul拉取serice列表

### ISSUE THREAD

**Issue by tingzhou85** [weibocom/nginx-upsync-module#245]
upstream配置：
upstream metis {
    least_conn;
    keepalive 100;
    upsync consul:8500/v1/health/service/test upsync_timeout=10m upsync_interval=2m upsync_type=consul strong_dependency=off;
    upsync_dump_path /opt/nginx/conf/upstreams_managed/test.conf;
    upsync_lb least_conn;
    include /opt/nginx/conf/upstreams_managed/test.conf;
}
实际观察下来，2分钟的间隔里，nginx一共向consul服务器发送了16次http请求。
nginx服务器是16核的，所以怀疑upstream里的upsync操作，是worker级别的吗？
如果nginx服务器的worker数量是16，每个upsync_interval里面，upsync都会被调用16次

**Comment by tpwow** [comment]
是worker级别的
