### ISSUE TITLE
nginx shutting down  

### ISSUE THREAD

**Issue by jackyliusohu** [weibocom/nginx-upsync-module#249]
您好：
           使用nginx-upsync-module  当动态修改upstream ip 列表时，他有shutting down 机制吗，如果没shutting down 机制，如果老连接在上传东西或者时间较长的链接， 这时是怎么处理的。

**Comment by xiaokai-wang** [comment]
@jackyliusohu 被更新的upstream 不会再接新的请求，当没有请求在处理后，会定时清楚掉.
