### ISSUE TITLE
有计划支持解析 upstream 里的 hostname 吗

### ISSUE THREAD

**Issue by everpcpc** [weibocom/nginx-upsync-module#25]
比如 `/v1/kv/upstreams/example/www.example.com:80` 这样的。

看从 consul 里拿 upstream 的时候会检查是否是 ip 地址，否则就返回 invalid 了。

**Comment by xiaokai-wang** [comment]
支持域名的目的是什么？如果是为了实现动态解析的目的就不需要了，tengine 有个动态解析域名的模块，或者借用proxy_pass...

**Comment by everpcpc** [comment]
主要是为了可读性，因为我们内部都是用 hostname 来标示机器的，就不需要先解析一下再写 consul 了。
看 dyups 是直接用的 `ngx_conf_parse` 来验证的，不知道成本怎么样。

**Comment by everpcpc** [comment]
另外，弱弱问一句，weibo 内部对于 consul 的 token 是怎么处理的？看这个 module 好像没有考虑单独用 token 的情况。

**Comment by xiaokai-wang** [comment]
1. 加入成本有限；可是如果用域名，我有点困惑，怎么动态的更新？consul 的作用是什么？

2. token 是第三方写入用的，读暂时没用.
