### ISSUE TITLE
高版本nginx编译报错

### ISSUE THREAD

**Issue by hanzixiaoshu** [weibocom/nginx-upsync-module#257]
nginx1.16编译是报错： error: conflicting types for ‘ngx_strnlen’，提示此类型冲突。
nginx1.13没有问题

**Comment by xiaokai-wang** [comment]
@hanzixiaoshu 帮忙修复一下？

**Comment by hanzixiaoshu** [comment]
> @hanzixiaoshu 帮忙修复一下？

没看过源码，不懂怎么改

**Comment by hanzixiaoshu** [comment]
你也遇到了吗？

**Comment by hanzixiaoshu** [comment]
> @hanzixiaoshu 帮忙修复一下？
我将/nginx-upsync-module-master/src/ngx_http_upsync_module.c文件中的ngx_strnlen函数改成了ngx_strnlens，编译的时候没有报错，但是不确定使用upsync功能的时候会不会有问题？
另外，我看了一下新版本的nginx，高版本nginx中内部封装了ngx_strnlen函数，所以编译的时候导致冲突。
这种处理方法不知是否有问题？
![image](https://user-images.githubusercontent.com/12489036/62760826-8edadb80-bab7-11e9-9130-8df6071dac12.png)

**Comment by hanzixiaoshu** [comment]
抱歉，可能是我版本太老了，我看github上最新的已经由ngx_strnlen改为ngx_http_upsync_strnlen了
