### ISSUE TITLE
upsync指令支持自定义类型吗？? ?

### ISSUE THREAD

**Issue by wanglin90** [weibocom/nginx-upsync-module#263]
文档上描述upsync指令目前支持consul、etcd。

- 从upsync的配置 “upsync $consul/etcd.api.com:$port/v1/kv/upstream/$upstream_name ” 上看，使用的是http协议，/v1/kv/upstream 是consul提供的http接口。

- 那么，如果upsync指令后面配置的是自定义的http服务可以吗？比如 “upsync $myapp.api.com:$port/v1/kv/upstream/test ”，/v1/kv/upstream/test 是我们自己应用提供的http接口，不使用consul/etcd的可以吗？

**Comment by xiaokai-wang** [comment]
@wanglin90 不可以的，除非你的服务和consul/etcd 的协议一致（返回的内容格式）等

**Comment by wanglin90** [comment]
> @wanglin90 不可以的，除非你的服务和consul/etcd 的协议一致（返回的内容格式）等

1，通过抓包发现consul返回的数据格式如下：
     `[{"LockIndex":0,"Key":"","Flags":0,"Value":"","CreateIndex":5517,"ModifyIndex":18218}]`

2，自己写一个http服务，返回的数据格式跟consul返回的一样时：
     发现upsync 指令可以定时轮询，但是不会更新dump文件里的信息。这是还涉及到其它协议吗？

**Comment by xiaokai-wang** [comment]
upsync 用的是long polling，目的是consul/etcd 有任何更新，可以及时的进行nginx 后端server 的更新; long polling 会有一个超时时间设置，会定期的关闭链接然后重新连consul/etcd.

为什么要自己写呢

**Comment by wanglin90** [comment]
嗯嗯，明白了，从抓包上看确实是hang住6min后重连consul的，我们的场景是想用自己的配置中心替代consul/etcd这种组件，然后在upsync和配置中心之间增加一个应用层，提供http服务。
