### ISSUE TITLE
upsync不支持主机名称吗？

### ISSUE THREAD

**Issue by gongwenbin** [weibocom/nginx-upsync-module#264]
Hi，您好！
  请问在consul，key配置为主机名称而不是IP地址，upsync是不是就不支持了，看nginx日志报2019/10/14 15:49:39 [error] 28106#0: upsync_check_key: invalid ip in /test-test.test.com:8080有什么方法吗？
2、curl -s http://test.test.com:8500/v1/kv/upstreams_test/test/192.168.0.1:8080  返回的json中value怎么解码？

**Comment by xiaokai-wang** [comment]
支持域名的

**Comment by gongwenbin** [comment]
nginx version: nginx/1.14.2
[error] 10896#0: upsync_check_key: invalid ip in /test.test.com:8080
是不是这个版本的nginx不支持呢？

**Comment by gfrankliu** [comment]
日志来自
https://github.com/weibocom/nginx-upsync-module/blob/master/src/ngx_http_upsync_module.c#L2037

可能是主机名有一个斜杠
 /test.test.com

**Comment by gongwenbin** [comment]
主机名称前面没有斜杠，就算有的upstream都写IP，也会报以下错误：
2019/11/12 20:57:11 [error] 3308#0: upsync_check_key: has no port in /

**Comment by gfrankliu** [comment]
Please post your nginx config and consul raw output from the kv.

**Comment by gongwenbin** [comment]
[www@mock-test upstream]$ curl http://sdb-main.test.com:8500/v1/kv/upstreams/mockspider?recurse
[{"LockIndex":0,"Key":"upstreams/mockspider/","Flags":0,"Value":null,"CreateIndex":488727,"ModifyIndex":488727},{"LockIndex":0,"Key":"upstreams/mockspider/10.240.4.180:8080","Flags":0,"Value":"eyJ3ZWlnaHQiOiAxMCwgIm1heF9mYWlscyI6IDIsICJmYWlsX3RpbWVvdXQiOiAxMCwgImRvd24iOiAwfQ==","CreateIndex":488729,"ModifyIndex":488791},{"LockIndex":0,"Key":"upstreams/mockspider/dzgj-test.test.com:8080","Flags":0,"Value":"eyJ3ZWlnaHQiOiAxMCwgIm1heF9mYWlscyI6IDIsICJmYWlsX3RpbWVvdXQiOiAxMCwgImRvd24iOiAwfQ==","CreateIndex":488732,"ModifyIndex":488793}]

nginx-config
upstream mockspider {
    server 127.0.0.1:11111;
    upsync sdb-main.test.com:8500/v1/kv/upstreams/mockspider upsync_timeout=6m upsync_interval=500ms upsync_type=consul strong_dependency=off;
    upsync_dump_path /usr/local/nginx/conf/upstream/mockspider.conf;
}

nginx-error.log
2019/11/17 09:29:17 [notice] 30948#0: upsync_dump_server: dump conf file /usr/local/nginx/conf/upstream/mockspider.conf succeeded, number of servers is 1
2019/11/17 09:29:17 [error] 30946#0: upsync_check_key: has no port in /
2019/11/17 09:29:17 [error] 30946#0: upsync_check_key: invalid ip in /dzgj-test.test.com:8080

**Comment by gfrankliu** [comment]
日志中的错误信息来自：
https://github.com/weibocom/nginx-upsync-module/blob/master/src/ngx_http_upsync_module.c#L2037

的确是只支持IP地址：
https://github.com/weibocom/nginx-upsync-module/blob/master/src/ngx_http_upsync_module.c#L2035
域名会报错：
```
if (ngx_inet_addr(ip_p, port_p - ip_p) == INADDR_NONE) {
```

@xiaokai-wang ^
