### ISSUE TITLE
 [WARN] upsync_timeout: timed out reading upsync_server: 172.17.6.208:8500

### ISSUE THREAD

**Issue by fangjianfeng** [weibocom/nginx-upsync-module#268]
问题：upsync功能正常，但是nginx error.log一直报超时的error

环境和配置：
1.nginx-upsync-module版本：2019-10-22 18:12拉取的最新版仓库：git clone https://github.com/weibocom/nginx-upsync-module.git 
2.consul配置：172.17.6.208:8500是一台client，服务没问题；
3.upstream配置
![image](https://user-images.githubusercontent.com/19743705/67353719-d84ea900-f585-11e9-885d-af6dfc652277.png)
4.当前server列表
![image](https://user-images.githubusercontent.com/19743705/67353773-ffa57600-f585-11e9-9475-9604ca50fe67.png)
5.执行更新正常
![image](https://user-images.githubusercontent.com/19743705/67354472-c53cd880-f587-11e9-8b7d-666110af488b.png)

异常日志：
每隔upsync_timeout=5s  +  upsync_interval=20s，就会报一次
![image](https://user-images.githubusercontent.com/19743705/67354113-d507ed00-f586-11e9-85aa-5c1ef92974f9.png)

**Comment by fangjianfeng** [comment]
回退版本得到解决。

上述测试是clone的最新仓编译的(刚好merge了一个request)，回退到v2.1.0正常了

**Comment by fangjianfeng** [comment]
回退版本解决

**Comment by gfrankliu** [comment]
我测试了clone最新仓编译，没看到你说的异常日志。
是不是你的网络正好有问题？能否再试试？

**Comment by unixchina** [comment]
我的最新版本也有这个错误日志，我确定网络没有问题

**Comment by unixchina** [comment]
> 
我 用这个版本也还有这个日志..

**Comment by unixchina** [comment]
> 回退版本得到解决。
> 
> 上述测试是clone的最新仓编译的(刚好merge了一个request)，回退到v2.1.0正常了

我 用这个版本也还有这个日志..
