### ISSUE TITLE
使用nginx1.16.1版本，stream模块里调用upsync "upsync" directive is not allowed

### ISSUE THREAD

**Issue by sophie0000** [weibocom/nginx-upsync-module#274]
使用nginx1.16.1版本，有一个tcp连接配置 在stream模块里 增加
 upstream backend_xx_xx_tcp {

            upsync xx-xx-xx-lvs.xx.org:2335/v2/keys/xx/xx/ngconf/config/prd/upstream/backend_xx_xx_tcp upsync_timeout=6m upsync_interval=5000ms upsync_type=etcd strong_dependency=off;
            upsync_dump_path /opt/xx/xx/conf/upsync-upstream/backend_xx_xx_tcp.conf;
            include /opt/xx/xx/conf/upsync-upstream/backend_xx_xx_tcp.conf;
    }

nginx reload 的时候报以下错误 1.12版本没有这个问题呢
"upsync" directive is not allowed here in nginx.conf

**Comment by xiaokai-wang** [comment]
stream 相关配置请使用[nginx-stream-upsync-module](https://github.com/xiaokai-wang/nginx-stream-upsync-module)模块
