### ISSUE TITLE
openresty编译出错，求解

### ISSUE THREAD

**Issue by 527593036** [weibocom/nginx-upsync-module#275]
1、环境
系统： centos7
openresty版本： openresty-1.15.8.2
nginx_upstream_check_module版本： check_1.12.1+.patch，check_1.14.0+.patch， check_1.16.1+.patch

2、编译流程
cd openresty-1.15.8.2/bundle/nginx-1.15.8/
patch -p1 < ../../../nginx_upstream_check_module/check_1.14.0+.patch #分别测试了3个补丁

./configure --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-ld-opt="-L/usr/local/lib/" --with-cc-opt="-L/usr/local/include/" --add-module=../nginx-module-vts --add-module=../nginx_upstream_check_module --add-module=../nginx-upsync-module

编译出错：
![image](https://user-images.githubusercontent.com/10548716/69809795-6c66fc80-1225-11ea-875f-ae6a9aa3a51a.png)

**Comment by bubbleatgit** [comment]
要用这个module，不能用原来yaoweibin的。

https://github.com/xiaokai-wang/nginx_upstream_check_module

**Comment by 527593036** [comment]
> 要用这个module，不能用原来yaoweibin的。
> 
> https://github.com/xiaokai-wang/nginx_upstream_check_module

非常感谢
