### ISSUE TITLE
Starting a server with node backup=1 means crash

### ISSUE THREAD

**Issue by CallMeFoxie** [weibocom/nginx-upsync-module#29]
Hi,
we've found also one crash during startup - when any upstream is set as backup=1 it will make the upsync module crash.

The reason is simple:
in ngx_http_upsync_add_peers, there is
if (server->backup) { continue; }
which means that when ngx_http_upsync_del_peers runs, it will crash on
 if (ngx_memn2cmp((u_char *) tmp_peers->peer[i].sockaddr, (u_char *) server->addrs->sockaddr, len, len)
as the parameters are 0/NULL.

The easiest fix is to just ignore the backup parameter (and comment out the continue;). I have tried reading the official source for nginx upstream RR balancing, but I have no idea how backup nodes are supposed to behave so I am not sure of the proper fix.

Sorry, I speak only English.

**Comment by xiaokai-wang** [comment]
The attribute of backup is not supported now, maybe will be supported later.

is that necessary? you can sync upstreams from conf server and easily add/del backend server.

**Comment by CallMeFoxie** [comment]
Commenting the if (server->backup) { continue; } would probably do the trick for now and keeping the servers all in -- otherwise the thread crashes, respawns, crashes, respawns ad infinium.  We have taken care of that in our management interface but others might run into the same issue meanwhile.

**Comment by xiaokai-wang** [comment]
really trick and a bug, a pr?please

last pr be merged, thanks.

**Comment by xiaokai-wang** [comment]
thanks @CallMeFoxie .
