### ISSUE TITLE
如果直接支持k8s的etcd的service的endpoint的格式会怎么样

### ISSUE THREAD

**Issue by seven-wjx** [weibocom/nginx-upsync-module#32]
nginx直接获取endpoints，生成upstreams
etcdctl get /registry/services/endpoints/default/open-falcon|python -m json.tool
{
    "apiVersion": "v1",
    "kind": "Endpoints",
    "metadata": {
        "creationTimestamp": "2016-03-11T13:48:08Z",
        "labels": {
            "open-falcon/cluster-service": "true",
            "open-falcon/name": "open-falcon"
        },
        "name": "open-falcon",
        "namespace": "default",
        "resourceVersion": "340988",
        "selfLink": "/api/v1/namespaces/default/endpoints/open-falcon",
        "uid": "e32bfea2-e78f-11e5-9b7d-ecf4bbdfa200"
    },
    "subsets": [
        {
            "addresses": [
                {
                    "ip": "10.10.10.10",
                    "targetRef": {
                        "kind": "Pod",
                        "name": "open-falcon-wzute",
                        "namespace": "default",
                        "resourceVersion": "341001",
                        "uid": "ca602bf5-e78f-11e5-9b7d-ecf4bbdfa200"
                    }
                }
            ],
            "ports": [
                {
                    "name": "open-falcon",
                    "port": 6030,
                    "protocol": "TCP"
                }
            ]
        }
    ]
}

**Comment by xiaokai-wang** [comment]
支持是没有任何问题的，只是想着一种更通用的方式，这种方式是正确的姿势？

**Comment by jolestar** [comment]
这种挺好 可以挂在k8s外面做负载均衡

**Comment by seven-wjx** [comment]
如果实现了容器独立ip, 并且外部可直接访问，这种nginx可以作为外部的负载均衡
如果k8s是sdn的网络，并且nginx也放在k8s的容器里，nginx可以替代kube-proxy作为负载均衡

**Comment by CaesarC** [comment]
期待更新，类似confd可以用temlate的功能，这样可以获取etcd特殊的endpoint格式

**Comment by seven-wjx** [comment]
> 期待更新，类似confd可以用temlate的功能，这样可以获取etcd特殊的endpoint格式

可以在容器实例中使用sidecar注册到consul里
