### ISSUE TITLE
how to add/tuning backup of an upstream

### ISSUE THREAD

**Issue by jpuyy** [weibocom/nginx-upsync-module#38]
```curl -XPUT -d value='{"weight":1, "max_fails":2, "fail_timeout":8, "backup":1}' http://192.168.2.111:4001/v2/keys/upstreams/api_module/192.168.2.12:80```
```curl -XPUT -d value='{"weight":1, "max_fails":2, "fail_timeout":8, "backup":0}' http://192.168.2.111:4001/v2/keys/upstreams/api_module/192.168.2.12:80```

not working

**Comment by xiaokai-wang** [comment]
sorry, the attribute of backup is not supported now.

**Comment by xiaokai-wang** [comment]
Is that necessary In production environment？
