### ISSUE TITLE
tengine master版本编译不同通过

### ISSUE THREAD

**Issue by saga1015** [weibocom/nginx-upsync-module#39]
大拿，此模块在tengine master下编译不通过，报错如下
        -L/opt/websuite/tengine/lib -Wl,-E -lpthread -ldl -lcrypt -L/opt/websuite/tengine/lib -lluajit-5.1 -lm -ldl -lm ../pcre-8.36/.libs/libpcre.a -lssl -lcrypto -ldl -lz -lgd -ljemalloc
objs/addon/src/ngx_http_upsync_module.o: In function `ngx_http_upsync_least_conn_init':
/root/source/tengine/nginx-upsync-module/src/ngx_http_upsync_module.h:120: undefined reference to `ngx_http_upstream_least_conn_module'
objs/addon/src/ngx_http_upsync_module.o: In function `ngx_http_upsync_del_peer_least_conn':
/root/source/tengine/nginx-upsync-module/src/ngx_http_upsync_module.h:157: undefined reference to `ngx_http_upstream_least_conn_module'
collect2: ld 返回 1
make[1]: *** [objs/nginx] 错误 1
make[1]: Leaving directory `/root/source/tengine/src/tengine'
make: *** [build] 错误 2

请大拿协助呀

**Comment by xiaokai-wang** [comment]
tengine master + nginx-upsync-module master 并没有复现这个问题，请再试一下

你的./configure 后参数是什么？

**Comment by saga1015** [comment]
./configure --prefix=/opt/websuite/tengine \
--conf-path=/opt/config/tengine/nginx.conf \
--error-log-path=/opt/logs/tengine/error.log \
--http-log-path=/opt/logs/tengine/access.log \
--pid-path=/opt/run/tengine \
--user=websuite \
--group=websuite \
--dso-path=/opt/websuite/tengine/modules \
--without-select_module \
--without-poll_module \
--with-file-aio \
--with-http_v2_module \
--with-http_realip_module \
--with-http_gzip_static_module \
--with-http_auth_request_module \
--with-http_addition_module=shared \
--with-http_image_filter_module=shared \
--with-http_geoip_module=shared \
--with-http_concat_module=shared \
--with-http_random_index_module=shared \
--with-http_secure_link_module=shared \
--with-http_sysguard_module=shared \
--with-http_charset_filter_module=shared \
--with-http_userid_filter_module=shared \
--with-http_footer_filter_module=shared \
--with-http_trim_filter_module=shared \
--with-http_access_module=shared \
--with-http_autoindex_module=shared \
--with-http_map_module=shared \
--with-http_referer_module=shared \
--with-http_fastcgi_module=shared \
--with-http_uwsgi_module=shared \
--with-http_scgi_module=shared \
--with-http_empty_gif_module=shared \
--with-http_limit_conn_module=shared \
--with-http_limit_req_module=shared \
--with-http_reqstat_module=shared \
--with-http_browser_module=shared \
--with-http_user_agent_module=shared \
--with-http_upstream_session_sticky_module=shared \
--with-http_upstream_ip_hash_module=shared \
--with-http_upstream_least_conn_module=shared \
--without-http_ssi_module \
--without-http_split_clients_module \
--without-http_memcached_module \
--with-http_tfs_module=shared \
--with-libyajl-inc=/opt/websuite/tengine/include/yajl \
--with-libyajl-lib=/opt/websuite/tengine/lib \
--with-luajit-inc=/opt/websuite/tengine/include/luajit-2.1 \
--with-luajit-lib=/opt/websuite/tengine/lib \
--http-client-body-temp-path=/opt/websuite/tengine/cache/client_temp \
--http-proxy-temp-path=/opt/websuite/tengine/cache/proxy_temp \
--http-fastcgi-temp-path=/opt/websuite/tengine/cache/fastcgi_temp \
--http-uwsgi-temp-path=/opt/websuite/tengine/cache/uwsgi_temp \
--http-scgi-temp-path=/opt/websuite/tengine/cache/scgi_temp \
--without-mail_pop3_module \
--without-mail_imap_module \
--without-mail_smtp_module \
--with-pcre=../pcre-8.36 \
--with-pcre-opt=-fPIC \
--with-pcre-jit \
--with-jemalloc \
--with-cc-opt='-w -pipe -march=native -mtune=native -m128bit-long-double -m64 -fno-builtin-malloc' \
--add-module=/root/source/tengine/echo-nginx-module \
--add-module=/root/source/tengine/headers-more-nginx-module \
--add-module=/root/source/tengine/memc-nginx-module \
--add-module=/root/source/tengine/nginx-module-vts \
--add-module=/root/source/tengine/ngx_cache_purge \
--add-module=/root/source/tengine/ngx_devel_kit \
--add-module=/root/source/tengine/redis2-nginx-module \
--add-module=/root/source/tengine/set-misc-nginx-module \
--add-module=/root/source/tengine/srcache-nginx-module \
--add-module=/root/source/tengine/nginx-hmux-module \
--add-module=/root/source/tengine/lua-nginx-module \
--add-module=/root/source/tengine/lua-upstream-nginx-module \
--add-module=/root/source/tengine/testcookie-nginx-module \
--add-module=/root/source/tengine/nginx-upsync-module
这是我们编译的参数

**Comment by xiaokai-wang** [comment]
'--with-http_upstream_least_conn_module=shared ' 加shared 的目的是什么？用动态编译有什么特殊的考量么？

**Comment by saga1015** [comment]
其实这个模块我们用不到，所以作为动态加载的模块，不会是需要编译成静态模块才行吧

**Comment by xiaokai-wang** [comment]
既然不用何必编译进去；有些模块默认会编译进去的，静态编译进去就是占用些空间，速度比动态的还要快些吧

shared 是tengine 加进去的，官方并不支持

**Comment by gfrankliu** [comment]
官方1.9.11开始也支持动态模块了：http://nginx.org/en/CHANGES

**Comment by xiaokai-wang** [comment]
嗯啊，有主意到官方的这个变动

动态的添加模块，它的应用场景我现在还不是很清楚，但是一个模块如果没有什么问题，也不需要频繁的变动，是没有必要做成动态的吧

这一块有待进一步了解，多谢！
