### ISSUE TITLE
the compatible problem of nginx-upsync-module with nginx_upstream_check_module 

### ISSUE THREAD

**Issue by xiaokai-wang** [weibocom/nginx-upsync-module#4]
nginx-upsync-module supports health check of dynamicly adding backend servers with nginx_upstream_check_module, needs dynamicly operating interface of nginx_upstream_check_module.

but newly ngx_http_upstream_check_module.c file not update to  nginx_upstream_check_module.git, so you need to use 'https://github.com/alibaba/tengine/blob/master/src/http/ngx_http_upstream_check_module.c' replace 'https://github.com/yaoweibin/nginx_upstream_check_module/blob/master/ngx_http_upstream_check_module.c'. 

thanks

**Comment by triumph** [comment]
按照上面的替换之后 ，编译还是出错，错误如下

![qq 20151211095106](https://cloud.githubusercontent.com/assets/11950/11733840/be1f476c-9fec-11e5-8a3f-ce4e6e458aa8.jpg)
