### ISSUE TITLE
建议：使用ngx_conf_parse来解析所有配置

### ISSUE THREAD

**Issue by davidwudv** [weibocom/nginx-upsync-module#41]
你好！
我阅读了源码，发现你们是自己在解析upstream里的每一项配置的，例如peer里的weight等等....最近还加了lb配置....我觉得其实没有必要这样做，使用nginx原有的配置解析机制来解析就一劳永逸了，否则每一项配置都自己解析、设置各个字段太蛋疼了，以后还要跟着nginx的步伐支持新配置。

这是可以做到的，这部分功能我已经实现过了。
参考一下upstream模块的配置解析函数即可。

**Comment by xiaokai-wang** [comment]
这一部分是解析dump file的配置，不符合ngx_conf_parse 接口规范，不过这部分确实可以优化，欢迎各种建议
