### ISSUE TITLE
链接共享

### ISSUE THREAD

**Issue by gfrankliu** [weibocom/nginx-upsync-module#43]
目前upsync是定义在upstream里，这是否意味着如果我有几万个upstream，nginx在同一时刻会有几万个链接到consul？是否有什么方法可以让所有的upstream共享一个或几个链接到consul？这会节省很多资源。

**Comment by xiaokai-wang** [comment]
是的，理论上是这样子的

让所有的upstream共享一个或几个这个有点困难，毕竟nginx 的更新是以upstream 为单位的

理论上nginx 集群都会以业务为单位或者以nginx 的承载力来看，几万个upstream 的情况是没有的
