### ISSUE TITLE
delayed upsync

### ISSUE THREAD

**Issue by gfrankliu** [weibocom/nginx-upsync-module#45]
Is it possible to add a flag to support delayed upsync?
If you have lots of upstream defined but only a few having traffic at a time, it doesn't make sense for every upstream to upsync against consul with numerous connections. We can do upsync only when there are traffic for the upstream. I think this is how jdomain is doing: https://github.com/wdaike/ngx_upstream_jdomain

**Comment by xiaokai-wang** [comment]
I think that is not necessary.

If your upstream has no traffic or is not much traffic, it needn't to configure upsync. If your backend servers is often changed or your upstream has a heavy traffic at a time and another time is little , need to scale or reduce backend servers, that is perfection choice for upsync.

What do you think?
