### ISSUE TITLE
allow show all upstreams

### ISSUE THREAD

**Issue by gfrankliu** [weibocom/nginx-upsync-module#46]
Is it possible to let upstream_show to list all upstreams? 
Currently if I don't specify one, I will get
```
Please input specific upstream name
```

**Comment by xiaokai-wang** [comment]
of course.

Can you make a pr? please, if you are interested.

Thanks.

**Comment by gfrankliu** [comment]
Can this be merged into nginx-1.9.x-branch? 
By the way, when will nginx-1.9.x-branch be merged back into master?

**Comment by xiaokai-wang** [comment]
nginx-1.9.x will not be merged into master for the present.

**Comment by CallMeFoxie** [comment]
It should be possible to cherry pick this commit via git, just as well any other possible commit.

**Comment by gfrankliu** [comment]
@CallMeFoxie I just got a chance to try this with nginx 1.8.1. With default nginx.conf and no upstream defined, I got those errors when checking status:

```
2016/04/07 23:29:57 [alert] 44998#0: *2 zero size buf in writer t:1 r:0 f:0 00000001079BC000 00000001079BC000-00000001079BC000 0000000000000000 0-0, client: 127.0.0.1, server: localhost, request: "GET /upstream HTTP/1.1", host: "localhost:9080"
```
Should I get something else "no upstream defined"?
