### ISSUE TITLE
Future for Nodes Managing

### ISSUE THREAD

**Issue by luxuan** [weibocom/nginx-upsync-module#47]
Hi ,@xaikai, as we know, nginx cluster servers for different services in the production, we may only config one or limitted upstreams at the beginning, but we need changed when ever only one service updating or the booming traffic.Do you think it is necessary to add a future to solve this situation?

Here is my plan:
Add an key-list struct like upstream struct in consul, as key for every nginx node ip, value for upstream, such as：
10.0.0.1: auth
10.0.0.1: remind
10.0.0.2: feed
it means the nginx node 10.0.0.1 servers for _auth_ and _remind_ service, and 10.0.0.2 servers for feed, and if more traffic of feed coming, we can add _10.0.0.1:feed_ to consul for rebalancing nginx load.

By the way, this issue is inspired by https://github.com/weibocom/nginx-upsync-module/issues/45, @gfrankliu.

**Comment by xiaokai-wang** [comment]
It's cool, thanks.

We are searching for a more general solution. The one above is a little custom I think, which may cause heavy traffic for conf server if having too many upstreams. Or maybe latter, thanks.
