### ISSUE TITLE
Too many health checks

### ISSUE THREAD

**Issue by gfrankliu** [weibocom/nginx-upsync-module#56]
Using the https://github.com/xiaokai-wang/nginx_upstream_check_module , I noticed the same check is done by every nginx worker process. eg: if I have one upstream with two backend servers, each nginx worker process will check those two servers. If I have 32 cpu, and set check interval 1 second, I end up with 32 checks against one backend server every second, and total 64 checks per upstream.

https://github.com/yaoweibin/nginx_upstream_check_module works differently, and only sends one check, no matter how many worker process.

**Comment by xiaokai-wang** [comment]
no, the work model is consistent.

**Comment by gfrankliu** [comment]
I used "check_keepalive_requests", and netstat shows 4 times ESTABLISHED connections if I have 4 cpu when there is no traffic. The only thing is the health check. tcpdump confirms all those connections are sending health checks.
Can you also test and see if you can reproduce?

**Comment by xiaokai-wang** [comment]
be updated, please try again, thanks.

**Comment by gfrankliu** [comment]
Works great, thanks.
