### ISSUE TITLE
Connection to ETCD starts failing after some time

### ISSUE THREAD

**Issue by CallMeFoxie** [weibocom/nginx-upsync-module#59]
Hey,
we've been testing the module in dev for some time now, but we've run into an odd issue - after some time the nginx stops connecting to the ETCD:

2016/04/19 11:05:05 [error] 20129#0: recv() failed (104: Connection reset by peer)
2016/04/19 11:05:05 [error] 20129#0: upsync_recv: recv error with upsync_server: 127.0.0.1:4379

It happens about 2 - 3 hours since last etcd change.

I have not managed to track down as to why this happens - the ETCD log file does not give any hints. I can get data off the etcd just fine, just as after sending HUP to the nginx resets it and it works again fine.

Sadly I am going away until the end of the month so I cannot help to track down the issue right now. 
I thought that the etcd connection should automatically reconnect on failure or closed connection... or not?

**Comment by xiaokai-wang** [comment]
Thank you for all you have done.

Maybe that's a problem, but will not influence the service. I will check that, thanks again.

**Comment by CallMeFoxie** [comment]
The changes in ETCD would not update and reflect in the upstream.

**Comment by xiaokai-wang** [comment]
Ok, I will track that.

**Comment by CallMeFoxie** [comment]
I have managed to come to this, after coming back from vacation :-)

on the line
2684	        if (size > 0) {

I set a breakpoint:

(gdb) p (*((ngx_http_upsync_server_t*)c->data))->ctx->recv->pos
$10 = (u_char *) 0x1abca80 "HTTP/1.0 400 Bad Request\r\nContent-Length: 161\r\nContent-Type: application/json\r\nDate: Mon, 02 May 2016 05:41:55 GMT\r\nX-Etcd-Cluster-Id: 6603f010318e0608\r\nX-Etcd-Index: 119754\r\n\r\n{\"errorCode\":401,\"message\":\"The event in requested index is outdated and cleared\",\"cause\":\"the requested history has been cleared [118755/9529]\",\"index\":119754}\n"

Basically once a lot of writes are done into ETCD, this index is no longer watchable.

Considering how your code works, I suggest setting watch with no specified index anyways - as of right now, when a change comes, you probe the whole ETCD anyways (the response is 'set', not 'get' on index change):
if (ngx_memcmp(action->valuestring, "get", 3) != 0) ... meaning this triggers the whole reload of the node anyways.

Thus I suggest changing
ngx_sprintf(request, "GET %V?wait=true&recursive=true&waitIndex=%d"
and removing the waitIndex=%d

and see what happens.
I can try in my dev env and pull if it works okay after longer time.

(Note that we use other services in this ETCD cluster, so writes happen every few seconds and the Index ID changes a lot).

**Comment by xiaokai-wang** [comment]
You are great, thanks.
