### ISSUE TITLE
替换ngx_http_upstream_check_module.c 文件后，编译还是不通过

### ISSUE THREAD

**Issue by triumph** [weibocom/nginx-upsync-module#6]
替换ngx_http_upstream_check_module.c 文件后，编译还是不通过。
能不能提供一个可用的替换文件啊。

![qq 20151211095106](https://cloud.githubusercontent.com/assets/11950/11733986/222c169e-9fee-11e5-9e4c-fb03e6288c4d.jpg)

**Comment by xiaokai-wang** [comment]
嗯，这样确实有点麻烦

为了方便大家与健康监测模块一起使用，请去 https://github.com/xiaokai-wang/nginx_upstream_check_module 下载健康监测模块，无需修改，直接编译便可

多谢！

**Comment by tietang** [comment]
mac osx 下
/Users/tietang/nginx_openresty/nginx-1.8.0/nginx-upsync-module/src/ngx_http_upsync_module.c:827:28: error: 
      no member named 'check_index' in 'ngx_http_upstream_rr_peer_t'
            peers->peer[m].check_index = index;
            ~~~~~~~~~~~~~~ ^
/Users/tietang/nginx_openresty/nginx-1.8.0/nginx-upsync-module/src/ngx_http_upsync_module.c:1071:32: error: 
      no member named 'check_index' in 'ngx_http_upstream_rr_peer_t'
                peers->peer[n].check_index = tmp_peers->peer[i].check_index;
                ~~~~~~~~~~~~~~ ^
/Users/tietang/nginx_openresty/nginx-1.8.0/nginx-upsync-module/src/ngx_http_upsync_module.c:1071:65: error: 
      no member named 'check_index' in 'ngx_http_upstream_rr_peer_t'
                peers->peer[n].check_index = tmp_peers->peer[i].check_index;
                                             ~~~~~~~~~~~~~~~~~~ ^
/Users/tietang/nginx_openresty/nginx-1.8.0/nginx-upsync-module/src/ngx_http_upsync_module.c:1851:28: error: 
      no member named 'check_index' in 'ngx_http_upstream_rr_peer_t'
            peers->peer[i].check_index = tmp_peers->peer[i].check_index;
            ~~~~~~~~~~~~~~ ^
/Users/tietang/nginx_openresty/nginx-1.8.0/nginx-upsync-module/src/ngx_http_upsync_module.c:1851:61: error: 
      no member named 'check_index' in 'ngx_http_upstream_rr_peer_t'
            peers->peer[i].check_index = tmp_peers->peer[i].check_index;
                                         ~~~~~~~~~~~~~~~~~~ ^

**Comment by tietang** [comment]
mac osx下单独编译
./configure --add-module=/path/to/nginx-upsync-module

/Users/tietang/nginx_openresty/nginx-1.8.0/nginx-upsync-module/src/ngx_http_upsync_module.c:1742:13: error: 
      variable 'status' may be uninitialized when used here
      [-Werror,-Wconditional-uninitialized]
        if (status != NGX_OK) {
            ^~~~~~
/Users/tietang/nginx_openresty/nginx-1.8.0/nginx-upsync-module/src/ngx_http_upsync_module.c:1709:48: note: 
      initialize the variable 'status' to silence this warning
    ngx_int_t                            status;
                                               ^
                                                = 0
1 error generated.

**Comment by xiaokai-wang** [comment]
The first question: nginx_upstream_check_module has a check_1.7.5+.patch

1. move the patch to ../nginx path

2. patch -p1 < check_1.7.5+.patch

The last make.

**Comment by xiaokai-wang** [comment]
The sencond questions is another theme, please make a another issue.

The version is v0.2.1 that you try?

**Comment by xiaokai-wang** [comment]
Fixed, thanks.

Please clone the new source.

**Comment by tietang** [comment]
tks! It's works!

**Comment by liuyue2656** [comment]
编译nginx-upstream-check-module没成功过。

环境：centos7、openresty-1.11.2

**Comment by maomaoaichirou** [comment]
The nginx-1.12.0 Support  nginx-upstream-check-module ？

/nginx/nginx-upsync-module//src/ngx_http_upsync_module.c
/nginx/nginx-upsync-module//src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_add_peers’:
/nginx/nginx-upsync-module//src/ngx_http_upsync_module.c:868:17: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘check_index’
             peer->check_index = index;
                 ^
/nginx/nginx-upsync-module//src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_init_peers’:
/nginx/nginx-upsync-module//src/ngx_http_upsync_module.c:2334:17: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘check_index’
             peer->check_index = tmp_peer[i].check_index;
                 ^
/nginx/nginx-upsync-module//src/ngx_http_upsync_module.c:2334:44: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘check_index’
             peer->check_index = tmp_peer[i].check_index;
                                            ^
make[1]: *** [objs/addon/src/ngx_http_upsync_module.o] Error 1
make[1]: Leaving directory `/nginx/nginx-1.12.0'
make: *** [build] Error 2

**Comment by xiaokai-wang** [comment]
yes, patch first.
