### ISSUE TITLE
etcd rasing memory usage by time

### ISSUE THREAD

**Issue by jpuyy** [weibocom/nginx-upsync-module#60]
using this module, only 10 keys of upstream in etcd.
Etcd cost 16MB memory firstly, then after 6 hours, raise to  523MB。Finally oom.
How to solve the problem.

data from: ps -ylC etcd (RSS filed)
etcd version:  both etcd version 2.0.5 and etcd Version: 2.3.1

**Comment by xiaokai-wang** [comment]
If I am clear your question, that's the problem of etcd, not the problem of the module.

Not much to etcd, sorry.

**Comment by jpuyy** [comment]
So have weibocom using this module in production ?
If weibocom in production, using upsync_type consul or etcd?
Can I get some practical experience of this module in production.

**Comment by xiaokai-wang** [comment]
Consul is used.

The doc dir has some data.

**Comment by xiaokai-wang** [comment]
By the way, as far as I know, others use the module with etcd, not meeting your problem.

Please have a check.

**Comment by jpuyy** [comment]
https://coreos.com/etcd/docs/latest/benchmarks/etcd-3-watch-memory-benchmark.html

You know, I have only 56 upstream keys( include leaf and parent). Do you have an instant contact method?

**Comment by xiaokai-wang** [comment]
@CallMeFoxie , you use etcd, right?

Do you have ever met the problem?

**Comment by CallMeFoxie** [comment]
We have not seen anything related to memory like this... Definitely sounds more like etcd issue rather than nginx-upsync-module.
(We use kernel 3.10.0-rhel7.2-openvz7, in OpenVZ container, etcd 2.3.1)

**Comment by jpuyy** [comment]
@CallMeFoxie 

OK, I will do another try.

kernel 3.10.0-327.13.1.el7.x86_64
etcd 2.3.1
kvm container

With low established connections.
[root@etcd-upstreams-prd ]# netstat -nat | grep ESTABLISHED | wc -l
128

**Comment by jpuyy** [comment]
@CallMeFoxie

May I have your etcd start command ?
I use
`/usr/local/bin/etcd --listen-client-urls http://172.16.1.191:4001 --advertise-client-urls http://172.16.1.191:4001`

**Comment by CallMeFoxie** [comment]
For etcd cluster we use this (note that we use SSL and have clustered environment for failover):

(shortened and redacted)
LISTEN_CLIENT_URLS="https://`hostname`:${client_port},http://127.0.0.1:${client_port}" # https for anybody, http for localhost
ADVERTISE_CLIENT_URLS="https://`hostname`:${client_port}" # but advertise `hostname` only to others
/path/to/etcd \
  --heartbeat-interval 500 \
  --election-timeout 2500 \
  --name `hostname` \
  --data-dir "${datadir}" \
  --initial-cluster "${INITIAL_CLUSTER}" \
  --initial-advertise-peer-urls "https://`hostname`:${peer_port}" \
  --listen-peer-urls "https://0.0.0.0:${peer_port}" \
  --peer-cert-file "${peer_cert}" \
  --peer-key-file "${peer_key}" \
  --peer-trusted-ca-file "${peer_ca}" \
  --trusted-ca-file "${peer_ca}" \
  --listen-client-urls "${LISTEN_CLIENT_URLS}" \
  --advertise-client-urls "${ADVERTISE_CLIENT_URLS}" \
  --peer-client-cert-auth \
  --client-cert-auth \
  ${CLIENT_CERT_FILE} \
  ${CLIENT_KEY_FILE}

For etcd readonly proxy (terminates SSL and listens on localhost only) we use this:
LISTEN_CLIENT_URLS="http://${client_listen}:${client_port}"
/path/to/etcd \
  --name `hostname` \
  --data-dir "${datadir}" \
  --initial-cluster "${INITIAL_CLUSTER}" \
  --listen-client-urls "${LISTEN_CLIENT_URLS}" \
  --peer-trusted-ca-file "${peer_ca}" \
  --peer-cert-file "${peer_cert_file}" \
  --peer-key-file "${peer_key_file}" \
  --proxy readonly

**Comment by jpuyy** [comment]
@CallMeFoxie 
Thanks, Problem solved, etcd execute command should have --snapshot-count 500, i.e.

`/usr/local/bin/etcd --listen-client-urls http://172.16.1.191:4001 --advertise-client-urls http://172.16.1.191:4001 --snapshot-count 500`
