### ISSUE TITLE
May I ask upsync module's "mark server down" feature is gracefully shutting the connection down or not  

### ISSUE THREAD

**Issue by lzw2006** [weibocom/nginx-upsync-module#61]
As title

**Comment by xiaokai-wang** [comment]
not shutting down the connection has already been builded, but the new requests will not go there.

**Comment by lzw2006** [comment]
So what if a long processing request has been reached an upstream server and at the same time I mark the server "down", will the request still return to the client ?

**Comment by gfrankliu** [comment]
"down" will only affect future requests. existing requests that are already in-flight will continue to finish and client will get whatever response from upstream.
BTW, this is an nginx flag, and upsync module simply passes it from consul/etcd to nginx.

**Comment by xiaokai-wang** [comment]
That's totally right, thanks upstair.

**Comment by lzw2006** [comment]
Thanks!
