### ISSUE TITLE
reload takes long time

### ISSUE THREAD

**Issue by gfrankliu** [weibocom/nginx-upsync-module#63]
upsync provides dynamically modifying backend servers without reloading nginx, but when I need to add more virtual hosts and more upstream blocks, nginx reload is still needed.

Whenever we reload nginx (send SIGHUP), we see old nginx process in the state of `nginx: worker process is shutting down` and then go away.

Without upsync module, those old nginx processes disappears almost immediately when there is no traffic, but with upsync module, I see those old nginx processes in "shutting down" state for a long time. In one of my tests, I reloaded nginx three times by sending SIGHUP to the master nginx process 3 times which generated some of those "shutting down" nginx processes. It took more than 5 minutes and finally they went away. The problem is each of those "shutting down" process uses same amount of system memory, and server ran out of memory quickly.

**Comment by CallMeFoxie** [comment]
are those times, by any chance, related to the timeout values for upsync?

**Comment by xiaokai-wang** [comment]
Yes, it is related to the timeout now.

**Comment by gfrankliu** [comment]
Yes, it seems to be related.
I am using consul, not sure if etcd has the same problem.
One interesting thing: even if I temporarily stop consul, "shutting down" nginx processes still take long time to go away. If the "long" is related to the connection between nginx and consul, since consul is not running, shouldn't nginx immediately fail and "shutting down" processes go away quick?

**Comment by gfrankliu** [comment]
During a reload, nginx will keep the old processes in memory until all the existing connections are done. It seems the upsync long pull (upsync_timeout=6m) causes nginx to "think" the old processes are still serving something. During 6m, if you reloads 10 times, you end up with 10x memory usage due to 10 copies of old nginx processes.

Is there a way for upsync module to capture the reload signal and disconnect from consul immediately?

**Comment by gfrankliu** [comment]
@xiaokai-wang 
Reload is basically sending HUP signal to nginx master process. Is there anything you can do to "break" the consul HTTP long pull immediately after receiving the HUP signal? I think by default nginx will wait for all existing HTTP connection to finish (or timeout).

**Comment by xiaokai-wang** [comment]
Nginx will do waiting for all connections done. Let me have a try.

Delay to exit, what the effecting they have?

**Comment by gfrankliu** [comment]
The "delay" may cause out of memory.
For each reload, nginx will keep the old nginx process with old config, and start new nginx process with new config. The memory usage is doubled. 

Using upsync, we don't need to reload when upstream servers have changes, but if we need to add new virtual host or make other changes, we still need to reload. If we have several such changes during the "delay" period, the memory usage will be doubled, tripled, etc. We can quickly run out of memory.

If you can fix the upsync, the old process will go away faster so the memory will go back normal quicker.

**Comment by xiaokai-wang** [comment]
If nginx serve as a proxy, memory cost is little. Will hava a try.
