### ISSUE TITLE
Race condition with ETCD

### ISSUE THREAD

**Issue by CallMeFoxie** [weibocom/nginx-upsync-module#71]
Hi,
We've also noticed yet another problem. With issue #59 fixed we've actually introduced another problem - a race condition. If 2 (or more) things change in ETCD right after each other, then only the first one might get registered.
 -> ETCD is at index 100.
 -> we introduce a change, ETCD is at 101
 -> wait=true triggers for reload, starts downloading and parsing at ETCD index 101
 -> we introduce another change, ETCD is at 102
 -> upsync finishes reloading, thinking we are waiting for 102, but we have already had 102 change

The (probably correct?) fix would be to revert the change and keep waitIndex BUT make sure that the upsync module can handle 400 Bad Request reply with this content: 
{"errorCode":401,"message":"The event in requested index is outdated and cleared","cause":"the requested history has been cleared [216457/211]","index":217456}
which it can not as of right now and keeps triggering only receive errors repeatedly.

I have no idea if consul drops old indexes as well. If yes then the original issue exists there as well.

**Comment by xiaokai-wang** [comment]
Consul is different with etcd about the index working mode.

A index is corresponding one change in consul, however for etcd corresponding one key.

So etcd need two request for all changes in my realizing.

**Comment by CallMeFoxie** [comment]
Index changes with any write operation to ETCD.
But, as was originally discussed in #59, when there are too many changes "outside" of the watched key/directory, the server starts returning 400 Bad Request and further error description within the JSON and the whole key/directory has to be reloaded to get the new watch key.
I have managed to do a possible fix for this - https://github.com/CallMeFoxie/nginx-upsync-module/commit/261c01a892e0e9a5208510bddda8236d3528a58b - but I am not sure if it won't break Consul since I am passing 400 status into the JSON parsing as well? This code forces reload by setting watch index back to 0 when it reaches past its usability date.

**Comment by xiaokai-wang** [comment]
Looks like all problem attributable to the index of etcd. Needing to reconfirm the problem.

**Comment by xiaokai-wang** [comment]
It's no relation with consul, they are different parse_json function.

**Comment by CallMeFoxie** [comment]
Yes but I pass even 400 error page to the consul as well.

**Comment by CallMeFoxie** [comment]
FIxed in #81
