### ISSUE TITLE
nginx errors for upsync

### ISSUE THREAD

**Issue by xidianwlc** [weibocom/nginx-upsync-module#74]
nginx error log：
2016/05/16 11:03:08 [error] 15506#0: upsync_recv: recv error with upsync_server: 192.168.56.101:8500
2016/05/16 11:08:21 [error] 15506#0: recv() failed (104: Connection reset by peer)
2016/05/16 11:08:21 [error] 15506#0: upsync_recv: recv error with upsync_server: 192.168.56.101:8500
2016/05/16 11:13:34 [error] 15506#0: recv() failed (104: Connection reset by peer)
2016/05/16 11:13:34 [error] 15506#0: upsync_recv: recv error with upsync_server: 192.168.56.101:8500
2016/05/16 11:14:54 [error] 15508#0: send() failed (104: Connection reset by peer)
2016/05/16 11:14:54 [error] 15508#0: upsync_send: send error with upsync_server: 192.168.56.101:8500
2016/05/16 11:24:20 [error] 15506#0: recv() failed (104: Connection reset by peer)
2016/05/16 11:24:20 [error] 15506#0: upsync_recv: recv error with upsync_server: 192.168.56.101:8500

how to avoiding these nginx errors

**Comment by gfrankliu** [comment]
Is consul server down or being blocked?

**Comment by xidianwlc** [comment]
consul server is ok and not being blocked

**Comment by xiaokai-wang** [comment]
A single node is ok. Can you have a check the log of consul?

**Comment by xidianwlc** [comment]
2016/05/13 16:09:19 [ERR] http: Request GET /v1/kv/online/upstreams/test/newtest?recurse&index=0, error: No cluster leader from=192.168.56.101:34311
    2016/05/13 16:09:28 [ERR] http: Request GET /v1/kv/online/upstreams/test/newtest?recurse&index=0, error: No cluster leader from=192.168.56.101:34313
    2016/05/13 16:09:29 [ERR] http: Request GET /v1/kv/online/upstreams/cps_python/newcps?recurse&index=0, error: No cluster leader from=192.168.56.101:34314
    2016/05/13 16:09:30 [ERR] http: Request GET /v1/kv/online/upstreams/cps_python/newcps?recurse&index=0, error: No cluster leader from=192.168.56.101:34315
    2016/05/13 16:09:39 [ERR] http: Request GET /v1/kv/online/upstreams/cps_python/newcps?recurse&index=0, error: No cluster leader from=192.168.56.101:34317
    2016/05/13 16:09:39 [ERR] http: Request GET /v1/kv/online/upstreams/test/newtest?recurse&index=0, error: No cluster leader from=192.168.56.101:34318
    2016/05/13 16:09:41 [ERR] http: Request GET /v1/kv/online/upstreams/test/newtest?recurse&index=0, error: No cluster leader from=192.168.56.101:34319
    2016/05/13 16:09:42 [ERR] agent: failed to sync remote state: No cluster leader

**Comment by senthilkumar-kj** [comment]
@xidianwlc if you are running one node and not in dev mode, I think you have to add bootstrap. This is how I run the server in my local.

**consul agent -server -data-dir=/opt/consul -bootstrap**

please try this and see if it serves requests

**Comment by xidianwlc** [comment]
OK, I will hava a try

**Comment by chenge191** [comment]
i have the same error，how to solve it @xidianwlc @gfrankliu @xiaokai-wang

**Comment by aak1247** [comment]
It has been solved?
