### ISSUE TITLE
nginx-1.9.15编译报错：‘ngx_http_upstream_rr_peer_t’ has no member named ‘check_index’

### ISSUE THREAD

**Issue by stormgbs** [weibocom/nginx-upsync-module#75]
系统环境：
CentOS-6.3 
gcc-4.4.6
nginx-1.9.15

`modules/nginx-upsync-module/src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_add_peers’:  
modules/nginx-upsync-module/src/ngx_http_upsync_module.c:823: error:   ‘ngx_http_upstream_rr_peer_t’ has no member named ‘check_index’  
modules/nginx-upsync-module/src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_del_peers’:  
modules/nginx-upsync-module/src/ngx_http_upsync_module.c:1001: error:   ‘ngx_http_upstream_rr_peer_t’ has no member named ‘check_index’  
modules/nginx-upsync-module/src/ngx_http_upsync_module.c:1001: error:   ‘ngx_http_upstream_rr_peer_t’ has no member named ‘check_index’  
modules/nginx-upsync-module/src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_init_peers’:  
modules/nginx-upsync-module/src/ngx_http_upsync_module.c:2186: error:   ‘ngx_http_upstream_rr_peer_t’ has no member named ‘check_index’  
modules/nginx-upsync-module/src/ngx_http_upsync_module.c:2186: error:   ‘ngx_http_upstream_rr_peer_t’ has no member named ‘check_index’`  

请问upsync支持到nginx哪个最新小版本号？

**Comment by gfrankliu** [comment]
可以使用分支：https://github.com/weibocom/nginx-upsync-module/tree/nginx-upsync-1.9.x

**Comment by stormgbs** [comment]
@gfrankliu upstream-check模块和upsync模块冲突，两者只能存一，同时打开就会编译报错：  

> objs/addon/src/ngx_http_upsync_module.o: In function `ngx_http_upsync_add_peers':
/home/gaobushuang/nginx_dir/nginx-1.9.15/modules/nginx-upsync-module/src/ngx_http_upsync_module.c:845: undefined reference to `ngx_http_upstream_check_add_dynamic_peer'
objs/addon/src/ngx_http_upsync_module.o: In function `ngx_http_upsync_del_peers':
/home/gaobushuang/nginx_dir/nginx-1.9.15/modules/nginx-upsync-module/src/ngx_http_upsync_module.c:988: undefined reference to `ngx_http_upstream_check_delete_dynamic_peer'
collect2: ld returned 1 exit status
make[1]: *** [objs/nginx] Error 1
make[1]: Leaving directory `/home/gaobushuang/nginx_dir/nginx-1.9.15'
make: *** [build] Error 2

**Comment by gfrankliu** [comment]
必须用这个 https://github.com/xiaokai-wang/nginx_upstream_check_module

**Comment by stormgbs** [comment]
@gfrankliu 
用xiaokai-wang的那个就会报最初的错误：
> modules/nginx-upsync-module/src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_add_peers’:
modules/nginx-upsync-module/src/ngx_http_upsync_module.c:847: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘check_index’
modules/nginx-upsync-module/src/ngx_http_upsync_module.c: In function ‘ngx_http_upsync_init_peers’:
modules/nginx-upsync-module/src/ngx_http_upsync_module.c:2137: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘check_index’
modules/nginx-upsync-module/src/ngx_http_upsync_module.c:2137: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘check_index’
make[1]: *** [objs/addon/src/ngx_http_upsync_module.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/home/gaobushuang/nginx_dir/nginx-1.9.15'
make: *** [build] Error 2  

>  ~/nginx_dir/nginx-1.9.15/modules/nginx-upsync-module$ > git status
# On branch nginx-upsync-1.9.x
nothing to commit (working directory clean)

**Comment by gfrankliu** [comment]
Check module 的布丁加了吗？check_1.9.2+.patch

**Comment by stormgbs** [comment]
@gfrankliu 汗，终于过去了，应该是patch打了多次多乱了。 
重新解压了nginx源码，然后：
patch -p0 < modules/nginx_upstream_check_module/check_1.9.2+.patch 
就可以过去。

**Comment by stormgbs** [comment]
@gfrankliu 非常感谢，高效的支持回复：）

**Comment by stormgbs** [comment]
Mark下， nginx-1.10 也可以编译通过。

**Comment by blurcat** [comment]
> @gfrankliu 汗，终于过去了，应该是patch打了多次多乱了。
> 重新解压了nginx源码，然后：
> patch -p0 < modules/nginx_upstream_check_module/check_1.9.2+.patch
> 就可以过去。

是的，照这个方法nginx-1.10.3可以成功
