### ISSUE TITLE
Do you have cli/ui for manage k/v

### ISSUE THREAD

**Issue by jpuyy** [weibocom/nginx-upsync-module#76]
If nginx upsync will tuning a lot, Do you have any cli or ui for manage the consul or etcd?

I want to do this, any ideas?

**Comment by senthilkumar-kj** [comment]
Are you looking for this? https://www.consul.io/intro/getting-started/kv.html

**Comment by gfrankliu** [comment]
This is a popular consul cli: https://github.com/CiscoCloud/consul-cli
