### ISSUE TITLE
nginx-1.8.1 编译失败

### ISSUE THREAD

**Issue by zexuan** [weibocom/nginx-upsync-module#86]
我从master分支上pull的代码，和nginx-1.8.1一起编译的时候，编译不能通过，报如下错误：ngx_http_upsync_module.c:827:19: error: no member named 'next' in 'ngx_http_upstream_rr_peer_t'，

系统 OSX 10.10.5

该扩展不支持nginx-1.8.1，或者不支持osx，还是有什么bug？

**Comment by CallMeFoxie** [comment]
master = 1.9/1.10 branch... nginx-upsync-1.8.x is the 1.8 branch :)

**Comment by zexuan** [comment]
got it, thx

**Comment by chenge191** [comment]
怎么解决的。求解答
