### ISSUE TITLE
conflicts between nginx-upsync-module and nginx-stream-upsync-module

### ISSUE THREAD

**Issue by gfrankliu** [weibocom/nginx-upsync-module#87]
I tried to include both nginx-upsync-module and nginx-stream-upsync-module but got lots of function redefinitions. It seems both modules include the same http_parser.c and json.c. Is it possible to add some ifdef like what we did in http_parser.h and json.h so that they won't conflict if someone tries to include both modules?

**Comment by CallMeFoxie** [comment]
I created this meta addon to solve that issue: https://github.com/CallMeFoxie/nginx-upsync

**Comment by gfrankliu** [comment]
Yes it makes sense to combine the two into one because of lots of overlapping . It will also make it easier to maintain and you don't have to fix the same bug in two places .
