### ISSUE TITLE
一直报连接upsync_server失败，但是upstream实际更新却没有问题

### ISSUE THREAD

**Issue by workhardcc** [weibocom/nginx-upsync-module#88]
Hi，报错如下：

> 2016/06/27 13:45:56 [error] 6675#0: upsync_timeout: timed out reading upsync_server: 10.93.79.49:4001 
> 2016/06/27 13:46:27 [error] 6675#0: upsync_timeout: timed out reading upsync_server: 10.93.79.49:4001 
> 2016/06/27 13:51:58 [error] 6675#0: upsync_timeout: timed out reading upsync_server: 10.93.79.49:4001 
> 2016/06/27 13:52:29 [error] 6675#0: upsync_timeout: timed out reading upsync_server: 10.93.79.49:4001 
> 2016/06/27 13:57:59 [error] 6675#0: upsync_timeout: timed out reading upsync_server: 10.93.79.49:4001 
> 2016/06/27 13:58:30 [error] 6675#0: upsync_timeout: timed out reading upsync_server: 10.93.79.49:4001 
> 2016/06/27 14:04:00 [error] 6675#0: upsync_timeout: timed out reading upsync_server: 10.93.79.49:4001 
> 2016/06/27 14:04:31 [error] 6675#0: upsync_timeout: timed out reading upsync_server: 10.93.79.49:4001 
> 2016/06/27 14:10:03 [error] 6675#0: upsync_timeout: timed out reading upsync_server: 10.93.79.49:4001 
> 2016/06/27 14:10:32 [error] 6675#0: upsync_timeout: timed out reading upsync_server: 10.93.79.49:4001 
> 2016/06/27 14:16:03 [error] 6675#0: upsync_timeout: timed out reading upsync_server: 10.93.79.49:4001 
> 2016/06/27 14:16:34 [error] 6675#0: upsync_timeout: timed out reading upsync_server: 10.93.79.49:4001 
> 2016/06/27 14:22:05 [error] 6675#0: upsync_timeout: timed out reading upsync_server: 10.93.79.49:4001 
> 2016/06/27 14:22:35 [error] 6675#0: upsync_timeout: timed out reading upsync_server: 10.93.79.49:4001 
> 2016/06/27 14:28:06 [error] 6675#0: upsync_timeout: timed out reading upsync_server: 10.93.79.49:4001 
> 2016/06/27 14:28:36 [error] 6675#0: upsync_timeout: timed out reading upsync_server: 10.93.79.49:4001
实际上每次对upstream的修改模块都能及时更新并无问题。规律是每6分钟一组报错（同upsync_timeout=6m这个配置相同），每组报错内的两个报错又间隔大约30s

**Comment by workhardcc** [comment]
额，每六分钟报一次“upsync_timeout: timed out reading upsync_server: 10.93.79.49:4001”好像是正常的，这个case可以close。
但为什么距离上一次5分30秒的时候就报一次连接超时，距离上一次6分钟的时候再报一次？
还有个问题：“upsync_parse_json: value is invalid”这个错是哪里的问题？

**Comment by workhardcc** [comment]
感谢回答  我再看看！

**Comment by workhardcc** [comment]
1.那就意味着每轮拉取有两次动作（如果本轮时间周期内没有变化），一次是upsync_timeout=6m这里定义的6分钟，另一次是6m+随机时间？
2.upsync_parse_json: value is invalid 这个报错并不是时刻都有，我看好像是每隔18分钟就报一次，看起来不像是数据的问题啊
`curl http://10.93.1.1:4001/v2/keys/upstreams/k8s_upstream_test/172.16.71.2:8000`

> {"action":"get","node":{"key":"/upstreams/k8s_upstream_test/172.16.71.2:8000","value":"{\"weight\":2, \"max_fails\":2, \"fail_timeout\":5}","modifiedIndex":1654669,"createdIndex":1654669}}
数据看起来挺正常的。。。

**Comment by xiaokai-wang** [comment]
1. 只拉取一次，拉取时间是配置时间+一个随机时间；

2. 不是经常报？那这个很奇怪，能不能gdb 一下？

感谢！

**Comment by workhardcc** [comment]
hi  此前没有nginx经验没有C语言经验，照着这篇文章（http://www.lenky.info/archives/2011/09/58 ）照猫画虎操作了一下，不知道下面的gdb内容是否能解决问题。如不行还请指导一下，谢谢！
```
gdb -q
(gdb) shell ./nginx
(gdb) shell pidof nginx
7153 7152
(gdb) attach 7153
Attaching to process 7153
Reading symbols from /usr/local/nginx/sbin/nginx...done.
Reading symbols from /lib64/libdl.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libdl.so.2
Reading symbols from /lib64/libpthread.so.0...(no debugging symbols found)...done.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Loaded symbols for /lib64/libpthread.so.0
Reading symbols from /lib64/libcrypt.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libcrypt.so.1
Reading symbols from /lib64/libm.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libm.so.6
Reading symbols from /lib64/libpcre.so.1...Reading symbols from /lib64/libpcre.so.1...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libpcre.so.1
Reading symbols from /lib64/libcrypto.so.10...Reading symbols from /lib64/libcrypto.so.10...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libcrypto.so.10
Reading symbols from /lib64/libz.so.1...Reading symbols from /lib64/libz.so.1...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libz.so.1
Reading symbols from /lib64/libc.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libc.so.6
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/ld-linux-x86-64.so.2
Reading symbols from /lib64/libfreebl3.so...Reading symbols from /lib64/libfreebl3.so...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libfreebl3.so
Reading symbols from /lib64/libnss_files.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libnss_files.so.2
Reading symbols from /lib64/libnss_sss.so.2...Reading symbols from /lib64/libnss_sss.so.2...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libnss_sss.so.2
0x00007f3ff7cad7d3 in __epoll_wait_nocancel () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-105.el7.x86_64 nss-softokn-freebl-3.16.2.3-13.el7_1.x86_64 openssl-libs-1.0.1e-51.el7_2.4.x86_64 pcre-8.32-15.el7.x86_64 sssd-client-1.13.0-40.el7.x86_64 zlib-1.2.7-15.el7.x86_64
(gdb) 
(gdb) 
(gdb)  b ngx_process_events_and_timers
Breakpoint 1 at 0x426e7c: file src/event/ngx_event.c, line 195.
(gdb) c
Continuing.

Breakpoint 1, ngx_process_events_and_timers (cycle=cycle@entry=0x1296070) at src/event/ngx_event.c:195
195	{
(gdb) detach
Detaching from program: /usr/local/nginx/sbin/nginx, process 7153
```

**Comment by xiaokai-wang** [comment]
这些信息并不能说明问题；

1. 可以在conf 配置文件里，全局下加上一个配置项：master_process off; 此时只会有一个进程，同时处理请求；

2. 你也可以把work_processes 配置为1，然后 gdb -p process_number of work process. 在里面设置断点，打出拉取解析的信息

**Comment by CallMeFoxie** [comment]
I use

set detach-on-fork off
set follow-fork-mode child

when debugging with gdb to break even on child processes

**Comment by workhardcc** [comment]
hi 上面提到的这个问题,我找公司一个会C的同学通过打日志的方式解决了，感谢两位的指导。
问题的原因是：我在最开始的时候对一个key赋值，这个key的值格式不对，我当时没有注意，当我再给一些新的key赋值的时候，模块会自动检查一遍所有key的值是否正确，这个时候它会把最开始的那个值的错误报出来，这样给人一个错觉是：我最近新增的key的值是错误的，于是我就在纠结到底哪里错了，而忽略了这个错误并不是新进的，而是一直就有。
这个其实不算是1个问题，是我自己的疏忽大意，但是各位也可以考虑一下打个日志或者别的方式避免这类问题出现啥的，再次感谢各位的帮助。

**Comment by xiaokai-wang** [comment]
Ok, got! Printing the value is much better. Thanks.

**Comment by workhardcc** [comment]
另外，是不是如果一个upstream的配置不正确，会导致别的配置正确upstream的配置也不生效啊？

**Comment by xiaokai-wang** [comment]
不影响，相互独立

**Comment by workhardcc** [comment]
ok ,多谢
