### ISSUE TITLE
max_fails=1 fail_timeout=10s参数可以去掉？

### ISSUE THREAD

**Issue by workhardcc** [weibocom/nginx-upsync-module#89]
nginx version：1.10.1
编译命令：./configure --add-module=/path/to/nginx-upsync-module
经测试关掉N台upstream中的一台，nginx并不会踢掉故障的机器
如果加上模块nginx-upstream-check-module，其对应的检测命令类似：check interval=5000 rise=1 fall=2 timeout=4000;
所以max_fails=1 fail_timeout=10s显得没有任何意义？

**Comment by xiaokai-wang** [comment]
是的，这两个地方有点重复，如果用了健康监测模块，这两个属性可以省略

**Comment by workhardcc** [comment]
其实我想表达的意思是：如果我不用健康监测模块，max_fails=1 fail_timeout=10s也没有任何意义。测试发现这两个参数并不能使nginx正确踢掉故障的机器（nginx 1.10.1版本似乎是自带健康检查的）。  不过也不必深究，加上健康检查模块可以满足我的需求了，感谢回复！

**Comment by workhardcc** [comment]
我知道为啥

> 如果我不用健康监测模块，max_fails=1 fail_timeout=10s也没有任何意义。测试发现这两个参数并不能使nginx正确踢掉故障的机器（nginx 1.10.1版本似乎是自带健康检查的）

因为`upsync_parse_json: value is invalid`这个报错表明`{weight:2, max_fails:2, fail_timeout:5}`这些参数并没有生效，但是这些参数哪里有问题呢？

**Comment by xiaokai-wang** [comment]
1. max_fails  和 fail_timeout 这两个参数并不是把故障的机器踢掉，而是在timeout 的时间内 如果失败了fails 次，则不再访问，过了timeout 时间段，还是会继续访问；

2. upsync_parse_json: value is invalid, 报这个错说明格式有问题，麻烦请给出更加详细的信息，多谢！

**Comment by workhardcc** [comment]
感谢您的回答，我此前对nginx了解不多，第一点见笑了
1.我在故意停掉upstream中的某一台机器的服务以后（一共两台后端realserver），再去多次访问测试页面基本上是一次成功一次失败，这说明流量还是打到了故障的那台realserver，进而表明max_fails 和 fail_timeout 这两个参数没有生效.
2.这个问题我在另一个issue里gdb给你看，这个就先close。再次感谢！

**Comment by xiaokai-wang** [comment]
多谢！

欢迎交流学习.
