### ISSUE TITLE
在现有流程中加入对server配置的管理是否可行？

### ISSUE THREAD

**Issue by skyeydemon** [weibocom/nginx-upsync-module#92]
一个服务典型的nginx配置包含server配置项（location等）和upstream配置项。
在nginx-upsync-module现有流程/框架下能否考虑加入对于这一部分的支持。比如server配置项作为文本对象存储管理。
如果能实现，作用非常大。

**Comment by xiaokai-wang** [comment]
这个暂时没有调研过，但是server 二级配置，涉及到的点太多，比较复杂
