### ISSUE TITLE
upstream_show报502

### ISSUE THREAD

**Issue by chenge191** [weibocom/nginx-upsync-module#96]
curl http://10.13.0.99:90/upstream_list?test -i
报
HTTP/1.1 502 Bad Gateway

**Comment by xiaokai-wang** [comment]
麻烦贴一下配置

**Comment by chenge191** [comment]
是按照你的wiki里直接粘贴过来的，发现wiki里 /upstream_list前少了个= ，加上=好了
 location /upstream_list {
         upstream_show;
     }

**Comment by chenge191** [comment]
@xiaokai-wang upstream_show返回的结果是否没有节点对应的健康状态
