### ISSUE TITLE
我想了解下可以实现下面这样的需求吗？

### ISSUE THREAD

**Issue by luohoufu** [weibocom/nginx-upsync-module#97]
应用场景(阿里云)：
 DNS -> SLB -> {[ECS(OpenResty)],[ECS(OpenResty)]} -> { [SLB -> ECS1,ECS2],[SLB -> ECS1,ECS2],...}

说明：
　　　ECS(OpenResty)中通过判断HTTP头中的X-Service-Name到Redis中查询对应的服务地址(上游的SLB地址, 即{ [SLB -> ECS1,ECS2],[SLB -> ECS1,ECS2],...})

目标：
现想采用　nginx-upsync-module　模块来替换上游SLB，动态访问到 { [SLB -> ECS1,ECS2],[SLB -> ECS1,ECS2],...}

请问可以实现吗？

**Comment by xiaokai-wang** [comment]
本模块只支持已有服务的弹性扩容、缩容，不支持服务的动态调度；

或者我可以理解为你的redis 承担着配置中心（命名服务）的角色，nginx 的两个不同的服务（upstream）都配置上此模块，从而拉取后端的server 资源；在/url 路径下，可以根据http 头的信息从而打到不同的后端（upstream）？

如果是上面的情况是可以用的

**Comment by luohoufu** [comment]
@xiaokai-wang 不好意思，我没说清楚，主要是写的太急了。确实是你的那种情况redis承担了类似命名服务的配置中心。
我后来自己也仔细思考了下，应该是可以实现。请教你有没有更好的思路？
例子(域名及ip均假设)：
请求URL：http://dev.up/
请求头中X-Service-Name：order
域名： dev.up   对应IP：66.66.66.66
上游服务器IP： 10.0.0.10
　　　　　　   10.0.0.11
上游服务：http://10.0.0.10:8080/order/info
                 http://10.0.0.11:8080/order/info

请求URL：http://dev.up/
请求头中X-Service-Name：register
域名： dev.up   对应IP：66.66.66.66
上游服务器IP： 10.0.0.12
　　　　　　   10.0.0.13
上游服务：http://10.0.0.12:8080/member/add
                 http://10.0.0.13:8080/member/add

如果普通的nginx配置会产生多个upstream，并且upstream后,反向代理proxy_pass的url还是动态的。
原来可以直接从redis里取出上游负载的地址，缺点是访问层级多了一层负载，现在拿掉上游的负载就需要配合nginx-upsync-module（弹性扩容、缩容）、并且手动实现url动态路由。

**Comment by xiaokai-wang** [comment]
```
upstream register {
        server 127.0.0.1:11111;

        upsync 127.0.0.1:9091/v1/kv/upstreams/register upsync_timeout=6m upsync_interval=500ms upsync_type=consul strong_dependency=off;
        upsync_dump_path /usr/local/nginx/conf/servers/servers_register.conf;
}
upstream order {
        server 127.0.0.1:11111;

        upsync 127.0.0.1:9091/v1/kv/upstreams/order upsync_timeout=6m upsync_interval=500ms upsync_type=consul strong_dependency=off;
        upsync_dump_path /usr/local/nginx/conf/servers/servers_order.conf;
}

server {

    ........

    location / {
            if($http_x_service_name = order) {
                rewrite ^(.*)$ /order/info break;
            }
            if ( ) {
               ....
             }
     }
   
     location ^ /order/info {
            proxy_pass http://order;
    }
}
```

如此？

你的redis server 的数据格式必须符合现有的，或者从新组织、从新解析.

**Comment by xiaokai-wang** [comment]
另redis 是基于tcp，当前是基于http.

**Comment by luohoufu** [comment]
@xiaokai-wang 谢谢，很受启发！！！
原来的取upstream动态url(路由)的逻辑是通过lua来写的，现在看来nginx.conf也可以达到目的。
就是一旦上游服务接口几十个模块几百个接口时配置文件会变得很长。
