### ISSUE TITLE
upstream 中默认server怎么保留?(想做灰度发布)

### ISSUE THREAD

**Issue by insoz** [weibocom/nginx-upsync-module#99]
#### 需求:
正常服务:  http://10.211.55.12:8080
测试服务:  http://10.211.55.12:8080/?tn=test
Consul 注册两个upstream 服务, 正常用户访问test, 测试用户访问testlocal

我现在的想法是测试用户进来都访问`upstream testlocal ` 中配置的默认server, 然后有新服务部署后,自动去注册服务的IP和端口到`upstream testlocal ` , 测试完成后删除新注册的服务, 让它访问默认server, 但是现在我测试,删除新注册的服务后, 请求还是到新服务, 重启nginx才能请求到默认server, 有什么方法能使用默认server?  或者您还有什么好的做灰度发布的方法给我推荐一个?

#### 配置文件:
```nginx
upstream test {
    server 127.0.0.1:1092;
        upsync 10.211.55.11:8500/v1/kv/upstreams/test/ upsync_timeout=6m upsync_interval=500ms upsync_type=consul strong_dependency=off;
        upsync_dump_path /tmp/test.conf;
    }

    upstream testlocal {
    server 127.0.0.1:1091;
        upsync 10.211.55.11:8500/v1/kv/upstreams/testlocal/ upsync_timeout=6m upsync_interval=500ms upsync_type=consul strong_dependency=on;
        upsync_dump_path /tmp/testlocal.conf;
    }

    server {
        listen 8080;

        location = / {
        proxy_pass http://test;
        if ( $arg_tn = test ) {
        proxy_pass http://testlocal;
            }
        }
}
```

**Comment by xiaokai-wang** [comment]
把你的默认server 也注册到consul

**Comment by insoz** [comment]
后端服务只有两台, 如果把默认server也注册到consul , 那么测试时访问的有可能是以前的代码,nginx 会轮询的吧?  起不到测试的作用了...

**Comment by xiaokai-wang** [comment]
我的意思是，当你需要测试新的服务时，就把默认server的删除，然后注册新的服务ip:port；然后需要把新的服务下掉的时候，再注销旧的服务，再把默认的server注册上去；比较tricky，但是应该是work 的；可以try 一下
